"""initial schema — all 7 core tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-14

Creates users, email_verifications, api_keys, papers, materials, chunks,
and stats_cache per PROJECT_SPEC.md section 4. This migration is
hand-written (not autogenerated) so it can land before a live database
exists; it matches api/models/db.py exactly.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # for gen_random_uuid

    # --- users ------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("institution", sa.String(500)),
        sa.Column("country", sa.String(100)),
        sa.Column("age", sa.SmallInteger()),
        sa.Column("research_area", sa.String(255)),
        sa.Column("purpose", sa.Text()),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("last_login", sa.TIMESTAMP(timezone=True)),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.CheckConstraint("age IS NULL OR (age >= 13 AND age <= 120)",
                           name="ck_users_age_range"),
    )

    # --- email_verifications ---------------------------------------------
    op.create_table(
        "email_verifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token", sa.String(64), nullable=False, unique=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )

    # --- api_keys ---------------------------------------------------------
    op.create_table(
        "api_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("key_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("key_prefix", sa.String(12), nullable=False),
        sa.Column("name", sa.String(100)),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("last_used", sa.TIMESTAMP(timezone=True)),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )

    # --- papers -----------------------------------------------------------
    op.create_table(
        "papers",
        sa.Column("id", sa.String(100), primary_key=True),
        sa.Column("source", sa.String(20), nullable=False),
        sa.Column("arxiv_id", sa.String(20)),
        sa.Column("doi", sa.String(200)),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", postgresql.JSONB(), nullable=False),
        sa.Column("affiliations", postgresql.JSONB()),
        sa.Column("date_submitted", sa.Date()),
        sa.Column("date_published", sa.Date()),
        sa.Column("journal", sa.String(300)),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("categories", postgresql.JSONB()),
        sa.Column("material_family", sa.String(50)),
        sa.Column("status", sa.String(20), nullable=False, server_default=sa.text("'published'")),
        sa.Column("retraction_date", sa.Date()),
        sa.Column("retraction_reason", sa.Text()),
        sa.Column("citation_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("materials_extracted", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("quality_flags", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("indexed_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    op.create_index("idx_papers_family", "papers", ["material_family"])
    op.create_index("idx_papers_date", "papers", ["date_published"])
    op.create_index("idx_papers_status", "papers", ["status"])
    op.create_index("idx_papers_arxiv", "papers", ["arxiv_id"])

    # --- materials --------------------------------------------------------
    op.create_table(
        "materials",
        sa.Column("id", sa.String(100), primary_key=True),
        sa.Column("formula", sa.String(200), nullable=False),
        sa.Column("formula_normalized", sa.String(200), nullable=False),
        sa.Column("formula_latex", sa.String(200)),
        sa.Column("family", sa.String(50)),
        sa.Column("subfamily", sa.String(100)),
        sa.Column("crystal_structure", sa.String(100)),
        sa.Column("tc_max", sa.REAL()),
        sa.Column("tc_max_conditions", sa.String(300)),
        sa.Column("tc_ambient", sa.REAL()),
        sa.Column("pairing_symmetry", sa.String(100)),
        sa.Column("discovery_year", sa.SmallInteger()),
        sa.Column("total_papers", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("status", sa.String(50), nullable=False,
                  server_default=sa.text("'active_research'")),
        sa.Column("records", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    op.create_index("idx_materials_family", "materials", ["family"])
    op.create_index(
        "idx_materials_tc",
        "materials",
        [sa.text("tc_max DESC NULLS LAST")],
    )

    # --- chunks -----------------------------------------------------------
    op.create_table(
        "chunks",
        sa.Column("id", sa.String(200), primary_key=True),
        sa.Column("paper_id", sa.String(100), sa.ForeignKey("papers.id"), nullable=False),
        sa.Column("title", sa.Text()),
        sa.Column("authors_short", sa.String(200)),
        sa.Column("year", sa.SmallInteger()),
        sa.Column("section", sa.String(200)),
        sa.Column("chunk_index", sa.SmallInteger()),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("material_family", sa.String(50)),
        sa.Column("materials_mentioned", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("has_equation", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("has_table", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.create_index("idx_chunks_paper", "chunks", ["paper_id"])

    # --- stats_cache ------------------------------------------------------
    op.create_table(
        "stats_cache",
        sa.Column("key", sa.String(100), primary_key=True),
        sa.Column("value", postgresql.JSONB(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("stats_cache")
    op.drop_index("idx_chunks_paper", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("idx_materials_tc", table_name="materials")
    op.drop_index("idx_materials_family", table_name="materials")
    op.drop_table("materials")
    op.drop_index("idx_papers_arxiv", table_name="papers")
    op.drop_index("idx_papers_status", table_name="papers")
    op.drop_index("idx_papers_date", table_name="papers")
    op.drop_index("idx_papers_family", table_name="papers")
    op.drop_table("papers")
    op.drop_table("api_keys")
    op.drop_table("email_verifications")
    op.drop_table("users")
