import readiness from "@/public/research-pilots/discovery-experimental-readiness-2026-10-06.json";

const labels: Record<string, string> = { "oxide_metallic:tc": "Reported recommended Tc", "oxide_metallic:t1": "Zero resistance", "oxide_metallic:t2": "Resistance midpoint", "oxide_metallic:t3": "Resistance R=100%", "oxide_metallic:tcsus": "Magnetic susceptibility", "oxide_metallic:tcn": "Measurement lower-temperature bound", "organic:tc": "Reported organic Tc", "organic:tcmax": "Maximum organic Tc under pressure", "organic:tcn": "Organic measurement lower-temperature bound" };
const number = (n: number) => n.toLocaleString("en-US");

export function DiscoveryExperimentalQueue() {
  return <section className="min-w-0 space-y-3" aria-labelledby="experimental-queue-heading">
    <h2 id="experimental-queue-heading" className="font-semibold">Experimental evidence queue</h2>
    <p className="max-w-3xl text-sm text-sage-muted">Replayed {number(readiness.source_inventory.oxide_metallic.rows)} oxide and metallic source rows and {number(readiness.source_inventory.organic.rows)} organic rows. Criterion channels remain separate; row cohorts overlap.</p>
    <div className="relative max-w-full overflow-x-auto rounded-lg border border-sage-border" tabIndex={0} role="region" aria-label="Experimental evidence channels, scroll horizontally for all columns"><table className="w-full min-w-[600px] text-left text-sm"><caption className="sr-only">Source expressions requiring label review. Counts are not independent experiments or approved training samples.</caption><thead className="bg-sage-surface text-sage-muted"><tr><th scope="col" className="p-3">Source channel</th><th scope="col" className="p-3">Expressions</th><th scope="col" className="p-3">Positive value with explicit K</th></tr></thead><tbody>{Object.entries(readiness.channels).map(([key, c]) => <tr key={key} className="border-t border-sage-border"><th scope="row" className="p-3 font-normal">{labels[key] ?? `${c.source_table}: ${c.source_field}`}<p className="text-xs text-sage-muted">{c.expression_role === "measurement_lower_temperature_not_tc" ? "Censored measurement bound; not a Tc or zero label" : "Source expression requiring review"}</p></th><td className="p-3 tabular-nums">{number(c.expressions)}</td><td className="p-3 tabular-nums">{c.expression_role === "measurement_lower_temperature_not_tc" ? "Not a Tc label" : number(c.positive_with_explicit_kelvin)}</td></tr>)}</tbody></table></div>
    <p className="max-w-3xl text-sm">Training eligibility is unresolved. Review source versions, sample identity, Tc criterion, units, measurement conditions and data-use permissions before freezing material and source groups for held-out validation.</p>
    <details className="text-sm"><summary className="cursor-pointer py-2">Source and remaining review tasks</summary><div className="space-y-2"><p>{readiness.source_license.attribution} · <a className="site-text-link" href={readiness.source_license.dataset_doi}>Source dataset</a> · recorded license: {readiness.source_license.recorded_license}</p><ul className="list-disc space-y-1 pl-5">{readiness.next_actions.map(a => <li key={a}>{a}</li>)}</ul><p>No model has been trained by this replay. Scores, uncertainty and admitted-label counts remain unassigned.</p></div></details>
  </section>;
}
