"use client";

import { useEffect, useRef, useState } from "react";
import { useDashboardUser } from "@/components/dashboard/user-context";
import { ApiError, materialFieldCaseContext, materialFieldCasePreview, materialFieldCaseCommit, materialFieldCaseOutcome, materialTableFieldCaseCapabilities, materialTableFieldCaseMaterial, materialTableFieldCaseDetail, sourceTableExpressionCapabilities, sourceTableExpressionList, sourceTableExpressionDetail, sourceExpressionPreview, sourceExpressionCommit, sourceExpressionOutcome } from "@/lib/api";
import { onAuthChange } from "@/lib/auth-session";
import { parseExpressionJson, expressionCanonical, expressionSha, expressionSourceHref, type ExpressionCapabilities, type ExpressionReceipt, } from "@/lib/source-expressions";
import { fieldCaseTargetSummary } from "@/lib/material-field-cases";
import { TABLE_CASE_FIELDS, TABLE_CASE_REQUEST_VERSION, tableCaseText, tableCaseLabel, tableCaseReason, tableRoleLabel, knownTableCaseCapabilities, knownTableSourceCapabilities, knownTableCaseContext, compileTablePackage, tableExpressionRecovery, knownTableExpressionReceipt, knownTableExpressionPage, knownTableSourceRevision, tableCaseRecovery, knownTableCaseReceipt, knownTableCaseMaterial, knownTableCaseDetail, type TableCaseCapabilities, type TableCaseContext, type TablePrepared, type TableSourceRevision, type TableCaseDetail, type TableCaseMaterialPage, type TableCaseRequest, type TableCaseReceipt, type TableCaseRecovery, type TableExpressionPage, type TableSourceRecovery, readTableRecovery, storeTableRecovery, clearTableRecovery, tableStoredSourceIdentity, tableStoredCaseIdentity, knownTableStoredOutcome, type TableStoredIdentity, type TableSaveConfirmation } from "@/lib/material-table-fields";

const button = "rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink hover:border-accent-deep disabled:opacity-50";
const primary = "rounded-md bg-accent-deep px-3 py-2 text-sm font-medium text-white hover:bg-accent disabled:opacity-50";
const input = "mt-1 w-full min-w-0 rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink";
const section = "min-w-0 rounded-xl border border-sage-border bg-white p-4 sm:p-5";
type TableUpload = { package: TablePrepared["package"]; verified: TablePrepared };
type SourceDraft = { kind: "source"; request: { request_key: string; package: TableUpload["package"] }; ref: TableSourceRecovery; receipt: ExpressionReceipt; prepared: TableUpload };
type CaseDraft = { kind: "case"; request: TableCaseRequest; ref: TableCaseRecovery; receipt: TableCaseReceipt };
type Draft = SourceDraft | CaseDraft;
async function bounded<T>(call: () => Promise<T>, controller: AbortController) { let timer: ReturnType<typeof setTimeout> | undefined; try { return await Promise.race([call(), new Promise<never>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error("Private operation timed out")); }, 25000); })]); } finally { if (timer) clearTimeout(timer); } }
function Pin({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-xs text-sage-muted">{label}</dt><dd className="break-all text-xs text-sage-ink">{value ?? "Unestablished"}</dd></div>; }
function TableSource({ expression }: { expression: TableSourceRevision }) {
  const p = expression.projection, href = expressionSourceHref(expression.capture.source.url);
  return <div className="space-y-2"><p className="break-words text-sm font-medium">{tableCaseLabel(p.field_id)}: {p.value.raw_value} {p.value.raw_unit}</p><p className="text-xs text-sage-muted">{tableRoleLabel(p.field_role)} · Original row unit · Interpretation pending</p><details className="text-xs"><summary className="cursor-pointer text-sage-muted">Original source window and integrity</summary><p className="mt-2 whitespace-pre-wrap break-words">{p.window.raw_label}</p><dl className="mt-3 grid gap-2"><Pin label="Expression revision" value={expression.id} /><Pin label="Source ID" value={expression.capture.source.source_id} /><Pin label="Source fragment SHA256" value={expression.capture.source_content_sha256} /></dl>{href && <a className="mt-2 inline-block text-accent-deep underline" href={href} target="_blank" rel="noopener noreferrer">Open declared source</a>}<p className="mt-2 text-sage-muted">Publication revision, rights and currentness remain unverified. A captured window does not establish sample or phase identity.</p></details></div>;
}

export function MaterialTableFieldWorkbench({ initialMaterialId = "", initialField = "" }: { initialMaterialId?: string; initialField?: string }) {
  const { user } = useDashboardUser();
  const [access, setAccess] = useState<TableCaseCapabilities | null>(null), [sourceAccess, setSourceAccess] = useState<ExpressionCapabilities | null>(null);
  const [materialId, setMaterialId] = useState(initialMaterialId), [recordIndex, setRecordIndex] = useState("0"), [field, setField] = useState(TABLE_CASE_FIELDS.includes(initialField as typeof TABLE_CASE_FIELDS[number]) ? initialField : TABLE_CASE_FIELDS[0] as string);
  const [context, setContext] = useState<TableCaseContext | null>(null), [prepared, setPrepared] = useState<TableUpload | null>(null);
  const [sourceReceipt, setSourceReceipt] = useState<ExpressionReceipt | null>(null), [expression, setExpression] = useState<TableSourceRevision | null>(null), [caseDetail, setCaseDetail] = useState<TableCaseDetail | null>(null);
  const [cases, setCases] = useState<TableCaseMaterialPage | null>(null), [sources, setSources] = useState<TableExpressionPage | null>(null), [proposePaper, setProposePaper] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null), [recovery, setRecovery] = useState<TableStoredIdentity | null>(null), [receipt, setReceipt] = useState<ExpressionReceipt | TableCaseReceipt | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null);
  const [storageBlocked, setStorageBlocked] = useState(false), [confirmation, setConfirmation] = useState<TableSaveConfirmation | null>(null);
  const mounted = useRef(false), seq = useRef(0), controller = useRef<AbortController | null>(null), retained = useRef<TableStoredIdentity | null>(null);
  const cap = access?.actor_user_id === user.id ? access : null, sourceCap = sourceAccess?.actor_user_id === user.id ? sourceAccess : null, locked = busy || recovery !== null;
  const target = caseDetail?.target, targetField = target?.operation === "target" ? (target.payload as { field_id: string }).field_id : null;
  function clearDraft() { setDraft(null); setReceipt(null); setConfirmation(null); }
  function clearScope() { setContext(null); setPrepared(null); setSourceReceipt(null); setExpression(null); setCaseDetail(null); setCases(null); setSources(null); setProposePaper(false); clearDraft(); }
  function clearPrivate() { ++seq.current; controller.current?.abort(); setAccess(null); setSourceAccess(null); clearScope(); setRecovery(null); retained.current = null; setStorageBlocked(true); setBusy(false); }
  function begin() { const version = ++seq.current; controller.current?.abort(); const next = new AbortController(); controller.current = next; return { signal: next.signal, active: () => mounted.current && seq.current === version, run: <T,>(call: () => Promise<T>) => bounded(call, next) }; }
  function fail(error: unknown) { clearScope(); setBusy(false); if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared."); } else if (error instanceof ApiError && error.status === 404) setMessage("The private interface or original source is unavailable. No scientific absence was inferred."); else if (error instanceof ApiError && error.status === 409) setMessage("The retained record, source head or access changed. Reload the exact scope before continuing."); else setMessage("The original source proof could not be verified. Reload the exact scope before continuing."); }
  async function refreshAccess() {
    const op = begin(); setAccess(null); setSourceAccess(null); clearScope(); setBusy(true); setMessage(null); setRecovery(null); retained.current = null; setStorageBlocked(true);
    try { const [a, b] = await op.run(() => Promise.all([materialTableFieldCaseCapabilities(op.signal), sourceTableExpressionCapabilities(op.signal)])), c = knownTableCaseCapabilities(a, user.id), s = knownTableSourceCapabilities(b, user.id); if (!op.active()) return; if (!c || !s || c.session_version !== s.session_version || c.curator_grant_id !== s.curator_grant_id) throw new Error("Unsupported access"); setAccess(c); setSourceAccess(s); setBusy(false); const stored = readTableRecovery(user.id); if (stored.status === "pending") { retained.current = stored.identity; setRecovery(stored.identity); setStorageBlocked(false); setMessage("Check the original save with GET before starting another operation. No write will be retried."); } else if (stored.status === "blocked") { setStorageBlocked(true); setMessage("Recovery storage is unavailable or damaged. Pending writes are blocked; no empty ledger was inferred."); } else setStorageBlocked(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  useEffect(() => { mounted.current = true; clearPrivate(); void refreshAccess(); const unsubscribe = onAuthChange(() => { clearPrivate(); setMessage("Session changed. Private information has been cleared; refresh access."); }); return () => { unsubscribe(); mounted.current = false; ++seq.current; controller.current?.abort(); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user.id]);
  useEffect(() => { if (initialMaterialId !== materialId && !retained.current) { ++seq.current; controller.current?.abort(); clearScope(); setMaterialId(initialMaterialId); setBusy(false); } // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialMaterialId]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (retained.current) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, []);
  function editScope(edit: () => void) { if (locked) return; ++seq.current; controller.current?.abort(); clearScope(); edit(); setMessage(null); }
  async function loadScope() {
    if (!cap || locked || !tableCaseText(materialId, 100) || !/^\d+$/.test(recordIndex) || Number(recordIndex) > 4999) return; const id = materialId, index = Number(recordIndex), op = begin(); clearScope(); setBusy(true); setMessage(null);
    try { const c = await knownTableCaseContext(await op.run(() => materialFieldCaseContext(id, "retained_result", index, null, op.signal)), cap, id, "retained_result", index, null); if (!op.active()) return; if (!c) throw new Error("Unverified record"); setContext(c); if (!c.eligibility.eligible) { setBusy(false); setMessage(c.eligibility.reason_codes.map(tableCaseReason).join(" · ")); return; } setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function readPackage(file: File | undefined) {
    if (!file || locked) return;
    const op = begin(); setPrepared(null); setSourceReceipt(null); setExpression(null); clearDraft(); setBusy(true); setMessage(null);
    try {
      if (file.size > 393216) throw new Error("Package too large");
      const next = await compileTablePackage(parseExpressionJson(await file.text()));
      if (!op.active()) return;
      setPrepared({ package: next.package, verified: next }); setBusy(false);
    } catch (error) { if (op.active()) fail(error); }
  }
  async function previewSource() {
    if (!sourceCap?.can_import || !prepared || locked || storageBlocked) return; const p = prepared, request = { request_key: `table-source:${crypto.randomUUID()}`, package: p.package }, ref = tableExpressionRecovery(p.verified, sourceCap, request.request_key), op = begin(); clearDraft(); setBusy(true); setMessage(null);
    try { const next = await knownTableExpressionReceipt(await op.run(() => sourceExpressionPreview(request, op.signal)), sourceCap, ref, "preview", p.verified); if (!op.active()) return; if (!next) throw new Error("Unverified source preview"); const saved = { ...ref, previewSha: next.preview_sha256, manifestCanonical: expressionCanonical(next.expression_manifest), receiptId: next.receipt_id, receiptSha: next.receipt_sha256, captureId: next.capture_id }; if (next.replayed) { setSourceReceipt(next); setReceipt(next); } else setDraft({ kind: "source", request, ref: saved, receipt: next, prepared: p }); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function previewCase(request: TableCaseRequest, chain: string | null = null) {
    if (!cap?.can_write || locked || storageBlocked) return; const op = begin(); clearDraft(); setBusy(true); setMessage(null);
    try { const ref = tableCaseRecovery(request, cap, await expressionSha(expressionCanonical(request)), target, chain), next = await knownTableCaseReceipt(await op.run(() => materialFieldCasePreview(request, op.signal)), cap, ref, "preview"); if (!op.active()) return; if (!next) throw new Error("Unverified target preview"); if (next.replayed) setReceipt(next); else setDraft({ kind: "case", request, ref: { ...ref, previewSha: next.preview_sha256, receiptSha: next.receipt_sha256, receiptId: next.receipt_id }, receipt: next }); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  function previewTarget() { if (context?.eligibility.eligible) void previewCase({ version: TABLE_CASE_REQUEST_VERSION, request_key: `table-target:${crypto.randomUUID()}`, operation: "target", payload: { field_id: field, target: context.target } }); }
  async function previewAssociation() {
    if (!expression || !target || !target.eligibility.eligible || !expression.is_expression_head || !expression.capture.latest_retained_capture_for_source || targetField !== expression.projection.field_id || locked) return;
    if (prepared && target.context_sha256 !== context?.context_sha256) { setMessage("This target belongs to a different retained record. Load the target created from this exact prepared context."); return; }
    const version = seq.current, chain = await expressionSha(expressionCanonical([target.id, expression.expression_key])); if (!mounted.current || version !== seq.current) return;
    if (caseDetail?.associations.some(a => a.is_head && (a.payload as { expression_revision_id: string }).expression_revision_id === expression.id)) { setMessage("A current proposal already exists for this source expression. Inspect its history before adding another."); return; }
    await previewCase({ version: TABLE_CASE_REQUEST_VERSION, request_key: `table-association:${crypto.randomUUID()}`, operation: "association", payload: { target_id: target.id, target_sha256: target.record_sha256, expression_revision_id: expression.id, expression_record_sha256: expression.record_sha256, source_identity: { paper_id: proposePaper ? context?.closure.paper_id ?? null : null, work_id: null }, action: "propose", predecessor: null } }, chain);
  }
  async function acceptSaved(d: Draft, next: ExpressionReceipt | TableCaseReceipt) { setReceipt(next); setDraft(null); setBusy(false); retained.current = null; setRecovery(null); if (d.kind === "source") { setPrepared(d.prepared); setSourceReceipt(next as ExpressionReceipt); setExpression(null); } else if (d.request.operation === "target") setMessage("The pending target was saved. Load its current case before proposing a source association."); else setMessage("The pending association was saved. Reload the case to inspect its current scope and history."); }
  async function commit() {
    if (!cap?.can_write || !sourceCap || !draft || locked || retained.current || storageBlocked) return; const d = draft, op = begin(); setBusy(true); setMessage(null);
    let identity: TableStoredIdentity;
    try { identity = d.kind === "source" ? await tableStoredSourceIdentity(d.ref) : tableStoredCaseIdentity(d.ref); if (!op.active()) return; if (!storeTableRecovery(identity)) { clearScope(); setStorageBlocked(true); setBusy(false); setMessage("Recovery identity could not be stored and verified. No save was sent; pending writes are blocked."); return; } }
    catch { if (op.active()) { clearScope(); setStorageBlocked(true); setBusy(false); setMessage("Recovery identity could not be stored and verified. No save was sent; pending writes are blocked."); } return; }
    retained.current = identity; setRecovery(identity); setDraft(null);
    try { const next = d.kind === "source" ? await knownTableExpressionReceipt(await op.run(() => sourceExpressionCommit(d.request, d.ref.previewSha, op.signal)), sourceCap, d.ref, "commit", d.prepared.verified) : await knownTableCaseReceipt(await op.run(() => materialFieldCaseCommit(d.request, d.ref.previewSha, op.signal)), cap, d.ref, "commit"); if (!op.active()) return; if (!next) throw new Error("Unverified save"); if (!clearTableRecovery(identity)) { clearScope(); setConfirmation({ kind: identity.kind, receiptId: identity.receiptId, receiptSha: identity.receiptSha, requestKey: identity.requestKey }); setRecovery(identity); setStorageBlocked(true); setBusy(false); setMessage("The save receipt was verified, but its stored identity could not be cleared. Pending writes remain blocked."); return; } setStorageBlocked(false); await acceptSaved(d, next); }
    catch (error) { if (!op.active()) return; clearScope(); setBusy(false); if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared. The original save identity remains stored for GET recovery."); } else { setRecovery(identity); setMessage("The save outcome is unknown. Check its original GET outcome; no write will be retried."); } }
  }
  async function checkOutcome() {
    if (!cap || !sourceCap || !recovery || busy || recovery.actorId !== cap.actor_user_id) return; const identity = recovery, op = begin(); setBusy(true); setMessage(null);
    try { const response = identity.kind === "source" ? await op.run(() => sourceExpressionOutcome(identity.requestKey, identity.requestSha, op.signal)) : await op.run(() => materialFieldCaseOutcome(identity.requestKey, identity.requestSha, op.signal)), next = await knownTableStoredOutcome(response, cap.actor_user_id, identity); if (!op.active()) return; if (!next) throw new Error("Unverified outcome"); clearScope(); setConfirmation(next); setBusy(false); if (!clearTableRecovery(identity)) { setStorageBlocked(true); setRecovery(identity); setMessage("The original receipt was confirmed, but its stored identity could not be cleared. Pending writes remain blocked."); return; } retained.current = null; setRecovery(null); setStorageBlocked(false); setMessage("The original receipt is confirmed. Reload current sources or field cases before continuing; no write was retried."); }
    catch (error) { if (!op.active()) return; if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared. The original save identity remains stored for GET recovery."); } else { setBusy(false); setMessage("The original outcome remains unverified. No rollback or failed save was inferred; no write was retried."); } }
  }
  async function loadSources(offset = 0) {
    if (!cap || locked) return; const selected = field, sourceId = prepared?.package.source.source_id, op = begin(); clearDraft(); setSources(null); setExpression(null); setBusy(true); setMessage(null);
    try { const next = await knownTableExpressionPage(await op.run(() => sourceTableExpressionList(offset, 8, selected, sourceId, op.signal)), offset, 8, { field: selected, sourceId }); if (!op.active()) return; if (!next) throw new Error("Unverified source window"); setSources(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function inspectSource(item: TableSourceRevision) {
    if (!cap || locked) return; const op = begin(); clearDraft(); setExpression(null); setBusy(true); setMessage(null);
    try { const next = await knownTableSourceRevision(await op.run(() => sourceTableExpressionDetail(item.id, op.signal)), item.id, item.record_sha256); if (!op.active()) return; if (!next || !next.is_expression_head || !next.capture.latest_retained_capture_for_source || prepared && (next.import_receipt_id !== sourceReceipt?.receipt_id || !prepared.verified.projections.some(p => p.expression_key === next.projection.expression_key) || next.capture.source_content_sha256 !== prepared.package.source_content_sha256)) throw new Error("Changed source head"); setExpression(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function loadCases(offset = 0) {
    if (!cap || locked || !materialId.trim()) return; const id = materialId, op = begin(); clearDraft(); setCases(null); setCaseDetail(null); setBusy(true); setMessage(null);
    try { const next = await knownTableCaseMaterial(await op.run(() => materialTableFieldCaseMaterial(id, offset, op.signal)), cap, id, offset); if (!op.active()) return; if (!next) throw new Error("Unverified case window"); setCases(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function inspectCase(id: string, original?: TableCaseDetail["target"]) {
    if (!cap || locked) return; const expected = receipt && "operation" in receipt && receipt.operation === "target" && receipt.target_id === id ? receipt : null, op = begin(); clearDraft(); setCaseDetail(null); setProposePaper(false); setBusy(true); setMessage(null);
    try { const next = await knownTableCaseDetail(await op.run(() => materialTableFieldCaseDetail(id, op.signal)), cap, original); if (!op.active()) return; if (!next || expected && (next.target.record_sha256 !== expected.receipt_sha256 || next.target.record_canonical_json !== expected.receipt_canonical_json) || (next.target.payload as { target: { material_id: string } }).target.material_id !== materialId) throw new Error("Unverified target"); setCaseDetail(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  const canWrite = Boolean(cap?.can_write && sourceCap?.can_import && !locked && !storageBlocked);
  return <div className="min-w-0 space-y-5">
    <header className="space-y-2"><h2 className="text-2xl font-semibold text-sage-ink">Table source review</h2><p className="max-w-3xl text-sm text-sage-muted">Inspect table cells, retain their source, and propose links to exact material records.</p><details className="text-xs text-sage-muted"><summary className="cursor-pointer">Scope of this private workflow</summary><p className="mt-2 max-w-3xl">Values retain printed units and uncertainty without conversion. Field interpretation, sample and phase identity remain pending. Source imports, targets and associations are separate private ledger operations. They do not approve public scientific values or ML use. Table layout is declared from retained text; inspect the original publication before reviewing the composition and sample state.</p></details></header>
    <div className="flex flex-wrap items-center gap-3"><button className={button} disabled={busy} onClick={() => void refreshAccess()}>Refresh access</button>{cap && <span className="text-xs text-sage-muted">{cap.can_write && sourceCap?.can_import ? "Curator access" : "Read access"}</span>}{busy && <span role="status" className="text-sm text-sage-muted">Loading exact scope…</span>}</div>
    {message && <p role="status" className="break-words rounded-md border border-sage-border bg-sage-surface p-3 text-sm">{message}</p>}
    {cap && (recovery ? <section className={section} aria-label="Original save recovery"><h3 className="font-medium">Original save recovery</h3><p className="mt-2 text-sm text-sage-muted">The original {recovery.kind === "source" ? "source import" : recovery.operation} request is retained for this actor in this browser tab. Check its outcome with GET before another save.</p><button className={`${button} mt-3`} disabled={busy} onClick={() => void checkOutcome()}>Check original request</button><details className="mt-3 text-xs"><summary className="cursor-pointer">Original request pins</summary><dl className="mt-2 grid gap-2"><Pin label="Request key" value={recovery.requestKey} /><Pin label="Request SHA256" value={recovery.requestSha} /><Pin label="Preview SHA256" value={recovery.previewSha} /></dl></details></section> : <>
      <section className={section} aria-label="Exact retained record"><h3 className="font-medium">Exact retained record</h3><div className="mt-3 grid items-end gap-3 sm:grid-cols-[minmax(0,1fr)_9rem_auto]"><label className="text-xs text-sage-muted">Material ID<input className={input} value={materialId} maxLength={100} disabled={locked} onChange={e => editScope(() => setMaterialId(e.target.value))} /></label><label className="text-xs text-sage-muted">Retained record index<input className={input} inputMode="numeric" value={recordIndex} maxLength={4} disabled={locked} onChange={e => editScope(() => setRecordIndex(e.target.value))} /></label><button className={primary} disabled={locked || !tableCaseText(materialId, 100) || !/^\d+$/.test(recordIndex) || Number(recordIndex) > 4999} onClick={() => void loadScope()}>Load exact record</button></div>
        {context && <div className="mt-4 space-y-3 border-t border-sage-border pt-3"><dl className="grid gap-2 sm:grid-cols-2">{fieldCaseTargetSummary(context.context_canonical_json).map(p => <div key={p.label}><dt className="text-xs text-sage-muted">{p.label}</dt><dd className="break-words text-sm">{p.value}</dd></div>)}<Pin label="Exact result ID" value={context.closure.legacy_result_id} /><Pin label="Retained paper ID" value={context.closure.paper_id} /></dl><details className="text-xs text-sage-muted"><summary className="cursor-pointer">Exact retained record proof</summary><Pin label="Record SHA256" value={context.closure.retained_record_sha256} /><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all">{context.context_canonical_json}</pre></details></div>}
      </section>
      <section className={section} aria-label="Original table package"><h3 className="font-medium">Original table package</h3><p className="mt-2 text-sm text-sage-muted">Choose a source-expression-package/2.2.0 JSON file. Column headings, row units and cell text are checked together. No source is saved until you preview and save.</p><label className="mt-3 block text-sm">Table package file<input type="file" accept=".json,application/json" className={`${input} file:mr-3 file:rounded file:border-0 file:bg-sage-surface file:px-3 file:py-2`} disabled={locked} onChange={e => { const file = e.currentTarget.files?.[0]; e.currentTarget.value = ""; void readPackage(file); }} /></label>
      {prepared && <div className="mt-4 space-y-3"><h4 className="font-medium">{prepared.verified.projections.length} checked source cells</h4><ul className="divide-y divide-sage-border">{prepared.verified.projections.map(p => <li key={p.expression_key} className="py-3"><p className="break-words text-sm font-medium">{p.subject.formula} · {tableCaseLabel(p.field_id)}</p><p className="mt-1 text-sm">{p.value.raw_value} {p.value.raw_unit}</p><p className="mt-1 text-xs text-sage-muted">Table {p.locator.table} · Data row {p.locator.row}, column {p.locator.column}</p></li>)}</ul><details className="text-xs"><summary className="cursor-pointer text-sage-muted">Original table text and integrity</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-words bg-sage-surface p-3">{prepared.verified.sourceText}</pre><Pin label="Original source SHA256" value={prepared.package.source_content_sha256} /><p className="mt-2">Cell spans match retained text. Declared layout, publication revision, composition and sample identity still require review.</p></details><div className="flex flex-wrap gap-2"><button className={primary} disabled={!canWrite || Boolean(sourceReceipt)} onClick={() => void previewSource()}>Preview source import</button>{sourceReceipt && <button className={button} disabled={locked} onClick={() => void loadSources()}>Load saved source expressions</button>}</div></div>}
      </section>
      <section className={section} aria-label="Table field target"><h3 className="font-medium">Field target</h3><label className="mt-3 block text-xs text-sage-muted">Scientific field<select className={input} value={field} disabled={locked} onChange={e => { ++seq.current; controller.current?.abort(); setField(e.target.value); setExpression(null); setCaseDetail(null); setSources(null); clearDraft(); }} aria-describedby="table-field-description">{TABLE_CASE_FIELDS.map(f => <option key={f} value={f}>{f === "debye_temperature_source_value" ? "Debye temperature (ΘD)" : "Heat capacity (γ)"}</option>)}</select></label><p id="table-field-description" className="mt-2 text-xs text-sage-muted">{tableCaseLabel(field)}</p><button className={`${button} mt-3`} disabled={!canWrite || !context?.eligibility.eligible} onClick={previewTarget}>Preview field target</button></section>
      <section className={section} aria-label="Current table sources"><h3 className="font-medium">Current table sources</h3><button className={`${button} mt-3`} disabled={locked} onClick={() => void loadSources()}>Load current expressions</button>{sources && <><p className="mt-3 text-xs text-sage-muted">{sources.expressions.length} of {sources.total} current heads in this returned window.</p><ul className="mt-2 divide-y divide-sage-border">{sources.expressions.map(s => <li className="flex flex-wrap items-start justify-between gap-3 py-3" key={s.id}><div className="min-w-0 flex-1"><p className="break-words text-sm">{s.projection.subject.formula} · {s.projection.value.raw_value} {s.projection.value.raw_unit}</p><p className="text-xs text-sage-muted">{tableRoleLabel(s.projection.field_role)}</p></div><button className={button} disabled={locked || Boolean(prepared && s.import_receipt_id !== sourceReceipt?.receipt_id)} onClick={() => void inspectSource(s)}>Inspect source expression</button></li>)}</ul>{sources.offset + sources.expressions.length < sources.total && <button className={button} disabled={locked} onClick={() => void loadSources(sources.offset + sources.expressions.length)}>Next source window</button>}</>}{expression && <div className="mt-4 border-t border-sage-border pt-3"><TableSource expression={expression} /></div>}</section>
      <section className={section} aria-label="Current table field cases"><h3 className="font-medium">Current table field cases</h3><div className="mt-3 flex flex-wrap gap-2"><button className={button} disabled={locked || !materialId.trim()} onClick={() => void loadCases()}>Load material cases</button>{receipt && "operation" in receipt && receipt.operation === "target" && <button className={button} disabled={locked} onClick={() => void inspectCase(receipt.target_id)}>Load saved field target</button>}</div>{cases && <><p className="mt-3 text-xs text-sage-muted">{cases.entries_returned} of {cases.total} cases; {cases.entries_omitted} omitted from the requested window.</p><ul className="mt-2 divide-y divide-sage-border">{cases.entries.map(d => <li className="flex flex-wrap items-start justify-between gap-3 py-3" key={d.target.id}><div className="min-w-0"><p className="text-sm">{tableCaseLabel((d.target.payload as { field_id: string }).field_id)}</p><p className="text-xs text-sage-muted">{d.target.eligibility.eligible ? "Current target scope" : d.target.eligibility.reason_codes.map(tableCaseReason).join(" · ")}</p></div><button className={button} disabled={locked} onClick={() => void inspectCase(d.target.id, d.target)}>Inspect field case</button></li>)}</ul>{cases.next_offset !== null && <button className={button} disabled={locked} onClick={() => void loadCases(cases.next_offset!)}>Next case window</button>}</>}
        {caseDetail && target && <div className="mt-4 space-y-3 border-t border-sage-border pt-3"><h4 className="font-medium">{tableCaseLabel(targetField!)}</h4>{!target.eligibility.eligible && <p className="text-sm text-amber-800">{target.eligibility.reason_codes.map(tableCaseReason).join(" · ")}</p>}<details className="text-xs"><summary className="cursor-pointer text-sage-muted">Target pins</summary><dl className="mt-2 grid gap-2"><Pin label="Target ID" value={target.id} /><Pin label="Target record SHA256" value={target.record_sha256} /></dl></details>{expression && canWrite && <><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={proposePaper} onChange={e => { ++seq.current; setProposePaper(e.target.checked); clearDraft(); }} disabled={locked || !context?.closure.paper_id} />Propose the retained paper ID as a source link</label><p className="text-xs text-sage-muted">The paper link is proposed. Work, sample, phase and selected-result identity remain unestablished.</p><button className={primary} disabled={!target.eligibility.eligible || targetField !== expression.projection.field_id} onClick={() => void previewAssociation()}>Preview matching source proposal</button></>}
          <details className="text-xs"><summary className="cursor-pointer text-sage-muted">Source proposal history ({caseDetail.association_returned} of {caseDetail.association_total})</summary><ul className="mt-2 space-y-3">{caseDetail.associations.map(a => <li key={a.id}><p>{a.eligibility.eligible ? "Pending source proposal" : a.eligibility.reason_codes.map(tableCaseReason).join(" · ")}</p>{a.expression && <TableSource expression={a.expression} />}<Pin label="Association ID" value={a.id} /></li>)}</ul><p className="mt-2">{caseDetail.association_omitted} historical proposals outside this returned window.</p></details>
        </div>}
      </section>
    </>)}
    {cap && draft && <section className={`${section} border-accent-deep`} aria-label="Exact pending preview"><h3 className="font-medium">Exact pending preview</h3><p className="mt-2 text-sm">{draft.kind === "source" ? "Retain these original table cells" : draft.request.operation === "target" ? "Create this exact field target" : "Propose this matching source expression"}</p><p className="mt-2 text-xs text-sage-muted">Preview has not retained a write. Saving appends private pending history.</p><details className="mt-3 text-xs"><summary className="cursor-pointer text-sage-muted">Exact request and preview pins</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all">{draft.receipt.request_canonical_json}</pre><Pin label="Preview SHA256" value={draft.ref.previewSha} /></details><button className={`${primary} mt-3`} disabled={locked || !cap?.can_write || storageBlocked} onClick={() => void commit()}>Save pending operation</button></section>}
    {cap && confirmation && <section className={section} aria-label="Original receipt confirmed"><h3 className="font-medium">Original receipt confirmed</h3><p className="mt-2 text-sm">The original {confirmation.kind === "source" ? "source import" : "field-case operation"} is recorded. Reload current sources or field cases to inspect their present scope.</p><details className="mt-3 text-xs"><summary className="cursor-pointer text-sage-muted">Confirmed receipt pins</summary><dl className="mt-2 grid gap-2"><Pin label="Receipt ID" value={confirmation.receiptId} /><Pin label="Receipt SHA256" value={confirmation.receiptSha} /></dl></details></section>}
    {cap && receipt && <section className={section} aria-label="Saved pending operation"><h3 className="font-medium">Saved pending operation</h3><p className="mt-2 text-sm">{receipt.replayed ? "Original receipt recovered" : "Private ledger write recorded"}. Interpretation and scientific acceptance remain pending.</p><details className="mt-3 text-xs"><summary className="cursor-pointer text-sage-muted">Receipt pins</summary><dl className="mt-2 grid gap-2"><Pin label="Receipt ID" value={receipt.receipt_id} /><Pin label="Receipt SHA256" value={receipt.receipt_sha256} /></dl></details></section>}
  </div>;
}
