"use client";

import { useEffect, useRef, useState } from "react";
import Link from "@/components/AppLink";
import { useDashboardUser } from "@/components/dashboard/user-context";
import { ApiError, materialFieldReviewCapabilities, materialFieldReviewCommit, materialFieldReviewContext, materialFieldReviewEffective, materialFieldReviewOutcome, materialFieldReviewPreview } from "@/lib/api";
import { onAuthChange } from "@/lib/auth-session";
import { FIELD_REVIEW_CHECKS, FIELD_REVIEW_FIELDS, FIELD_REVIEW_PROFILE, FIELD_REVIEW_VERSION, fieldReviewCheckLabel, fieldReviewLabel, fieldReviewUuid, knownReviewCapabilities, knownReviewContext, knownReviewEffective, knownReviewReceipt, knownReviewRequest, loadReviewRecovery, retainReviewRecovery, clearReviewRecovery, reviewContextMatchesEffective, reviewRecovery, reviewSourceValue, type ReviewCapabilities, type ReviewContext, type ReviewEffective, type ReviewField, type ReviewItem, type ReviewReceipt, type ReviewRecovery, type ReviewRequest, type ReviewSelector } from "@/lib/material-field-review";

const panel = "min-w-0 rounded-xl border border-sage-border bg-white p-4 sm:p-5";
const input = "mt-1 w-full min-w-0 rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink";
const button = "rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink hover:border-accent-deep disabled:opacity-50";
const primary = "rounded-md bg-accent-deep px-3 py-2 text-sm font-medium text-white hover:bg-accent disabled:opacity-50";
type Draft = { request: ReviewRequest; receipt: ReviewReceipt; ref: ReviewRecovery };
function object(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function scalar(value: unknown): string { return typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : "Not retained"; }
function Pins({ children }: { children: React.ReactNode }) { return <details className="mt-3 text-xs text-sage-muted"><summary className="cursor-pointer">Source, record and review pins</summary><div className="mt-2 space-y-2 break-all">{children}</div></details>; }

export function MaterialFieldReviewWorkbench({ initialTargetId = "", initialExpressionId = "", initialAssociationId = "", initialField = "tc_criterion", initialKind = "condition", initialIndex = "0" }: { initialTargetId?: string; initialExpressionId?: string; initialAssociationId?: string; initialField?: ReviewField; initialKind?: "condition" | "value"; initialIndex?: string }) {
  const { user } = useDashboardUser();
  const [cap, setCap] = useState<ReviewCapabilities | null>(null), [targetId, setTargetId] = useState(initialTargetId), [expressionId, setExpressionId] = useState(initialExpressionId), [associationId, setAssociationId] = useState(initialAssociationId), [tcExpressionId, setTcExpressionId] = useState("");
  const [field, setField] = useState<ReviewField>(initialField), [kind, setKind] = useState<"condition" | "value">(initialKind), [index, setIndex] = useState(initialIndex);
  const [context, setContext] = useState<ReviewContext | null>(null), [effective, setEffective] = useState<ReviewEffective | null>(null), [item, setItem] = useState<ReviewItem | null>(null);
  const [draft, setDraft] = useState<Draft | null>(null), [receipt, setReceipt] = useState<ReviewReceipt | null>(null), [recovery, setRecovery] = useState<ReviewRecovery | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null);
  const mounted = useRef(false), seq = useRef(0), controller = useRef<AbortController | null>(null), retained = useRef<ReviewRecovery | null>(null);
  const access = cap?.actor_user_id === user.id ? cap : null, locked = busy || recovery !== null;
  function clearValues() { setContext(null); setEffective(null); setItem(null); setDraft(null); setReceipt(null); }
  function clearPrivate() { ++seq.current; controller.current?.abort(); setCap(null); clearValues(); setRecovery(null); setBusy(false); }
  function begin() { const version = ++seq.current; controller.current?.abort(); const next = new AbortController(); controller.current = next; return { signal: next.signal, active: () => mounted.current && seq.current === version, run: async <T,>(call: () => Promise<T>) => { let timer: ReturnType<typeof setTimeout> | undefined; try { return await Promise.race([call(), new Promise<never>((_, reject) => { timer = setTimeout(() => { next.abort(); reject(new Error("Private operation timed out")); }, 25000); })]); } finally { if (timer) clearTimeout(timer); } } }; }
  function fail(error: unknown) { clearValues(); setBusy(false); if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared."); } else if (error instanceof ApiError && error.status === 404) setMessage("This review interface or exact record is unavailable. No missing value was inferred."); else if (error instanceof ApiError && error.status === 409) setMessage("The original record, source or review head changed. Reload its current context."); else setMessage("The response could not be verified. Reload current context before continuing."); }
  async function refreshAccess() { const op = begin(); setCap(null); clearValues(); setBusy(true); setMessage(null); try { const next = knownReviewCapabilities(await op.run(() => materialFieldReviewCapabilities(op.signal)), user.id); if (!op.active()) return; if (!next) throw new Error("Unsupported review capabilities"); setCap(next); setBusy(false); retained.current = loadReviewRecovery(user.id); if (retained.current) { setRecovery(retained.current); setMessage("The original save requires an outcome check. No write will be retried."); } else { retained.current = null; setRecovery(null); } } catch (error) { if (op.active()) fail(error); } }
  useEffect(() => { mounted.current = true; clearPrivate(); void refreshAccess(); const unsubscribe = onAuthChange(() => { clearPrivate(); setMessage("Session changed. Private information has been cleared; refresh access."); }); return () => { unsubscribe(); mounted.current = false; ++seq.current; controller.current?.abort(); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user.id]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (retained.current) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, []);
  function edit(setter: () => void) { if (locked) return; ++seq.current; controller.current?.abort(); clearValues(); setter(); setMessage(null); }
  async function loadContext() {
    if (!access || locked) return;
    if (!fieldReviewUuid(targetId) || !fieldReviewUuid(expressionId) || associationId && !fieldReviewUuid(associationId) || kind === "value" && !fieldReviewUuid(tcExpressionId) || kind === "condition" && !/^[0-7]$/.test(index) || kind === "value" && field !== "measurement_method") { setMessage("Choose exact target and expression IDs, and the matching source component."); return; }
    const selector: ReviewSelector = { targetId, expressionId, fieldId: field, componentKind: kind, componentIndex: Number(index), ...(associationId ? { associationId } : {}), ...(kind === "value" && tcExpressionId ? { tcExpressionId } : {}) }, current = access, op = begin(); clearValues(); setBusy(true); setMessage(null);
    try { const raw = await op.run(() => materialFieldReviewContext(selector, op.signal)), next = await knownReviewContext(raw, current, selector); if (!op.active()) return; if (!next) throw new Error("Unverified review context"); const value = await knownReviewEffective(await op.run(() => materialFieldReviewEffective(targetId, field, op.signal)), current, targetId, field); if (!op.active()) return; if (!value || !reviewContextMatchesEffective(next, value)) throw new Error("Changed field review head"); setContext(next); setEffective(value); setItem({ ...next.item_template, rationale: "" }); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  function changeItem(patch: Partial<ReviewItem>) { if (!item || locked) return; setItem({ ...item, ...patch }); setDraft(null); setReceipt(null); }
  async function preview() {
    if (!access?.can_write || !item || locked) return;
    const request: ReviewRequest = { version: FIELD_REVIEW_VERSION, profile_version: FIELD_REVIEW_PROFILE, request_key: `field-review:${crypto.randomUUID()}`, items: [item] };
    if (!knownReviewRequest(request)) { setMessage("Supply a review rationale of 20–1,000 characters. Acceptance requires all four checks and explicit source inspection."); return; }
    const current = access, op = begin(); setDraft(null); setReceipt(null); setBusy(true); setMessage(null);
    try { const ref = await reviewRecovery(request, current), next = await knownReviewReceipt(await op.run(() => materialFieldReviewPreview(request, op.signal)), current, ref, "preview"); if (!op.active()) return; if (!next) throw new Error("Unverified review preview"); if (next.replayed) setReceipt(next); else setDraft({ request, receipt: next, ref: { ...ref, previewSha: next.preview_sha256, receiptId: next.receipt_id, receiptSha: next.receipt_sha256 } }); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function commit() {
    if (!access?.can_write || !draft || locked) return;
    const current = access, selected = draft; try { retainReviewRecovery(selected.ref); } catch { setMessage("The original save identity could not be retained in this browser. No write was attempted."); return; } const op = begin(); retained.current = selected.ref; setRecovery(selected.ref); setBusy(true); setMessage(null);
    try { const next = await knownReviewReceipt(await op.run(() => materialFieldReviewCommit(selected.request, selected.receipt.preview_sha256, op.signal)), current, selected.ref, "commit"); if (!op.active()) return; if (!next) throw new Error("Unverified review save"); clearReviewRecovery(current.actor_user_id); retained.current = null; setRecovery(null); clearValues(); setReceipt(next); setBusy(false); setMessage("The field decision was saved. Reload current context to inspect its effective value."); }
    catch (error) { if (op.active()) { if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private values have been cleared; the original save identity remains for its actor."); return; } clearValues(); setBusy(false); setMessage("The save outcome is unknown. Check the original operation below; no write will be retried."); } }
  }
  async function checkOutcome() {
    if (!access || !recovery || busy) return; const current = access, ref = recovery, op = begin(); clearValues(); setBusy(true); setMessage(null);
    try { const next = await knownReviewReceipt(await op.run(() => materialFieldReviewOutcome(ref.requestKey, ref.requestSha, op.signal)), current, ref, "outcome"); if (!op.active()) return; if (!next) throw new Error("Unverified original outcome"); clearReviewRecovery(current.actor_user_id); retained.current = null; setRecovery(null); setReceipt(next); setBusy(false); setMessage("The original operation is confirmed. Reload current context to inspect its effective value."); }
    catch (error) { if (op.active()) { if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private values have been cleared; the original save identity remains for its actor."); return; } setBusy(false); setMessage("The original outcome remains unresolved. Keep its identity for another read; no write will be retried."); } }
  }
  const summary = context && object(context.subject.retained_result_summary) ? context.subject.retained_result_summary : null;
  const tuple = context && object(context.subject.tuple) ? context.subject.tuple : null, subject = tuple && object(tuple.subject) ? tuple.subject : null, sourceWindow = tuple && object(tuple.window) ? tuple.window : null;
  const independent = context ? ![context.subject.target_user_id, context.subject.association_user_id, context.subject.importer_user_id, context.subject.capture_user_id, context.subject.tc_importer_user_id].includes(user.id) : false;
  return <div className="mx-auto max-w-5xl space-y-5">
    <header className="space-y-2"><p className="text-xs font-medium uppercase tracking-wide text-accent-deep">Private research workspace</p><h2 className="text-2xl font-semibold text-sage-ink">Review a missing Tc field</h2><p className="text-sm text-sage-muted">Compare the retained result with its exact source component, then append a field decision.</p><details className="text-xs text-sage-muted"><summary className="cursor-pointer">Scope of field review</summary><p className="mt-2">Field fidelity covers the printed source value and its relationship to this retained Tc result. The original observation stays intact. Scientific acceptance, public release and ML approval require separate review.</p></details></header>
    <div className="flex flex-wrap items-center gap-3"><button className={button} disabled={busy} onClick={() => void refreshAccess()}>Refresh review access</button>{access && <p className="text-xs text-sage-muted">{access.can_write ? "Reviewer access available" : "Read-only research access"}</p>}</div>
    {message && <p role="status" className="break-words rounded-md border border-sage-border bg-sage-surface p-3 text-sm">{message}</p>}
    {access && <>
      <section className={panel} aria-label="Exact review selection"><div className="grid items-end gap-3 sm:grid-cols-2">
        <label className="text-xs text-sage-muted">Field<select className={input} value={field} disabled={locked} onChange={e => edit(() => { setField(e.target.value as ReviewField); setKind("condition"); })}>{FIELD_REVIEW_FIELDS.map(f => <option key={f} value={f}>{fieldReviewLabel(f)}</option>)}</select></label>
        <label className="text-xs text-sage-muted">Retained-result target ID<input className={input} value={targetId} disabled={locked} onChange={e => edit(() => setTargetId(e.target.value))} /></label>
        <label className="text-xs text-sage-muted">Source-expression revision ID<input className={input} value={expressionId} disabled={locked} onChange={e => edit(() => setExpressionId(e.target.value))} /></label>
        <label className="text-xs text-sage-muted">Proposed association ID (optional)<input className={input} value={associationId} disabled={locked} onChange={e => edit(() => setAssociationId(e.target.value))} /></label>
        <label className="text-xs text-sage-muted">Source component<select className={input} value={kind} disabled={locked} onChange={e => edit(() => setKind(e.target.value as "condition" | "value"))}><option value="condition">Reported result condition</option>{field === "measurement_method" && <option value="value">Standalone method statement</option>}</select></label>
        {kind === "condition" && <label className="text-xs text-sage-muted">Condition index (0–7)<input className={input} inputMode="numeric" value={index} disabled={locked} onChange={e => edit(() => setIndex(e.target.value))} /></label>}
      </div>{kind === "value" && <label className="mt-3 block text-xs text-sage-muted">Companion Tc-expression revision ID<input className={input} value={tcExpressionId} disabled={locked} onChange={e => edit(() => setTcExpressionId(e.target.value))} /></label>}<div className="mt-4 flex flex-wrap items-center gap-3"><button className={primary} disabled={locked} onClick={() => void loadContext()}>Load current review context</button><Link className="text-sm text-accent-deep underline" href="/dashboard/research/material-field-cases">Find retained field targets</Link><Link className="text-sm text-accent-deep underline" href="/dashboard/research/source-expressions">Inspect source expressions</Link></div></section>
      {context && item && <section className={panel} aria-label="Original result and proposed field"><div className="grid gap-4 sm:grid-cols-2"><div><h3 className="font-medium">Original retained Tc result</h3><dl className="mt-2 space-y-2 text-sm"><div><dt className="text-xs text-sage-muted">Tc</dt><dd>{summary ? `${scalar(summary.tc_kelvin)} K` : "Inspect exact target context"}</dd></div><div><dt className="text-xs text-sage-muted">Publication</dt><dd className="break-words">{item.source_identity.paper_id}</dd></div>{summary && <div><dt className="text-xs text-sage-muted">Retained year and origin</dt><dd>{scalar(summary.year)} · {scalar(summary.knowledge_origin)}</dd></div>}</dl></div><div><h3 className="font-medium">Proposed {fieldReviewLabel(item.field_id)}</h3><p className="mt-2 break-words text-lg text-sage-ink">{reviewSourceValue(context.subject.candidate)}</p><p className="mt-1 break-words text-xs text-sage-muted">Source subject: {subject ? scalar(subject.formula) : "Unestablished"} · Sample: {subject ? scalar(subject.sample_label) : "Unestablished"}</p><p className="mt-1 break-words text-xs text-sage-muted">Source window: {sourceWindow ? scalar(sourceWindow.raw_label ?? sourceWindow.id) : "Unestablished"}</p></div></div>
        {!context.subject.eligible && <p className="mt-3 text-sm text-amber-800">Current source or target requires clarification: {context.subject.reason_codes.map(x => x.replaceAll("_", " ")).join(" · ")}</p>}{!independent && <p className="mt-3 text-sm text-amber-800">Acceptance requires a reviewer independent of the target, source capture, import and association authors.</p>}
        <Pins><p>Target: {item.target_id}</p><p>Original context SHA256: {scalar(context.subject.context_sha256)}</p><p>Source revision: {item.expression.id}</p><p>Subject SHA256: {context.subject_sha256}</p><p>Current preceding decision: {item.predecessor?.id ?? "No preceding decision"}</p><pre className="max-h-56 overflow-auto whitespace-pre-wrap break-all">{context.subject_canonical_json}</pre></Pins>
      </section>}
      {effective && <section className={panel} aria-label="Current field decision"><h3 className="font-medium">Current reviewed field</h3>{effective.field_fidelity_accepted ? <><p className="mt-2 break-words text-lg text-sage-ink">{reviewSourceValue(effective.effective_value)}</p><p className="mt-1 text-xs text-accent-deep">Source fidelity accepted for this field</p></> : <p className="mt-2 text-sm text-sage-muted">{effective.decision ? `${effective.decision.decision.replaceAll("_", " ")} · ${effective.decision.reason_codes.map(x => x.replaceAll("_", " ")).join(" · ") || "No effective accepted value"}` : "No field decision retained for this target."}</p>}</section>}
      {context && item && access.can_write && <section className={panel} aria-label="Reviewer field decision"><h3 className="font-medium">Review decision</h3><div className="mt-3 grid gap-3">{FIELD_REVIEW_CHECKS.map(check => <label className="text-sm" key={check}>{fieldReviewCheckLabel(check)}<select className={input} value={item.checks[check]} disabled={locked} onChange={e => changeItem({ checks: { ...item.checks, [check]: e.target.value as ReviewItem["checks"][typeof check] } })}><option value="unresolved">Unresolved</option><option value="satisfied">Satisfied after inspection</option><option value="not_applicable">Not applicable</option></select></label>)}<label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={item.source_inspection_attested} disabled={locked} onChange={e => changeItem({ source_inspection_attested: e.target.checked })} />I inspected the original source and its exact result window.</label><label className="text-sm">Decision<select className={input} value={item.decision} disabled={locked} onChange={e => changeItem({ decision: e.target.value as ReviewItem["decision"] })}><option value="request_clarification">Request clarification</option><option value="reject">Reject this field association</option><option value="accept" disabled={!context.subject.eligible || !independent}>Accept source fidelity for this field</option></select></label><label className="text-sm">Review rationale<textarea className={input} rows={3} maxLength={1000} value={item.rationale} disabled={locked} onChange={e => changeItem({ rationale: e.target.value })} /></label></div><button className={`${button} mt-4`} disabled={locked} onClick={() => void preview()}>Preview field decision</button></section>}
      {draft && <section className={`${panel} border-accent-deep`} aria-label="Exact field decision preview"><h3 className="font-medium">Ready to append this field decision</h3><p className="mt-2 text-sm">{fieldReviewLabel(draft.request.items[0].field_id)} · {draft.request.items[0].decision.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-sage-muted">Preview rolled back its write rehearsal. Saving appends this exact decision to private review history.</p><details className="mt-3 text-xs"><summary className="cursor-pointer">Exact decision and source pins</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all">{draft.receipt.request_canonical_json}</pre></details><button className={`${primary} mt-4`} disabled={locked || !access.can_write} onClick={() => void commit()}>Save this field decision</button></section>}
      {recovery && <section className={panel} aria-label="Original review outcome recovery"><h3 className="font-medium">Check the original save</h3><p className="mt-2 text-sm">Its outcome must be resolved before another decision.</p><p className="mt-2 break-all text-xs text-sage-muted">Request: {recovery.requestKey}<br />SHA256: {recovery.requestSha}</p><button className={`${button} mt-3`} disabled={busy} onClick={() => void checkOutcome()}>Check original save outcome</button></section>}
      {receipt && <section className={panel} aria-label="Verified field review receipt"><h3 className="font-medium">Field decision retained</h3><p className="mt-2 text-sm">Reload current context to check whether the field remains effective after source or access changes.</p><Pins><p>Receipt: {receipt.receipt_id}</p><p>Receipt SHA256: {receipt.receipt_sha256}</p><p>Request: {receipt.request_key}</p></Pins></section>}
    </>}
  </div>;
}
