"use client";

import { useEffect, useRef, useState } from "react";
import Link from "@/components/AppLink";
import { useDashboardUser } from "@/components/dashboard/user-context";
import { ApiError, materialFieldCaseCapabilities, materialFieldCaseCommit, materialFieldCaseContext, materialFieldCaseDetail, materialFieldCaseMaterial, materialFieldCaseOutcome, materialFieldCasePreview, sourceExpressionDetail, sourceExpressionList } from "@/lib/api";
import { onAuthChange } from "@/lib/auth-session";
import { FIELD_REVIEW_FIELDS } from "@/lib/material-field-review";
import { expressionCanonical, expressionSha, expressionSourceHref, knownExpressionPage, knownSourceRevision, sourceValueLabel, type ExpressionPage, type SourceRevision } from "@/lib/source-expressions";
import { compatibleFieldExpression, fieldCaseEntryActor, fieldCaseEntryChain, fieldCaseLabel, fieldCaseReason, fieldCaseRecovery, fieldCaseText, fieldCaseTargetSummary, knownFieldCaseCapabilities, knownFieldCaseContext, knownFieldCaseDetail, knownFieldCaseMaterial, knownFieldCaseReceipt, knownFieldCaseRequest, FIELD_CASE_OUTCOMES, FIELD_CASE_REASONS, FIELD_CASE_REQUEST_VERSION, type FieldCaseAssociationPayload, type FieldCaseAttemptPayload, type FieldCaseCapabilities, type FieldCaseContext, type FieldCaseDetail, type FieldCaseEntry, type FieldCaseMaterialPage, type FieldCaseReceipt, type FieldCaseRecovery, type FieldCaseRequest, type FieldCaseTargetPayload, type TargetKind } from "@/lib/material-field-cases";

const button = "rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink hover:border-accent-deep disabled:opacity-50";
const primary = "rounded-md bg-accent-deep px-3 py-2 text-sm font-medium text-white hover:bg-accent disabled:opacity-50";
const input = "mt-1 w-full min-w-0 rounded-md border border-sage-border bg-white px-3 py-2 text-sm text-sage-ink";
const section = "min-w-0 rounded-xl border border-sage-border bg-white p-4 sm:p-5";
type Draft = { request: FieldCaseRequest; preview: FieldCaseReceipt; ref: FieldCaseRecovery };
async function bounded<T>(call: () => Promise<T>, controller: AbortController) { let timer: ReturnType<typeof setTimeout> | undefined; try { return await Promise.race([call(), new Promise<never>((_, reject) => { timer = setTimeout(() => { controller.abort(); reject(new Error("Private operation timed out")); }, 25000); })]); } finally { if (timer) clearTimeout(timer); } }
function Pin({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-xs text-sage-muted">{label}</dt><dd className="break-all text-xs text-sage-ink">{value ?? "Unestablished"}</dd></div>; }
function Disposition({ entry }: { entry: { eligibility: { eligible: boolean; reason_codes: string[] } } }) { return entry.eligibility.eligible ? <span className="text-xs text-accent-deep">Current target scope</span> : <p className="text-xs text-amber-800">{entry.eligibility.reason_codes.map(fieldCaseReason).join(" · ")}</p>; }
function SourceView({ expression }: { expression: SourceRevision }) {
  const p = expression.projection, href = expressionSourceHref(expression.capture.source.url);
  const status = (value: SourceRevision["projection"]["value"]) => "raw_unit" in value && value.status !== "parsed" ? value.status === "unit_not_supplied" ? "Unit not supplied; numerical interpretation unresolved" : value.status === "unit_requires_review" ? "Unit requires interpretation" : "Source value requires interpretation" : null;
  return <div className="space-y-2 text-sm">
    <p className="break-words font-medium text-sage-ink">{p.subject.formula} · {sourceValueLabel(p.value)}</p>
    {status(p.value) && <p className="text-xs text-amber-800">{status(p.value)}</p>}
    <p className="text-xs text-sage-muted">{p.source_role.replaceAll("_", " ")} · {p.knowledge_origin} · {p.window.raw_label ?? "Window label unavailable"}</p>
    {p.model && <p className="text-xs">Model: {p.model}</p>}
    {p.conditions.length > 0 && <dl className="grid gap-2 sm:grid-cols-2">{p.conditions.map((c, i) => <div key={i}><dt className="text-xs text-sage-muted">{fieldCaseLabel(c.field_id)} · {c.role.replaceAll("_", " ")}</dt><dd className="break-words text-sm">{sourceValueLabel(c.value)}{status(c.value) && <span className="mt-1 block text-xs text-amber-800">{status(c.value)}</span>}</dd></div>)}</dl>}
    <details className="text-xs text-sage-muted"><summary className="cursor-pointer">Source window, locator and integrity</summary>
      <dl className="mt-2 grid gap-2"><Pin label="Source ID" value={expression.capture.source.source_id} /><Pin label="Revision ID" value={expression.id} /><Pin label="Retained fragment SHA256" value={expression.capture.source_content_sha256} /><Pin label="Declared parent-file SHA256, unverified" value={expression.capture.source.original_parent_sha256} /></dl>
      <p className="mt-2 break-words">{Object.entries(p.locator).filter(([, v]) => v !== null).map(([k, v]) => `${k}: ${v}`).join(" · ") || "Locator unavailable"}</p>
      <p className="mt-2">Source window: {p.window.id}. Declared currentness: {expression.capture.source.currentness.replaceAll("_", " ")}. Rights: {expression.capture.source.rights_status.replaceAll("_", " ")}. Publication revision, currentness and rights remain unverified.</p>
      {href && <a className="mt-2 inline-block text-accent-deep underline" href={href} target="_blank" rel="noopener noreferrer">Open declared source link</a>}
    </details>
  </div>;
}
function TargetSummary({ canonical }: { canonical: string }) {
  const items = fieldCaseTargetSummary(canonical);
  return <div role="region" className="space-y-2 rounded-md bg-sage-surface p-3" aria-label="Retained target summary"><p className="text-xs text-sage-muted">Retained metadata; not an accepted selected value. Stored precision is distinct from printed source precision.</p>{items.length ? <dl className="grid gap-2 sm:grid-cols-2">{items.map(item => <div key={item.label}><dt className="text-xs text-sage-muted">{item.label}</dt><dd className="break-words text-sm text-sage-ink">{item.value}</dd></div>)}</dl> : <p className="text-xs text-sage-muted">No known scalar summary in this retained context. Inspect its exact proof.</p>}</div>;
}
function RowHistory({ entry, onWithdraw, canWithdraw, reviewField }: { entry: FieldCaseEntry; onWithdraw?: () => void; canWithdraw?: boolean; reviewField?: string }) {
  const attempt = entry.operation === "attempt" ? entry.payload as FieldCaseAttemptPayload : null, association = entry.operation === "association" ? entry.payload as FieldCaseAssociationPayload : null;
  const projection = entry.expression?.projection;
  const conditions = projection?.conditions.map((c, index) => ({ ...c, index })).filter(c => c.field_id === reviewField && c.role === "reported_result_condition") ?? [];
  const standaloneMethod = reviewField === "measurement_method" && projection?.field_id === "measurement_method";
  const reviewSelection = reviewField && FIELD_REVIEW_FIELDS.some(f => f === reviewField) && (standaloneMethod || projection?.field_id === "tc_kelvin" && conditions.length === 1)
    ? { field: reviewField, kind: standaloneMethod ? "value" : "condition", index: standaloneMethod ? "0" : String(conditions[0].index) } : null;
  return <li className="space-y-2 border-t border-sage-border py-3 first:border-t-0">
    <p className="text-sm font-medium">{attempt ? fieldCaseReason(attempt.outcome) : association?.action === "withdraw" ? "Proposal withdrawn" : "Source association proposed"} <span className="font-normal text-sage-muted">· {entry.is_head ? "Current head" : "Historical entry"}</span></p>
    <Disposition entry={entry} />
    {attempt && <><p className="break-words text-sm">{attempt.checked_scope.scope_label}</p><p className="text-xs text-sage-muted">{attempt.reason_codes.map(fieldCaseReason).join(" · ")}</p><p className="text-xs text-sage-muted">Full text: {attempt.checked_scope.fulltext_checked ? "declared checked" : "not declared checked"} · Supplement: {attempt.checked_scope.supplement_checked ? "declared checked" : "not declared checked"}</p></>}
    {association && <p className="break-words text-xs text-sage-muted">Proposed paper: {association.source_identity.paper_id ?? "Unresolved"} · Proposed Work: {association.source_identity.work_id ?? "Unresolved"}</p>}
    {entry.expression && <SourceView expression={entry.expression} />}
    {association?.action === "propose" && entry.is_head && entry.eligibility.eligible && reviewSelection && <Link className="inline-block text-xs text-accent-deep underline" href={`/dashboard/research/material-field-review?${new URLSearchParams({ target: association.target_id, expression: association.expression_revision_id, association: entry.id, ...reviewSelection })}`}>Review this missing Tc field</Link>}
    <details className="text-xs text-sage-muted"><summary className="cursor-pointer">Record and source pins</summary><dl className="mt-2 grid gap-2"><Pin label="Entry ID" value={entry.id} /><Pin label="Record SHA256" value={entry.record_sha256} /><Pin label="Target context SHA256" value={entry.context_sha256} />{association && <Pin label="Expression revision ID" value={association.expression_revision_id} />}{attempt && <Pin label="Checked source IDs" value={attempt.checked_scope.source_ids.join(", ") || null} />}</dl></details>
    {canWithdraw && <button className={button} onClick={onWithdraw}>Preview withdrawal of my proposal</button>}
  </li>;
}

export function MaterialFieldCaseWorkbench({ initialMaterialId = "" }: { initialMaterialId?: string }) {
  const { user } = useDashboardUser();
  const [access, setAccess] = useState<FieldCaseCapabilities | null>(null), [materialId, setMaterialId] = useState(initialMaterialId);
  const [loadedMaterial, setLoadedMaterial] = useState<string | null>(null), [page, setPage] = useState<FieldCaseMaterialPage | null>(null), [detail, setDetail] = useState<FieldCaseDetail | null>(null), [context, setContext] = useState<FieldCaseContext | null>(null);
  const [kind, setKind] = useState<TargetKind>("retained_result"), [recordIndex, setRecordIndex] = useState("0"), [entityId, setEntityId] = useState(""), [field, setField] = useState("tc_kelvin");
  const [expressions, setExpressions] = useState<ExpressionPage | null>(null), [expression, setExpression] = useState<SourceRevision | null>(null), [sourceId, setSourceId] = useState(""), [expressionChain, setExpressionChain] = useState<string | null>(null);
  const [paperId, setPaperId] = useState(""), [workId, setWorkId] = useState(""), [outcome, setOutcome] = useState("source_unavailable"), [reasons, setReasons] = useState<string[]>(["source_unavailable"]), [scopeLabel, setScopeLabel] = useState(""), [sourceIds, setSourceIds] = useState(""), [fulltext, setFulltext] = useState(false), [supplement, setSupplement] = useState(false), [includeExpression, setIncludeExpression] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null), [receipt, setReceipt] = useState<FieldCaseReceipt | null>(null), [recovery, setRecovery] = useState<FieldCaseRecovery | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState<string | null>(null);
  const mounted = useRef(false), seq = useRef(0), controller = useRef<AbortController | null>(null), retained = useRef<FieldCaseRecovery | null>(null);
  const cap = access?.actor_user_id === user.id ? access : null, locked = busy || recovery !== null;
  const target = detail?.target, targetPayload = target?.payload as FieldCaseTargetPayload | undefined, targetField = targetPayload?.field_id ?? field;
  function clearDraft() { setDraft(null); setReceipt(null); }
  function clearSources() { setExpressions(null); setExpression(null); setExpressionChain(null); setSourceId(""); setPaperId(""); setWorkId(""); setIncludeExpression(false); }
  function clearCases() { setLoadedMaterial(null); setPage(null); setDetail(null); setContext(null); clearSources(); clearDraft(); setScopeLabel(""); setSourceIds(""); setFulltext(false); setSupplement(false); }
  function clearPrivate() { ++seq.current; controller.current?.abort(); setAccess(null); clearCases(); setRecovery(null); retained.current = null; setBusy(false); }
  function begin() { const version = ++seq.current; controller.current?.abort(); const next = new AbortController(); controller.current = next; return { signal: next.signal, active: () => mounted.current && seq.current === version, run: <T,>(call: () => Promise<T>) => bounded(call, next) }; }
  function fail(error: unknown) { clearCases(); setBusy(false); if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared."); } else if (error instanceof ApiError && error.status === 404) setMessage("This field-case interface, target or source is unavailable. No absence was inferred."); else if (error instanceof ApiError && error.status === 409) setMessage("The target, source head or access changed. Reload before preparing another preview."); else setMessage("The response could not be verified. Reload the exact target before continuing."); }
  async function refreshAccess() {
    const op = begin(); setAccess(null); clearCases(); setBusy(true); setMessage(null);
    try { const next = knownFieldCaseCapabilities(await op.run(() => materialFieldCaseCapabilities(op.signal)), user.id); if (!op.active()) return; if (!next) throw new Error("Unsupported capability"); setAccess(next); setBusy(false); if (retained.current?.actorId === user.id) { setRecovery(retained.current); setMessage("The original save still needs a GET outcome check. No write will be retried."); } else { retained.current = null; setRecovery(null); } }
    catch (error) { if (op.active()) fail(error); }
  }
  useEffect(() => { mounted.current = true; clearPrivate(); void refreshAccess(); const unsubscribe = onAuthChange(() => { clearPrivate(); setMessage("Session changed. Private information has been cleared; refresh access."); }); return () => { unsubscribe(); mounted.current = false; ++seq.current; controller.current?.abort(); }; /* Auth owns every retained draft and response. */ // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user.id]);
  useEffect(() => { if (initialMaterialId !== materialId && !retained.current) { ++seq.current; controller.current?.abort(); clearCases(); setMaterialId(initialMaterialId); setBusy(false); } // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialMaterialId]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (retained.current) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, []);
  function editMaterial(value: string) { if (locked) return; ++seq.current; controller.current?.abort(); clearCases(); setMaterialId(value); setMessage(null); }
  async function loadMaterial(offset = 0) {
    if (!cap || locked || !fieldCaseText(materialId, 100)) return; const current = cap, id = materialId, op = begin(); clearCases(); setBusy(true); setMessage(null);
    try { const next = await knownFieldCaseMaterial(await op.run(() => materialFieldCaseMaterial(id, offset, op.signal)), current, id, offset); if (!op.active()) return; if (!next) throw new Error("Unverified material window"); setPage(next); setLoadedMaterial(id); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function loadContext() {
    if (!cap || locked || !fieldCaseText(materialId, 100)) return; const current = cap, id = materialId, selectedKind = kind, index = kind === "retained_result" && /^\d+$/.test(recordIndex) ? Number(recordIndex) : null, entity = kind === "retained_result" ? null : entityId;
    if (kind === "retained_result" && (index === null || index > 4999) || kind !== "retained_result" && !entity) { setMessage("Choose an exact retained-record index or native entity ID."); return; }
    const op = begin(); setContext(null); setDetail(null); clearSources(); clearDraft(); setBusy(true); setMessage(null);
    try { const next = await knownFieldCaseContext(await op.run(() => materialFieldCaseContext(id, selectedKind, index, entity, op.signal)), current, id, selectedKind, index, entity); if (!op.active()) return; if (!next) throw new Error("Unverified target context"); setContext(next); setLoadedMaterial(id); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function inspectCase(item: FieldCaseEntry) {
    if (!cap || locked) return; const current = cap, op = begin(); setDetail(null); setContext(null); clearSources(); clearDraft(); setBusy(true); setMessage(null); setScopeLabel(""); setSourceIds(""); setFulltext(false); setSupplement(false);
    try { const next = await knownFieldCaseDetail(await op.run(() => materialFieldCaseDetail(item.id, op.signal)), current, item); if (!op.active()) return; if (!next) throw new Error("Unverified target detail"); setDetail(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function loadExpressions(offset = 0) {
    if (!cap || !target || locked) return; const mapped = cap.expression_field_map[targetField]; if (mapped === null) { setMessage("This field has no compatible typed source-expression intake yet. Record its checked scope or independent reference below."); return; }
    const sourceField = mapped.split(":")[0], filters = { field: sourceField, sourceId: sourceId || undefined }, op = begin(); setExpressions(null); setExpression(null); setIncludeExpression(false); setPaperId(""); setWorkId(""); clearDraft(); setBusy(true); setMessage(null);
    try { const next = await knownExpressionPage(await op.run(() => sourceExpressionList(offset, 8, filters, op.signal)), offset, 8, filters); if (!op.active()) return; if (!next) throw new Error("Unverified source-expression window"); setExpressions(next); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function selectExpression(item: SourceRevision) {
    if (!cap || !target || locked) return; const op = begin(); setExpression(null); setIncludeExpression(false); setPaperId(""); setWorkId(""); clearDraft(); setBusy(true); setMessage(null);
    try { const next = await knownSourceRevision(await op.run(() => sourceExpressionDetail(item.id, op.signal)), item.id, item.record_sha256); if (!op.active()) return; if (!next || !next.is_expression_head || !compatibleFieldExpression(targetField, next)) throw new Error("Unverified or incompatible expression"); const chain = await expressionSha(expressionCanonical([target.id, next.expression_key])); if (!op.active()) return; setExpression(next); setExpressionChain(chain); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  async function previewRequest(request: FieldCaseRequest, associationChain: string | null = null) {
    if (!cap?.can_write || locked) return; if (!knownFieldCaseRequest(request)) { setMessage("Check the exact IDs, source scope and reason choices before previewing."); return; }
    const current = cap, op = begin(); clearDraft(); setBusy(true); setMessage(null);
    try { const sha = await expressionSha(expressionCanonical(request)), ref = fieldCaseRecovery(request, current, sha, target, associationChain), next = await knownFieldCaseReceipt(await op.run(() => materialFieldCasePreview(request, op.signal)), current, ref, "preview"); if (!op.active()) return; if (!next) throw new Error("Unverified preview"); if (next.replayed) setReceipt(next); else setDraft({ request, preview: next, ref: { ...ref, previewSha: next.preview_sha256, receiptSha: next.receipt_sha256, receiptId: next.receipt_id } }); setBusy(false); }
    catch (error) { if (op.active()) fail(error); }
  }
  function requestKey() { return `field-case:${crypto.randomUUID()}`; }
  function previewTarget() { if (context) void previewRequest({ version: FIELD_CASE_REQUEST_VERSION, request_key: requestKey(), operation: "target", payload: { field_id: field, target: context.target } }); }
  function previewAssociation(previous?: FieldCaseEntry) {
    if (!target) return; const old = previous?.payload as FieldCaseAssociationPayload | undefined;
    if (!old && !expression) return;
    const p: FieldCaseAssociationPayload = { target_id: target.id, target_sha256: target.record_sha256, expression_revision_id: old?.expression_revision_id ?? expression!.id, expression_record_sha256: old?.expression_record_sha256 ?? expression!.record_sha256, source_identity: old?.source_identity ?? { paper_id: paperId || null, work_id: workId || null }, action: old ? "withdraw" : "propose", predecessor: old ? { id: previous!.id, record_sha256: previous!.record_sha256 } : (() => { const head = detail?.associations.find(a => a.is_head && fieldCaseEntryChain(a) === expressionChain); return head ? { id: head.id, record_sha256: head.record_sha256 } : null; })() };
    void previewRequest({ version: FIELD_CASE_REQUEST_VERSION, request_key: requestKey(), operation: "association", payload: p }, previous ? fieldCaseEntryChain(previous) : expressionChain);
  }
  function previewAttempt() {
    if (!target) return; const previous = detail?.attempts.find(a => a.is_head), ids = sourceIds.split(/\r?\n/).map(s => s.trim()).filter(Boolean);
    void previewRequest({ version: FIELD_CASE_REQUEST_VERSION, request_key: requestKey(), operation: "attempt", payload: { target_id: target.id, target_sha256: target.record_sha256, outcome, reason_codes: reasons, checked_scope: { source_ids: ids, fulltext_checked: fulltext, supplement_checked: supplement, scope_label: scopeLabel }, expression_pins: includeExpression && expression ? [{ revision_id: expression.id, record_sha256: expression.record_sha256 }] : [], predecessor: previous ? { id: previous.id, record_sha256: previous.record_sha256 } : null } });
  }
  async function commit() {
    if (!cap?.can_write || !draft || locked) return; const current = cap, selected = draft, op = begin(); retained.current = selected.ref; setBusy(true); setMessage(null);
    try { const next = await knownFieldCaseReceipt(await op.run(() => materialFieldCaseCommit(selected.request, selected.ref.previewSha, op.signal)), current, selected.ref, "commit"); if (!op.active()) return; if (!next) throw new Error("Unverified save"); retained.current = null; setRecovery(null); clearCases(); setReceipt(next); setBusy(false); setMessage("Saved to private pending history. Reload material cases to inspect the current view."); }
    catch (error) { if (!op.active()) return; if (error instanceof ApiError && [400, 401, 403, 409, 413, 415, 422].includes(error.status)) { retained.current = null; setRecovery(null); fail(error); } else { clearCases(); setRecovery(selected.ref); setBusy(false); setMessage("Save outcome is unknown. Check the original request with GET; no write will be retried. An unavailable receipt does not prove failure."); } }
  }
  async function checkOutcome() {
    if (!cap || !recovery || busy || recovery.actorId !== cap.actor_user_id) return; const current = cap, ref = recovery, op = begin(); setBusy(true); setMessage(null);
    try { const next = await knownFieldCaseReceipt(await op.run(() => materialFieldCaseOutcome(ref.requestKey, ref.requestSha, op.signal)), current, ref, "outcome"); if (!op.active()) return; if (!next) throw new Error("Unverified outcome"); retained.current = null; setRecovery(null); setReceipt(next); setBusy(false); setMessage("The original save is recorded. No new write was sent; reload material cases for current heads."); }
    catch (error) { if (!op.active()) return; if (error instanceof ApiError && [401, 403].includes(error.status)) { clearPrivate(); setMessage("Session or research access changed. Private information has been cleared."); } else { setBusy(false); setMessage("The original outcome remains unverified. No rollback or failed save is inferred; no write was retried."); } }
  }
  const canWrite = Boolean(cap?.can_write && !locked);
  return <div className="min-w-0 space-y-5">
    <header className="space-y-2"><p className="text-xs font-medium uppercase tracking-wide text-accent-deep">Private research workspace</p><h2 className="text-2xl font-semibold text-sage-ink">Material field cases</h2><p className="text-sm text-sage-muted">Track missing fields against an exact retained result, record the scope checked, and propose existing source expressions.</p><p className="text-xs text-sage-muted">Pending proposals do not establish sample, phase or selected-result identity. They do not change public values or confer scientific acceptance.</p></header>
    <div className="flex flex-wrap items-center gap-3"><button className={button} disabled={busy} onClick={() => void refreshAccess()}>Refresh access</button>{cap && <span className="text-xs text-sage-muted">{cap.can_write ? "Curator access" : "Read access"}</span>}{busy && <span role="status" className="text-sm text-sage-muted">Loading exact scope…</span>}</div>
    {message && <p role="status" className="rounded-md border border-sage-border bg-sage-surface p-3 text-sm text-sage-ink">{message}</p>}
    {cap && <>
      {recovery ? <section className={section} aria-label="Original save recovery"><h3 className="font-medium">Original save recovery</h3><p className="mt-2 text-sm text-sage-muted">Keep this page open until the original outcome is known. Recovery reads the original actor, key and preview pins.</p><button className={`${button} mt-3`} disabled={busy} onClick={() => void checkOutcome()}>Check original request</button><details className="mt-3 text-xs"><summary className="cursor-pointer">Original request pins</summary><dl className="mt-2 grid gap-2"><Pin label="Request key" value={recovery.requestKey} /><Pin label="Request SHA256" value={recovery.requestSha} /><Pin label="Preview SHA256" value={recovery.previewSha} /></dl></details></section> : <>
        <section className={section} aria-label="Exact material scope"><h3 className="font-medium">Exact material scope</h3><div className="mt-3 grid items-end gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label className="text-xs text-sage-muted">Material ID<input className={input} value={materialId} maxLength={100} disabled={locked} onChange={e => editMaterial(e.target.value)} /></label><button className={primary} disabled={locked || !fieldCaseText(materialId, 100)} onClick={() => void loadMaterial()}>Load material cases</button></div><p className="mt-2 text-xs text-sage-muted">Load uses an exact catalogue ID. Formula text does not establish an association.</p></section>
        {page && loadedMaterial === materialId && <section className={section} aria-label="Bounded material cases"><h3 className="font-medium">Material cases <span className="font-normal text-sage-muted">({page.entries_returned} of {page.total})</span></h3><Disposition entry={page} />{page.entries_omitted > 0 && <p className="mt-2 text-xs text-amber-800">{page.entries_omitted} requested cases omitted by the response bound. Continue from the returned window.</p>}{page.expressions_omitted > 0 && <p className="mt-2 text-xs text-sage-muted">{page.expressions_omitted} eligible expressions omitted from this bounded response.</p>}{page.entries.length === 0 ? <p className="mt-3 text-sm text-sage-muted">No field cases in this returned material window.</p> : <ul className="mt-2 divide-y divide-sage-border">{page.entries.map(item => { const p = item.target.payload as FieldCaseTargetPayload; return <li key={item.target.id} className="flex flex-wrap items-start justify-between gap-3 py-3"><div className="min-w-0"><p className="font-medium">{fieldCaseLabel(p.field_id)}</p><p className="text-xs text-sage-muted">{p.target.kind === "retained_result" ? `Retained record ${p.target.record_index}` : p.target.kind.replaceAll("_", " ")}</p><Disposition entry={item.target} /></div><button className={button} disabled={locked} onClick={() => void inspectCase(item.target)}>Inspect case</button></li>; })}</ul>}<div className="mt-3 flex flex-wrap gap-2"><button className={button} disabled={locked || page.offset === 0} onClick={() => void loadMaterial(0)}>First window</button>{page.next_offset !== null && <button className={button} disabled={locked} onClick={() => void loadMaterial(page.next_offset!)}>Next returned window</button>}</div></section>}
        {cap.can_write && <section className={section} aria-label="Create exact field target"><h3 className="font-medium">Create a field target</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-sage-muted">Scientific field<select className={input} value={field} disabled={locked} onChange={e => { setField(e.target.value); clearDraft(); }}>{cap.field_ids.map(id => <option value={id} key={id}>{fieldCaseLabel(id)}</option>)}</select></label><label className="text-xs text-sage-muted">Target record type<select className={input} value={kind} disabled={locked} onChange={e => { setKind(e.target.value as TargetKind); setContext(null); clearDraft(); }}><option value="retained_result">Retained result</option><option value="tc_claim">Native Tc claim</option><option value="event_property">Native event property</option></select></label>{kind === "retained_result" ? <label className="text-xs text-sage-muted">Retained record index<input className={input} inputMode="numeric" value={recordIndex} disabled={locked} onChange={e => { setRecordIndex(e.target.value); setContext(null); clearDraft(); }} /></label> : <label className="text-xs text-sage-muted">Native entity ID<input className={input} value={entityId} disabled={locked} onChange={e => { setEntityId(e.target.value); setContext(null); clearDraft(); }} /></label>}</div><button className={`${button} mt-3`} disabled={locked || !fieldCaseText(materialId, 100)} onClick={() => void loadContext()}>Load target context</button>{context && <div className="mt-4 space-y-3 border-t border-sage-border pt-3"><Disposition entry={context} /><TargetSummary canonical={context.context_canonical_json} /><dl className="grid gap-3 sm:grid-cols-2"><Pin label="Paper ID in retained context" value={context.closure.paper_id} /><Pin label="Sample link in record closure" value={context.closure.sample_id} /><Pin label="State link in record closure" value={context.closure.state_id} /><Pin label="Context SHA256" value={context.context_sha256} /></dl><details className="text-xs"><summary className="cursor-pointer">Exact private target proof</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all rounded-md bg-sage-surface p-3">{context.context_canonical_json}</pre></details><button className={primary} disabled={!canWrite} onClick={previewTarget}>Preview field target</button></div>}</section>}
        {detail && target && <section className={section} aria-label="Exact field case"><h3 className="text-lg font-medium">{fieldCaseLabel(targetField)}</h3><Disposition entry={target} /><div className="mt-3"><TargetSummary canonical={target.context_canonical_json!} /></div><details className="mt-3 text-xs"><summary className="cursor-pointer">Exact target pins</summary><dl className="mt-2 grid gap-2"><Pin label="Target ID" value={target.id} /><Pin label="Target record SHA256" value={target.record_sha256} /><Pin label="Context SHA256" value={target.context_sha256} /></dl></details>
          {cap.can_write && <div className="mt-5 space-y-5 border-t border-sage-border pt-4">
            <div><h4 className="font-medium">Existing source expression</h4><p className="mt-1 text-xs text-sage-muted">The source subject and conditions stay separate from the target. Publication identity is a proposal.</p>{cap.expression_field_map[targetField] === null ? <p className="mt-2 text-sm text-sage-muted">Typed expression intake does not support this field yet. You can record checked scope or an independent reference.</p> : <><div className="mt-3 grid items-end gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><label className="text-xs text-sage-muted">Source ID filter (optional)<input className={input} value={sourceId} disabled={locked} onChange={e => { setSourceId(e.target.value); setExpressions(null); setExpression(null); clearDraft(); }} /></label><button className={button} disabled={locked} onClick={() => void loadExpressions()}>Load compatible expressions</button></div>{expressions && <><p className="mt-3 text-xs text-sage-muted">{expressions.expressions.length} of {expressions.total} current expression heads; records are not independent experiments.</p><ul className="mt-2 divide-y divide-sage-border">{expressions.expressions.map(item => <li className="flex flex-wrap items-start justify-between gap-2 py-3" key={item.id}><div className="min-w-0"><p className="break-words text-sm">{item.projection.subject.formula} · {sourceValueLabel(item.projection.value)}</p><p className="text-xs text-sage-muted">{item.projection.window.raw_label ?? "Unlabelled source window"} · {item.capture.source.source_id}</p></div><button className={button} disabled={locked || !compatibleFieldExpression(targetField, item)} onClick={() => void selectExpression(item)}>Inspect source expression</button></li>)}</ul>{expressions.offset + expressions.expressions.length < expressions.total && <button className={button} disabled={locked} onClick={() => void loadExpressions(expressions.offset + expressions.expressions.length)}>Next expression window</button>}</>}</>}
              {expression && <div className="mt-3 space-y-3 rounded-md border border-sage-border p-3"><SourceView expression={expression} /><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-sage-muted">Proposed existing paper ID (optional)<input className={input} value={paperId} maxLength={100} disabled={locked} onChange={e => { setPaperId(e.target.value); clearDraft(); }} /></label><label className="text-xs text-sage-muted">Proposed existing Work ID (optional)<input className={input} value={workId} disabled={locked} onChange={e => { setWorkId(e.target.value); clearDraft(); }} /></label></div><button className={primary} disabled={!canWrite || !target.eligibility.eligible} onClick={() => previewAssociation()}>Preview source proposal</button></div>}
            </div>
            <div><h4 className="font-medium">Record a bounded source check</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-sage-muted">Outcome<select className={input} value={outcome} disabled={locked} onChange={e => { setOutcome(e.target.value); setReasons([e.target.value]); clearDraft(); }}>{FIELD_CASE_OUTCOMES.map(id => <option value={id} key={id}>{fieldCaseReason(id)}</option>)}</select></label><label className="text-xs text-sage-muted">Checked source IDs (one per line, up to eight)<textarea className={input} rows={2} value={sourceIds} disabled={locked} onChange={e => { setSourceIds(e.target.value); clearDraft(); }} /></label><label className="text-xs text-sage-muted sm:col-span-2">Checked scope<textarea className={input} rows={2} maxLength={500} value={scopeLabel} disabled={locked} onChange={e => { setScopeLabel(e.target.value); clearDraft(); }} placeholder="For example: abstract and table 2; supplement could not be obtained" /></label></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={fulltext} disabled={locked} onChange={e => { setFulltext(e.target.checked); clearDraft(); }} />Full text checked</label><label className="flex items-center gap-2"><input type="checkbox" checked={supplement} disabled={locked} onChange={e => { setSupplement(e.target.checked); clearDraft(); }} />Supplement checked</label>{expression && <label className="flex items-center gap-2"><input type="checkbox" checked={includeExpression} disabled={locked} onChange={e => { setIncludeExpression(e.target.checked); clearDraft(); }} />Pin inspected expression</label>}</div><details className="mt-3 text-xs"><summary className="cursor-pointer">Reasons ({reasons.length})</summary><div className="mt-2 grid gap-2 sm:grid-cols-2">{FIELD_CASE_REASONS.map(id => <label key={id} className="flex items-start gap-2"><input type="checkbox" checked={reasons.includes(id)} disabled={locked || !reasons.includes(id) && reasons.length >= 16} onChange={e => { setReasons(e.target.checked ? [...reasons, id] : reasons.filter(x => x !== id)); clearDraft(); }} />{fieldCaseReason(id)}</label>)}</div></details><p className="mt-2 text-xs text-sage-muted">A bounded check cannot establish that a whole paper or supplement does not report a field.</p><button className={`${primary} mt-3`} disabled={!canWrite || !scopeLabel.trim()} onClick={previewAttempt}>Preview source check</button></div>
          </div>}
          <details className="mt-5" open={detail.associations.length > 0}><summary className="cursor-pointer text-sm font-medium">Source proposal history ({detail.association_returned} of {detail.association_total})</summary><ul className="mt-2">{detail.associations.map(a => <RowHistory key={a.id} entry={a} reviewField={targetPayload?.target.kind === "retained_result" ? targetField : undefined} canWithdraw={canWrite && a.is_head && (a.payload as FieldCaseAssociationPayload).action === "propose" && fieldCaseEntryActor(a) === cap.actor_user_id} onWithdraw={() => previewAssociation(a)} />)}</ul>{detail.association_omitted > 0 && <p className="text-xs text-sage-muted">{detail.association_omitted} historical entries outside this returned window.</p>}</details>
          <details className="mt-4" open={detail.attempts.length > 0}><summary className="cursor-pointer text-sm font-medium">Source check history ({detail.attempt_returned} of {detail.attempt_total})</summary><ul className="mt-2">{detail.attempts.map(a => <RowHistory key={a.id} entry={a} />)}</ul>{detail.attempt_omitted > 0 && <p className="text-xs text-sage-muted">{detail.attempt_omitted} historical entries outside this returned window.</p>}</details>
        </section>}
      </>}
      {draft && <section className={`${section} border-accent-deep`} aria-label="Exact pending preview"><h3 className="font-medium">Exact pending preview</h3><p className="mt-2 text-sm">{draft.request.operation === "target" ? `Create ${fieldCaseLabel((draft.request.payload as FieldCaseTargetPayload).field_id)} target` : draft.request.operation === "attempt" ? fieldCaseReason((draft.request.payload as FieldCaseAttemptPayload).outcome) : (draft.request.payload as FieldCaseAssociationPayload).action === "withdraw" ? "Withdraw my preceding proposal" : "Propose this source expression"}</p><p className="mt-2 text-xs text-sage-muted">Preview has not retained a ledger write. Save appends private pending history; public scientific values remain unchanged.</p><details className="mt-3 text-xs"><summary className="cursor-pointer">Exact operation and proof</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all rounded-md bg-sage-surface p-3">{draft.preview.request_canonical_json}</pre><Pin label="Preview SHA256" value={draft.ref.previewSha} /></details><button className={`${primary} mt-3`} disabled={locked || !cap.can_write} onClick={() => void commit()}>Save pending operation</button></section>}
      {receipt && <section className={section} aria-label="Saved pending operation"><h3 className="font-medium">Saved pending operation</h3><p className="mt-2 text-sm">{receipt.replayed ? "Original receipt recovered" : "Private ledger write recorded"}. This receipt does not approve a scientific value or association.</p><details className="mt-3 text-xs"><summary className="cursor-pointer">Receipt pins</summary><dl className="mt-2 grid gap-2"><Pin label="Receipt ID" value={receipt.receipt_id} /><Pin label="Receipt SHA256" value={receipt.receipt_sha256} /><Pin label="Request SHA256" value={receipt.request_sha256} /></dl></details></section>}
      <p className="text-xs text-sage-muted"><Link href="/dashboard/research/source-expressions" className="text-accent-deep underline">Source-expression intake</Link> retains source fragments separately. Field cases propose a relationship to an existing target; publication and physical identity remain unestablished.</p>
    </>}
  </div>;
}
