apiVersion: 1

datasources:
  - name: SCLib Prometheus
    type: prometheus
    uid: sclib-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      manageAlerts: true
      alertmanagerUid: sclib-alertmanager

  - name: SCLib Alertmanager
    type: alertmanager
    uid: sclib-alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
