/** Test-owned batch/link seals for client rejection and transport tests. Not native SQL evidence. */
import wire from "../fixtures/discovery-designs-native.synthetic.json";
import { createConditionSweep, type ConditionSweepAxes } from "@/lib/discovery-condition-sweep";
import { DESIGN_VERSION, DESIGN_REQUEST_VERSION, knownDesignCapabilities, type DesignEntry } from "@/lib/discovery-designs";
import { CONDITION_BATCH_AUTHORITY, CONDITION_BATCH_VERSION, CONDITION_BATCH_REQUEST_VERSION, type ConditionBatchReceipt, type ConditionBatchRequest } from "@/lib/discovery-condition-batches";
import { expressionCanonical, expressionSha } from "@/lib/source-expressions";

export const TEST_UUID = "00000000-0000-0000-0000-000000000042";
export const copy = <T,>(v: T): T => structuredClone(v);
export const designCap = () => knownDesignCapabilities(copy(wire.capabilities), wire.capabilities.actor_user_id)!;
export const defaultAxes: ConditionSweepAxes = { pressures: ["10", "10.0", "50", "100", "200"].map(raw_gpa => ({ kind: "specified", raw_gpa })), temperatures_k: ["250", "300", "350"] };
export async function syntheticBatch(axes = defaultAxes) {
  const design = designCap(), entry = copy(wire.page.entries[0]) as DesignEntry;
  const manifest = await createConditionSweep({ capabilities: design, entry, axes });
  const cap = { ...CONDITION_BATCH_AUTHORITY, version: CONDITION_BATCH_VERSION, request_version: CONDITION_BATCH_REQUEST_VERSION, actor_user_id: design.actor_user_id, session_version: design.session_version, curator_grant_id: design.curator_grant_id, can_write: true as const, operations: ["retain_batch", "propose_candidate_child"] as const, max_page_size: 8 as const, max_operation_bytes: 16384 as const, max_manifest_bytes: 4194304 as const };
  const request: ConditionBatchRequest = { version: CONDITION_BATCH_REQUEST_VERSION, request_key: `condition-batch:${TEST_UUID}`, operation: "retain_batch", payload: { parent: manifest.parent, axes: copy(axes), expected_input_sha256: manifest.input_sha256, expected_manifest_sha256: manifest.manifest_sha256 } };
  const actor = { actor_user_id: cap.actor_user_id, actor_grant_id: cap.curator_grant_id, actor_session_version: cap.session_version }, id = "10000000-0000-0000-0000-000000000001";
  const requestJson = expressionCanonical(request), requestSha = await expressionSha(requestJson);
  const previewJson = expressionCanonical({ version: CONDITION_BATCH_VERSION, actor, request_sha256: requestSha, receipt_id: id, batch_id: id, parent: manifest.parent, input_sha256: manifest.input_sha256, manifest_sha256: manifest.manifest_sha256, scenario_total: manifest.scenarios.length }), previewSha = await expressionSha(previewJson);
  const { scope: _scope, ...flags } = CONDITION_BATCH_AUTHORITY;
  const record = { id, ...actor, operation: request.operation, request_key: request.request_key, request_json: requestJson, payload: request.payload, request_sha256: requestSha, preview_json: previewJson, preview_sha256: previewSha, parent: manifest.parent, source_pins: manifest.source_pins, input_json: manifest.input_canonical_json, input_sha256: manifest.input_sha256, manifest_sha256: manifest.manifest_sha256, scenario_total: manifest.scenarios.length, ...flags };
  const recordJson = expressionCanonical(record), recordSha = await expressionSha(recordJson);
  const preview: ConditionBatchReceipt = { ...CONDITION_BATCH_AUTHORITY, version: CONDITION_BATCH_VERSION, receipt_id: id, receipt_sha256: recordSha, ...actor, operation: request.operation, request_key: request.request_key, request_sha256: requestSha, preview_sha256: previewSha, request_canonical_json: requestJson, preview_canonical_json: previewJson, receipt_canonical_json: recordJson, batch_id: id, batch_record_sha256: recordSha, input_sha256: manifest.input_sha256, manifest_sha256: manifest.manifest_sha256, candidate_sha256: null, child: null, replayed: false, dry_run: true, pending_ledger_written: false };
  const commit = { ...preview, dry_run: false, pending_ledger_written: true }, outcome = { ...commit, replayed: true };
  const batch = { ...CONDITION_BATCH_AUTHORITY, id, record_sha256: recordSha, parent: manifest.parent, source_pins: manifest.source_pins, input_sha256: manifest.input_sha256, manifest_sha256: manifest.manifest_sha256, scenario_total: manifest.scenarios.length, eligibility: { eligible: true, reason_codes: [] }, receipt: commit };
  const page = { ...CONDITION_BATCH_AUTHORITY, version: CONDITION_BATCH_VERSION, actor_user_id: cap.actor_user_id, session_version: cap.session_version, offset: 0, limit: 8 as const, total: 1, entries: [batch] };
  const detail = (offset = 0) => ({ ...CONDITION_BATCH_AUTHORITY, version: CONDITION_BATCH_VERSION, actor_user_id: cap.actor_user_id, session_version: cap.session_version, entry: batch, offset, limit: 8 as const, scenario_total: manifest.scenarios.length, scenarios: manifest.scenarios.slice(offset, offset + 8).map(s => ({ ...copy(s), child: null })) });
  const scenario = manifest.scenarios[0], childRequest: ConditionBatchRequest = { version: CONDITION_BATCH_REQUEST_VERSION, request_key: `condition-child:${TEST_UUID}`, operation: "propose_candidate_child", payload: { batch: { id, record_sha256: recordSha, manifest_sha256: manifest.manifest_sha256 }, candidate_sha256: scenario.candidate_sha256 } };
  const childId = "10000000-0000-0000-0000-000000000003", childDesign = "10000000-0000-0000-0000-000000000004", linkId = "10000000-0000-0000-0000-000000000002";
  const nativeRequest = { version: DESIGN_REQUEST_VERSION, request_key: "synthetic-condition-child-native", operation: "propose", payload: { baseline: batch.source_pins.baseline, design: scenario.proposal, parent: { design_id: batch.parent.design_id, revision_id: batch.parent.revision_id, record_sha256: batch.parent.record_sha256 } } };
  const nativeRequestJson = expressionCanonical(nativeRequest), nativeRequestSha = await expressionSha(nativeRequestJson);
  const nativePreviewJson = expressionCanonical({ version: DESIGN_VERSION, actor, request_sha256: nativeRequestSha, receipt_id: childId, design_id: childDesign, revision: 1, context_sha256: batch.source_pins.context_sha256 }), nativePreviewSha = await expressionSha(nativePreviewJson);
  const nativeRecord = { ...JSON.parse(wire.commit.receipt_canonical_json), id: childId, design_id: childDesign, ...actor, revision: 1, operation: "propose", request_key: nativeRequest.request_key, request_json: nativeRequestJson, request_sha256: nativeRequestSha, payload: nativeRequest.payload, preview_json: nativePreviewJson, preview_sha256: nativePreviewSha, baseline: nativeRequest.payload.baseline, design: scenario.proposal, parent: nativeRequest.payload.parent, predecessor_id: null, predecessor_sha256: null };
  const nativeRecordJson = expressionCanonical(nativeRecord), nativeRecordSha = await expressionSha(nativeRecordJson);
  const nativeChild = { ...copy(wire.commit), receipt_id: childId, design_id: childDesign, receipt_sha256: nativeRecordSha, ...actor, request_key: nativeRequest.request_key, request_sha256: nativeRequestSha, preview_sha256: nativePreviewSha, request_canonical_json: nativeRequestJson, preview_canonical_json: nativePreviewJson, receipt_canonical_json: nativeRecordJson, dry_run: true, pending_ledger_written: false, replayed: false };
  const childRequestJson = expressionCanonical(childRequest), childRequestSha = await expressionSha(childRequestJson), pin = { design_id: childDesign, revision_id: childId, record_sha256: nativeRecordSha };
  const childPreviewJson = expressionCanonical({ version: CONDITION_BATCH_VERSION, actor, request_sha256: childRequestSha, receipt_id: linkId, batch_id: id, batch_record_sha256: recordSha, manifest_sha256: manifest.manifest_sha256, candidate_sha256: scenario.candidate_sha256, child: pin }), childPreviewSha = await expressionSha(childPreviewJson);
  const link = { id: linkId, ...actor, operation: childRequest.operation, request_key: childRequest.request_key, request_json: childRequestJson, payload: childRequest.payload, request_sha256: childRequestSha, preview_json: childPreviewJson, preview_sha256: childPreviewSha, batch_id: id, batch_record_sha256: recordSha, manifest_sha256: manifest.manifest_sha256, candidate_sha256: scenario.candidate_sha256, child_revision_id: childId, child_design_id: childDesign, child_record_sha256: nativeRecordSha, ...flags };
  const linkJson = expressionCanonical(link), linkSha = await expressionSha(linkJson);
  const childPreview: ConditionBatchReceipt = { ...preview, operation: "propose_candidate_child", receipt_id: linkId, receipt_sha256: linkSha, request_key: childRequest.request_key, request_sha256: childRequestSha, preview_sha256: childPreviewSha, request_canonical_json: childRequestJson, preview_canonical_json: childPreviewJson, receipt_canonical_json: linkJson, candidate_sha256: scenario.candidate_sha256, child: nativeChild };
  const childCommit = { ...childPreview, dry_run: false, pending_ledger_written: true, child: { ...nativeChild, dry_run: false, pending_ledger_written: true } }, childOutcome = { ...childCommit, replayed: true };
  return { design, cap, manifest, request, record, preview, commit, outcome, batch, page, detail, text: expressionCanonical(manifest), scenario, childRequest, childPreview, childCommit, childOutcome, pin };
}
