import { webcrypto } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ApiError, materialFieldReviewCommit, materialFieldReviewContext, materialFieldReviewEffective, materialFieldReviewOutcome } from "@/lib/api";
import { syntheticReviewRequest, reviewExpression, reviewTarget } from "../helpers/material-field-review-test-data";
beforeEach(() => vi.stubGlobal("crypto", webcrypto));
afterEach(() => vi.unstubAllGlobals());
describe("Private material field-review HTTP boundary", () => {
  it("uses credentialed no-store reads with the exact target, source component and abort signal", async () => { const fetcher = vi.fn().mockResolvedValue(new Response("{}", { headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetcher); const controller = new AbortController(); await materialFieldReviewContext({ targetId: reviewTarget, expressionId: reviewExpression, fieldId: "tc_criterion", componentKind: "condition", componentIndex: 3 }, controller.signal); const [url, options] = fetcher.mock.calls[0], query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("target_id")).toBe(reviewTarget); expect(query.get("expression_revision_id")).toBe(reviewExpression); expect(query.get("component_index")).toBe("3"); expect(query.has("association_id")).toBe(false); expect(options).toMatchObject({ credentials: "include", cache: "no-store", signal: controller.signal }); expect(options.body).toBeUndefined(); });
  it("never repeats an unknown POST and recovers through the original GET key and hash", async () => { const fetcher = vi.fn().mockResolvedValueOnce(new Response("{}", { status: 503, headers: { "content-type": "application/json" } })).mockResolvedValueOnce(new Response("{}", { headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetcher); const request = await syntheticReviewRequest(); await expect(materialFieldReviewCommit(request, "b".repeat(64))).rejects.toBeInstanceOf(ApiError); expect(fetcher).toHaveBeenCalledOnce(); expect(JSON.parse(fetcher.mock.calls[0][1].body)).toEqual({ request, expected_preview_sha256: "b".repeat(64) }); await materialFieldReviewOutcome(request.request_key, "c".repeat(64)); const [url, options] = fetcher.mock.calls[1], query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("request_key")).toBe(request.request_key); expect(query.get("expected_request_sha256")).toBe("c".repeat(64)); expect(options.method).not.toBe("POST"); expect(options.body).toBeUndefined(); });
  it("bounds an effective-field response before parsing or displaying private source contents", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ private_context: "x".repeat(512 * 1024 + 1) }), { headers: { "content-type": "application/json" } }))); await expect(materialFieldReviewEffective(reviewTarget, "tc_criterion")).rejects.toBeInstanceOf(ApiError); });
});
