import { webcrypto } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { expressionCanonical, expressionSha } from "@/lib/source-expressions";
import { compatibleFieldExpression, fieldCaseRecovery, fieldCaseTargetSummary, knownFieldCaseCapabilities, knownFieldCaseContext, knownFieldCaseDetail, knownFieldCaseEntry, knownFieldCaseMaterial, knownFieldCaseReceipt, knownFieldCaseRequest, FIELD_CASE_REQUEST_VERSION, type FieldCaseRequest } from "@/lib/material-field-cases";
import { caseActor, caseCap, caseMaterial, syntheticCaseContext, syntheticCaseDetail, syntheticCaseEntry, syntheticCaseReceipt, syntheticCaseRequest, syntheticMaterialPage } from "../helpers/material-field-case-test-data";
import { syntheticRevision } from "../helpers/source-expression-test-data";
beforeEach(() => vi.stubGlobal("crypto", webcrypto));
describe("Private field-case original record and pending-operation contract", () => {
  it("binds capabilities to exact actor, field map, bounded page and unchanged false authority", () => { expect(knownFieldCaseCapabilities(caseCap, caseActor)).toEqual(caseCap); for (const delta of [{ actor_user_id: "00000000-0000-4000-8000-000000000999" }, { scientific_acceptance: true }, { max_page_size: 9 }, { expression_field_map: { ...caseCap.expression_field_map, lambda_london_nm: "lambda_eph" } }, { private_notes: "hidden" }]) expect(knownFieldCaseCapabilities({ ...caseCap, ...delta }, caseActor)).toBeNull(); });
  it("preserves decimal lexical context bytes and binds exact selector and closure IDs", async () => { const context = await syntheticCaseContext(); expect(await knownFieldCaseContext(context, caseCap, caseMaterial, "retained_result", 0, null)).toEqual(context); expect(context.context_canonical_json).toContain("23.000"); expect(await knownFieldCaseContext(context, caseCap, caseMaterial, "retained_result", 1, null)).toBeNull(); expect(await knownFieldCaseContext({ ...context, closure: { ...context.closure, paper_id: "other" } }, caseCap, caseMaterial, "retained_result", 0, null)).toBeNull(); });
  it("distinguishes retained onset and zero-resistance targets without joining sources or inventing pressure", async () => {
    const base = JSON.parse((await syntheticCaseContext()).context_canonical_json);
    const onset = { ...base, result: { tc_kelvin: 23, knowledge_origin: "Observed", tc_criterion: "onset", material_formula: "NominalPtFormula" } };
    const zero = { ...base, record_index: 1, result: { tc_kelvin: "21.5", knowledge_origin: "Observed", tc_criterion: "zero_resistance", pressure: "ambient" } };
    expect(fieldCaseTargetSummary(expressionCanonical(onset))).toEqual([{ label: "Retained formula", value: "NominalPtFormula" }, { label: "Retained Tc (K)", value: "23" }, { label: "Retained origin", value: "Observed" }, { label: "Retained criterion", value: "onset" }]);
    expect(fieldCaseTargetSummary(expressionCanonical(zero))).toEqual([{ label: "Retained Tc (K)", value: "21.5" }, { label: "Retained pressure label", value: "ambient" }, { label: "Retained origin", value: "Observed" }, { label: "Retained criterion", value: "zero_resistance" }]);
    expect(fieldCaseTargetSummary(expressionCanonical({ ...base, result: { tc_kelvin: null, scientific_acceptance: true, private_notes: "secret", method: "inferred", origin: "guessed" } }))).toEqual([]);
  });
  it("keeps generic and inline retained quantity units without falsely converting them", async () => {
    const base = JSON.parse((await syntheticCaseContext()).context_canonical_json);
    expect(fieldCaseTargetSummary(expressionCanonical({ ...base, result: { tc: "4.2 mK", pressure: 500, pressure_unit: "MPa" } }))).toEqual([{ label: "Retained Tc raw value", value: "4.2 mK" }, { label: "Retained pressure (MPa)", value: "500" }]);
    expect(fieldCaseTargetSummary(expressionCanonical({ ...base, result: { tc: "4.2", pressure: 500 } }))).toEqual([{ label: "Retained Tc raw value", value: "4.2" }, { label: "Retained pressure raw value", value: "500" }]);
    expect(fieldCaseTargetSummary(expressionCanonical({ ...base, result: { tc_kelvin: "4.2 mK", pressure_gpa: 500, pressure_unit: "MPa" } }))).toEqual([{ label: "Retained Tc raw value", value: "4.2 mK" }, { label: "Retained pressure (MPa)", value: "500" }]);
    expect(fieldCaseTargetSummary(expressionCanonical({ ...base, result: { tc_kelvin: "4.2", tc_kelvin_unit: "mK", pressure_gpa: 500, pressure_gpa_unit: "MPa", pressure_unit: "GPa" } }))).toEqual([{ label: "Retained Tc (mK)", value: "4.2" }, { label: "Retained pressure (MPa)", value: "500" }]);
  });
  it("refuses duplicate proof keys and coordinated context tamper under original immutable row hash", async () => { const entry = await syntheticCaseEntry(); const changed = structuredClone(entry); changed.payload = { ...changed.payload, field_id: "lambda_eph" } as typeof changed.payload; expect(await knownFieldCaseEntry(changed, "target")).toBeNull(); changed.record_canonical_json = changed.record_canonical_json.replace('"field_id":"tc_kelvin"', '"field_id":"lambda_eph"'); expect(await knownFieldCaseEntry(changed, "target")).toBeNull(); const duplicate = entry.record_canonical_json.replace('"operation":"target"', '"operation":"target","operation":"target"'); expect(await knownFieldCaseEntry({ ...entry, record_canonical_json: duplicate, record_sha256: await expressionSha(duplicate) }, "target")).toBeNull(); });
  it("rejects added nested payload keys, false whole-paper inspection and numeric-index coercions", async () => { const request = await syntheticCaseRequest(); expect(knownFieldCaseRequest(request)).toBe(true); expect(knownFieldCaseRequest({ ...request, payload: { ...request.payload, private_notes: "secret" } })).toBe(false); if (request.operation === "target") expect(knownFieldCaseRequest({ ...request, payload: { field_id: ["tc_kelvin"], target: request.payload.target } })).toBe(false); const target = await syntheticCaseEntry(); const attempt = { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:attempt", operation: "attempt", payload: { target_id: target.id, target_sha256: target.record_sha256, outcome: "source_unavailable", reason_codes: ["source_unavailable"], checked_scope: { source_ids: [], fulltext_checked: true, supplement_checked: false, scope_label: "No accessible full text" }, expression_pins: [], predecessor: null } }; expect(knownFieldCaseRequest(attempt)).toBe(false); attempt.payload.checked_scope.fulltext_checked = false; expect(knownFieldCaseRequest(attempt)).toBe(true); });
  it("requires an actual expression pin for the available-expression outcome", async () => { const target = await syntheticCaseEntry(); const request = { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:available", operation: "attempt", payload: { target_id: target.id, target_sha256: target.record_sha256, outcome: "pending_expression_available", reason_codes: ["bounded_scope_only"], checked_scope: { source_ids: ["synthetic"], fulltext_checked: false, supplement_checked: false, scope_label: "Abstract only" }, expression_pins: [], predecessor: null } }; expect(knownFieldCaseRequest(request)).toBe(false); });
  it("does not equate a Tc quantity with its criterion or London length with EPC", async () => { const expression = await syntheticRevision(); expect(compatibleFieldExpression("tc_kelvin", expression)).toBe(true); expect(compatibleFieldExpression("tc_criterion", expression)).toBe(false); expect(compatibleFieldExpression("lambda_eph", expression)).toBe(false); expect(compatibleFieldExpression("atomic_sites", expression)).toBe(false); });
  it("verifies preview and exact saved row while retaining original context and actor receipts", async () => { const request = await syntheticCaseRequest(), preview = await syntheticCaseReceipt(request), ref = fieldCaseRecovery(request, caseCap, preview.request_sha256); expect(await knownFieldCaseReceipt(preview, caseCap, ref, "preview")).toEqual(preview); const bound = { ...ref, previewSha: preview.preview_sha256, receiptSha: preview.receipt_sha256, receiptId: preview.receipt_id }, saved = { ...preview, dry_run: false, pending_ledger_written: true }; expect(await knownFieldCaseReceipt(saved, caseCap, bound, "commit")).toEqual(saved); expect(await knownFieldCaseReceipt({ ...saved, replayed: true }, { ...caseCap, session_version: 3, curator_grant_id: "00000000-0000-4000-8000-000000000998" }, bound, "outcome")).toEqual({ ...saved, replayed: true }); });
  it("rejects a fully rehashed changed outcome with original request/preview identity", async () => { const request = await syntheticCaseRequest(), preview = await syntheticCaseReceipt(request), ref = { ...fieldCaseRecovery(request, caseCap, preview.request_sha256), previewSha: preview.preview_sha256, receiptSha: preview.receipt_sha256, receiptId: preview.receipt_id }; const changed = { ...preview, replayed: true, dry_run: false, pending_ledger_written: true }, body = JSON.parse(changed.receipt_canonical_json); body.actor_grant_id = "00000000-0000-4000-8000-000000000999"; const p = JSON.parse(body.preview_json); p.actor.actor_grant_id = body.actor_grant_id; body.preview_json = expressionCanonical(p); body.preview_sha256 = await expressionSha(body.preview_json); changed.actor_grant_id = body.actor_grant_id; changed.preview_canonical_json = body.preview_json; changed.preview_sha256 = body.preview_sha256; changed.receipt_canonical_json = expressionCanonical(body); changed.receipt_sha256 = await expressionSha(changed.receipt_canonical_json); expect(await knownFieldCaseReceipt(changed, caseCap, ref, "outcome")).toBeNull(); expect(await knownFieldCaseReceipt({ ...preview, replayed: true, dry_run: false, pending_ledger_written: true }, caseCap, { ...ref, receiptSha: "" }, "outcome")).toBeNull(); });
  it("rejects coordinated non-target context, field and chain rewrites against the original verified target pins", async () => {
    const target = await syntheticCaseEntry();
    const requests: FieldCaseRequest[] = [
      { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:pending-attempt", operation: "attempt", payload: { target_id: target.id, target_sha256: target.record_sha256, outcome: "source_unavailable", reason_codes: ["source_unavailable"], checked_scope: { source_ids: [], fulltext_checked: false, supplement_checked: false, scope_label: "Unavailable source" }, expression_pins: [], predecessor: null } },
      { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:pending-association", operation: "association", payload: { target_id: target.id, target_sha256: target.record_sha256, expression_revision_id: "00000000-0000-4000-8000-000000000801", expression_record_sha256: "c".repeat(64), source_identity: { paper_id: null, work_id: null }, action: "propose", predecessor: null } }
    ];
    for (const request of requests) {
      const preview = await syntheticCaseReceipt(request), ref = fieldCaseRecovery(request, caseCap, preview.request_sha256, target, "b".repeat(64));
      expect(await knownFieldCaseReceipt(preview, caseCap, ref, "preview")).toEqual(preview);
      expect(await knownFieldCaseReceipt(preview, caseCap, fieldCaseRecovery(request, caseCap, preview.request_sha256), "preview")).toBeNull();
      for (const kind of ["context", "field", ...(request.operation === "association" ? ["chain"] : [])]) {
        const changed = structuredClone(preview), body = JSON.parse(changed.receipt_canonical_json);
        if (kind === "context") { body.context_json = body.context_json.replace("23.000", "24.000"); body.context_sha256 = await expressionSha(body.context_json); const p = JSON.parse(body.preview_json); p.context_sha256 = body.context_sha256; body.preview_json = expressionCanonical(p); body.preview_sha256 = await expressionSha(body.preview_json); changed.preview_canonical_json = body.preview_json; changed.preview_sha256 = body.preview_sha256; }
        if (kind === "field") body.field_id = "lambda_eph";
        if (kind === "chain") body.chain_key = "d".repeat(64);
        changed.receipt_canonical_json = expressionCanonical(body); changed.receipt_sha256 = await expressionSha(changed.receipt_canonical_json);
        expect(await knownFieldCaseReceipt(changed, caseCap, ref, "preview")).toBeNull();
      }
    }
  });
  it("binds exact detail to the originally listed target, rejecting coordinated different row", async () => { const detail = await syntheticCaseDetail(), other = await syntheticCaseDetail("lambda_eph"); expect(await knownFieldCaseDetail(detail, caseCap, detail.target)).toEqual(detail); expect(await knownFieldCaseDetail(other, caseCap, detail.target)).toBeNull(); });
  it("keeps returned, omitted, total and continuation distinct after a byte-bound trim", async () => { const page = await syntheticMaterialPage(); const trimmed = { ...page, total: 8, entries_omitted: 7, response_truncated: true, next_offset: 1 }; expect(await knownFieldCaseMaterial(trimmed, caseCap, caseMaterial, 0)).toEqual(trimmed); expect(await knownFieldCaseMaterial({ ...trimmed, next_offset: 8 }, caseCap, caseMaterial, 0)).toBeNull(); expect(await knownFieldCaseMaterial({ ...trimmed, entries: [], entries_returned: 0, entries_omitted: 8, next_offset: 0 }, caseCap, caseMaterial, 0)).toBeNull(); });
  it("refuses unexplained private source objects, extra rows and false population counts", async () => { const page = await syntheticMaterialPage(); expect(await knownFieldCaseMaterial({ ...page, private_notes: "hidden" }, caseCap, caseMaterial, 0)).toBeNull(); expect(await knownFieldCaseMaterial({ ...page, expressions_returned: 1 }, caseCap, caseMaterial, 0)).toBeNull(); const detail = await syntheticCaseDetail(); expect(await knownFieldCaseDetail({ ...detail, association_total: 1 }, caseCap)).toBeNull(); });
});
