import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiError, materialLiteralFieldCapabilities, materialLiteralFieldPrepare, sourceLiteralExpressionCapabilities, sourceLiteralExpressionList, sourceLiteralExpressionDetail, materialLiteralFieldCaseCapabilities, materialLiteralFieldCaseMaterial, materialLiteralFieldCaseDetail, sourceExpressionCapabilities, materialFieldCaseCapabilities, sourceExpressionCommit, sourceExpressionOutcome } from "@/lib/api";
import { LITERAL_PROFILE } from "@/lib/material-literal-fields";
afterEach(() => vi.unstubAllGlobals());
function fetcher() { const mock = vi.fn().mockImplementation(async () => new Response("{}", { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", mock); return mock; }
describe("Explicit raw-profile HTTP boundary", () => {
  it("uses explicit fixed raw profile for all source and case reads while preserving default URLs", async () => { const f = fetcher(); await sourceLiteralExpressionCapabilities(); await sourceLiteralExpressionList(8, 8, "t_sdw_k", "source:/exact?1"); await sourceLiteralExpressionDetail("uuid:/?1"); await materialLiteralFieldCaseCapabilities(); await materialLiteralFieldCaseMaterial("material:/exact?1", 8); await materialLiteralFieldCaseDetail("target:/?1"); for (const [url, options] of f.mock.calls) { expect(new URL(String(url), "https://example.invalid").searchParams.get("profile")).toBe(LITERAL_PROFILE); expect(options).toMatchObject({ credentials: "include", cache: "no-store" }); expect(options.body).toBeUndefined(); } const list = new URL(String(f.mock.calls[1][0]), "https://example.invalid").searchParams; expect(list.get("offset")).toBe("8"); expect(list.get("field_id")).toBe("t_sdw_k"); expect(list.get("source_id")).toBe("source:/exact?1"); await sourceExpressionCapabilities(); await materialFieldCaseCapabilities(); expect(String(f.mock.calls[6][0])).not.toContain("profile="); expect(String(f.mock.calls[7][0])).not.toContain("profile="); });
  it("prepares only explicit selector/pin JSON with credentialed no-store and abort support", async () => { const f = fetcher(), abort = new AbortController(), body = { version: "synthetic-pin-only", candidate_id: "synthetic:selector" }; await materialLiteralFieldCapabilities(abort.signal); await materialLiteralFieldPrepare(body, abort.signal); expect(f.mock.calls[1][1]).toMatchObject({ method: "POST", body: JSON.stringify(body), cache: "no-store", credentials: "include", signal: abort.signal }); });
  it("does not retry an unknown source save and recovers by original GET key/hash only", async () => { const f = fetcher(); f.mockResolvedValueOnce(new Response("{}", { status: 503 })); const body = { request_key: "synthetic:original/+1", package: {} } as Parameters<typeof sourceExpressionCommit>[0]; await expect(sourceExpressionCommit(body, "a".repeat(64))).rejects.toBeInstanceOf(ApiError); expect(f).toHaveBeenCalledOnce(); await sourceExpressionOutcome(body.request_key, "b".repeat(64)); const [url, options] = f.mock.calls[1]; expect(options.method).not.toBe("POST"); expect(options.body).toBeUndefined(); const query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("request_key")).toBe(body.request_key); expect(query.get("expected_request_sha256")).toBe("b".repeat(64)); });
  it("refuses a prepare response exceeding its 2 MiB bound before private rendering", async () => { const f = fetcher(); f.mockResolvedValueOnce(new Response(JSON.stringify({ source_text: "x".repeat(2*1024*1024+1) }), { status: 200, headers: { "content-type": "application/json" } })); await expect(materialLiteralFieldPrepare({})).rejects.toBeInstanceOf(ApiError); expect(f).toHaveBeenCalledOnce(); });
});
