import { webcrypto } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { expressionCanonical, expressionSha, knownExpressionCapabilities, prepareExpressionPackage } from "@/lib/source-expressions";
import { knownFieldCaseRequest, knownFieldCaseCapabilities } from "@/lib/material-field-cases";
import { LITERAL_READ_HOLD_REASONS, LITERAL_CASE_FIELDS, LITERAL_CASE_REQUEST_VERSION, compileLiteralPackage, knownLiteralPrepareCapabilities, knownLiteralSourceCapabilities, knownLiteralCaseCapabilities, knownLiteralCaseRequest, knownLiteralCaseContext, knownLiteralCaseDetail, knownLiteralPrepare, literalCandidates, literalPrepareRequest, knownLiteralSourceRevision, knownLiteralExpressionPage, literalExpressionRecovery, knownLiteralExpressionReceipt, literalCaseRecovery, knownLiteralCaseReceipt, knownLiteralStoredIdentity, knownLiteralStoredOutcome, readLiteralRecovery, storeLiteralRecovery, clearLiteralRecovery, literalRecoveryStorageKey, type LiteralCaseRequest } from "@/lib/material-literal-fields";
import { caseCap, syntheticCaseRequest } from "../helpers/material-field-case-test-data";
import { literalActor, literalFlags, literalCaseCap, literalSourceCap, literalPrepareCap, literalMaterial, literalContext, literalPackage, literalReport, literalPreparedResponse, literalRevision, literalSourceReceipt, literalCaseReceipt, literalDetail, literalPythonOracle, literalStorageFixture } from "../helpers/material-literal-field-test-data";
function mockSessionStorage(overrides: Partial<Storage>) {
  const original = window.sessionStorage;
  vi.spyOn(window, "sessionStorage", "get").mockReturnValue({
    get length() { return original.length; },
    clear: () => original.clear(), getItem: key => original.getItem(key), key: index => original.key(index),
    removeItem: key => original.removeItem(key), setItem: (key, value) => original.setItem(key, value), ...overrides,
  });
}
beforeEach(() => { sessionStorage.clear(); vi.stubGlobal("crypto", webcrypto); });
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });
describe("Opt-in literal field protocol", () => {
  it.each(literalPythonOracle.entries)("matches the independently compiled Python $field_id package and projection hashes", async oracle => { const actual = await compileLiteralPackage(oracle.package); expect(actual.packageSha).toBe(oracle.package_sha256); expect(actual.projections[0]).toEqual(oracle.projection); expect(await expressionSha(expressionCanonical(actual.projections[0]))).toBe(oracle.projection_sha256); });
  it.each(LITERAL_CASE_FIELDS)("keeps %s as original text with its fixed role, never a normalized quantity", async field => { const pkg = await literalPackage(field), p = await compileLiteralPackage(pkg); expect(p.projections[0].value.quantity).toBeNull(); expect(p.projections[0].value.normalization).toBe("none"); expect(p.projections[0].value.raw_value).toBe(Array.from(p.sourceText).slice(pkg.expressions[0].value_spans[0].start, pkg.expressions[0].unit_spans[0]?.end ?? pkg.expressions[0].value_spans[0].end).join("")); expect(p.projections[0].field_role).toBe(field === "maximum_applied_pressure_source_value" ? "study_extent" : field === "minimum_temperature_k" ? "measurement_limit" : ["t_cdw_k", "t_afm_k", "t_sdw_k"].includes(field) ? "reported_order_transition" : "reported_property"); });
  it("checks codepoint positions after a non-BMP character and preserves printed uncertainty", async () => { const pkg = await literalPackage(), p = await compileLiteralPackage(pkg); expect(p.projections[0].value.raw_value).toBe("0.590(5) meV"); expect(p.projections[0].value.raw_uncertainty).toBe("(5)"); expect(pkg.expressions[0].subject.formula_spans[0].start).toBe(20); });
  it.each(["role", "boundary", "condition", "uncertainty", "cue", "profile"])("refuses a rehashed or structurally plausible %s mutant", async mutant => { const pkg = await literalPackage(), entry = pkg.expressions[0]; if (mutant === "role") entry.field_role = "study_extent"; if (mutant === "boundary") { entry.window.label_spans[0].start = entry.value_spans[0].start; const raw = new TextDecoder().decode(Uint8Array.from(atob(pkg.source_text_base64), c => c.charCodeAt(0))); entry.window.label_spans[0].sha256 = await expressionSha(Array.from(raw).slice(entry.window.label_spans[0].start).join("")); } if (mutant === "condition") entry.conditions = [{ field_id: "pressure_gpa", role: "reported_result_condition", value_spans: entry.value_spans, unit_spans: [] }]; if (mutant === "uncertainty") entry.uncertainty_spans = entry.unit_spans; if (mutant === "cue") entry.cue_spans = entry.unit_spans; if (mutant === "profile") entry.profile = "source-expression-package/2.0.0"; await expect(compileLiteralPackage(pkg)).rejects.toThrow(); });
  it("does not reinterpret study limits as Tc conditions", async () => { const pkg = await literalPackage("maximum_applied_pressure_source_value"); pkg.expressions[0].field_role = "reported_result_condition"; await expect(compileLiteralPackage(pkg)).rejects.toThrow(); const min = await compileLiteralPackage(await literalPackage("minimum_temperature_k")); expect(min.projections[0].value.raw_value).toBe("50 mK"); expect(min.projections[0].conditions).toEqual([]); });
  it("rejects raw packages and capabilities on the unchanged numeric profile", async () => { const pkg = await literalPackage(); expect(knownExpressionCapabilities(literalSourceCap, literalActor)).toBeNull(); await expect(prepareExpressionPackage(new TextEncoder().encode(JSON.stringify(pkg)))).rejects.toThrow(); expect(knownLiteralSourceCapabilities(literalSourceCap, literalActor)).not.toBeNull(); });
  it("preserves old 24-field operations while opt-in advertises their unchanged versions plus 14 new fields", async () => { expect(knownFieldCaseCapabilities(caseCap, literalActor)).not.toBeNull(); expect(knownLiteralCaseCapabilities(literalCaseCap, literalActor)).not.toBeNull(); expect(knownLiteralPrepareCapabilities(literalPrepareCap, literalActor)).not.toBeNull(); expect(knownLiteralCaseRequest(await syntheticCaseRequest())).toBe(false); const c = await literalContext(); for (const field of LITERAL_CASE_FIELDS) { const request = { version: LITERAL_CASE_REQUEST_VERSION, request_key: "synthetic:raw", operation: "target", payload: { field_id: field, target: c.target } }; expect(knownLiteralCaseRequest(request)).toBe(true); expect(knownFieldCaseRequest(request)).toBe(false); } });
  it("rejects raw fields advertised under the old request version, extra roles or foreign sessions", async () => { const caps = structuredClone(literalCaseCap); caps.field_request_versions.minimum_temperature_k = "material-field-case-operation/1.0.0"; expect(knownLiteralCaseCapabilities(caps, literalActor)).toBeNull(); expect(knownLiteralSourceCapabilities({ ...literalSourceCap, field_profiles: { ...literalSourceCap.field_profiles, tc_kelvin: "reported_property" } }, literalActor)).toBeNull(); expect(knownLiteralPrepareCapabilities({ ...literalPrepareCap, field_cases: { ...literalCaseCap, actor_user_id: "00000000-0000-4000-8000-000000000909" } }, literalActor)).toBeNull(); });
  it("independently rereads original bytes and all value/unit/cue spans before accepting a prepared package", async () => { const c = await literalContext(), list = literalCandidates(await literalReport(), literalMaterial, c)!; const request = literalPrepareRequest(c, list[0]), response = await literalPreparedResponse(request); const validated = await knownLiteralPrepare(response, literalCaseCap, c, list[0], request); expect(validated?.verified.sourceText).toContain("Synthetic fixture 🙂 NbN gap energy"); expect(validated?.verified.projections[0].value.quantity).toBeNull(); expect(response.pending_ledger_written).toBe(false); expect(Object.keys(request).sort()).toEqual(literalPrepareCap.prepare_request_keys); });
  it.each(["unit", "candidate", "source", "record", "context", "rights", "role"])("withholds a changed prepared %s even when reported hashes are refreshed", async mutation => { const c = await literalContext(), candidate = literalCandidates(await literalReport(), literalMaterial, c)![0], request = literalPrepareRequest(c, candidate), response = await literalPreparedResponse(request); if (mutation === "unit") { const altered = structuredClone(candidate); altered.rawUnit = "eV"; expect(await knownLiteralPrepare(response, literalCaseCap, c, altered, request)).toBeNull(); return; } if (mutation === "candidate") response.pins.candidate_id = "enrichment:" + "b".repeat(64); if (mutation === "source") response.package.source_content_sha256 = "b".repeat(64); if (mutation === "record") response.pins.retained_record_sha256 = "b".repeat(64); if (mutation === "context") response.context_canonical_json += " "; if (mutation === "rights") response.source_origin.source_rights_verified = true as false; if (mutation === "role") { response.package.expressions[0].field_role = "study_extent"; const { source_text_base64: _source, ...retained } = response.package; response.package_sha256 = await expressionSha(expressionCanonical(retained)); } expect(await knownLiteralPrepare(response, literalCaseCap, c, candidate, request)).toBeNull(); });
  it("selects candidates only for the exact current retained result and forbids a public metadata source upload", async () => { const c = await literalContext(), other = await literalContext(literalMaterial, 1); expect(literalCandidates(await literalReport(), literalMaterial, other)).toEqual([]); expect(literalCandidates(await literalReport(), literalMaterial, { ...c, eligibility: { eligible: false, reason_codes: ["source_lifecycle_held"] } })).toBeNull(); await expect(compileLiteralPackage(await literalReport())).rejects.toThrow(); const report = await literalReport(); report.candidates[0].subject.identity_basis = "formula_alias"; expect(literalCandidates(report, literalMaterial, c)).toBeNull(); });
  it("pins source preview/save/recovery to the original full package and projection manifest", async () => { const p = await compileLiteralPackage(await literalPackage()), ref = literalExpressionRecovery(p, literalSourceCap, "synthetic:source"), preview = await literalSourceReceipt(p); expect(await knownLiteralExpressionReceipt(preview, literalSourceCap, ref, "preview", p)).not.toBeNull(); const savedRef = { ...ref, previewSha: preview.preview_sha256, manifestCanonical: expressionCanonical(preview.expression_manifest), receiptId: preview.receipt_id, receiptSha: preview.receipt_sha256, captureId: preview.capture_id }, saved = await literalSourceReceipt(p, "synthetic:source", false); saved.replayed = true; expect(await knownLiteralExpressionReceipt(saved, literalSourceCap, savedRef, "outcome", p)).not.toBeNull(); expect(await knownLiteralExpressionReceipt(saved, literalSourceCap, { ...savedRef, requestKey: "other" }, "outcome", p)).toBeNull(); });
  it.each(["receipt_id", "capture_id"] as const)("refuses an outcome with a rehashed alternate %s despite matching key/package/preview", async key => { const p = await compileLiteralPackage(await literalPackage()), preview = await literalSourceReceipt(p), ref = { ...literalExpressionRecovery(p, literalSourceCap, preview.request_key), previewSha: preview.preview_sha256, manifestCanonical: expressionCanonical(preview.expression_manifest), receiptId: preview.receipt_id, receiptSha: preview.receipt_sha256, captureId: preview.capture_id }, saved = await literalSourceReceipt(p, preview.request_key, false), body = JSON.parse(saved.receipt_canonical_json); saved.replayed = true; saved[key] = "00000000-0000-4000-8000-000000000909"; body[key === "receipt_id" ? "id" : key] = saved[key]; saved.receipt_canonical_json = expressionCanonical(body); saved.receipt_sha256 = await expressionSha(saved.receipt_canonical_json); expect(await knownLiteralExpressionReceipt(saved, literalSourceCap, ref, "outcome", p)).toBeNull(); });
  it("pins the raw target preview to its exact 1.1 context and keeps context endpoint 1.0", async () => { const c = await literalContext(); expect(await knownLiteralCaseContext(c, literalCaseCap, literalMaterial, "retained_result", 0, null)).not.toBeNull(); const request = { version: LITERAL_CASE_REQUEST_VERSION, request_key: "synthetic:literal-target", operation: "target" as const, payload: { field_id: "gap_energy_source_value", target: c.target } }, ref = literalCaseRecovery(request, literalCaseCap, await expressionSha(expressionCanonical(request))), receipt = await literalCaseReceipt(request); expect(await knownLiteralCaseReceipt(receipt, literalCaseCap, ref, "preview")).not.toBeNull(); expect(await knownLiteralCaseReceipt({ ...receipt, version: "material-field-case/1.0.0" }, literalCaseCap, ref, "preview")).toBeNull(); });
  it("validates compact and detailed source reads against their original window and import receipt", async () => { const compact = await literalRevision("gap_energy_source_value", "synthetic:source", false), detail = await literalRevision(); expect(await knownLiteralSourceRevision(compact)).not.toBeNull(); expect(await knownLiteralSourceRevision(detail, detail.id, detail.record_sha256)).not.toBeNull(); const page = { version: literalSourceCap.version, total: 1, offset: 0, limit: 8, count_scope: "current_pending_expression_heads_not_experiments_or_verified_properties", expressions: [compact], scientific_acceptance: false, canonical_promotions: 0 }; expect(await knownLiteralExpressionPage(page, 0, 8)).not.toBeNull(); });
  it("rejects a raw-unit projection mutant after every surrounding projection/revision hash is rehashed", async () => { const revision = await literalRevision("gap_energy_source_value", "synthetic:source", false); revision.projection.value.raw_unit = "eV"; revision.projection_canonical_json = expressionCanonical(revision.projection); revision.projection_sha256 = await expressionSha(revision.projection_canonical_json); const body = JSON.parse(revision.revision_canonical_json); body.projection_json = revision.projection_canonical_json; body.projection_sha256 = revision.projection_sha256; revision.revision_canonical_json = expressionCanonical(body); revision.record_sha256 = await expressionSha(revision.revision_canonical_json); expect(await knownLiteralSourceRevision(revision)).toBeNull(); });
  it("preserves a printed line break between an amount and unit in candidate selectors", async () => { const pkg = await literalPackage(), text = new TextDecoder().decode(Uint8Array.from(atob(pkg.source_text_base64), c => c.charCodeAt(0))).replace(" meV", "\nmeV"); pkg.source_text_base64 = btoa(String.fromCharCode(...new TextEncoder().encode(text))); pkg.source_content_sha256 = await expressionSha(text); pkg.expressions[0].window.label_spans[0].sha256 = await expressionSha(text); const p = await compileLiteralPackage(pkg); expect(p.projections[0].value.raw_value).toBe("0.590(5)\nmeV"); const c = await literalContext(), report = await literalReport(); report.candidates[0].source.content_sha256 = pkg.source_content_sha256; report.candidates[0].source_value.raw_value = p.projections[0].value.raw_value; expect(literalCandidates(report, literalMaterial, c)?.[0].rawValue).toBe("0.590(5)\nmeV"); });
  it("checks optional model text outside the value window without pretending the read DTO contains full capture bytes", async () => { const pkg = await literalPackage(), text = new TextDecoder().decode(Uint8Array.from(atob(pkg.source_text_base64), c => c.charCodeAt(0))), model = "Synthetic model", extended = text + " " + model, start = Array.from(text).length + 1; pkg.source_text_base64 = btoa(String.fromCharCode(...new TextEncoder().encode(extended))); pkg.source_content_sha256 = await expressionSha(extended); pkg.expressions[0].model_spans = [{ start, end: start+model.length, sha256: await expressionSha(model) }]; const revision = await literalRevision("gap_energy_source_value", "synthetic:source", true, pkg); expect(await knownLiteralSourceRevision(revision, revision.id, revision.record_sha256)).not.toBeNull(); });
  it.each(LITERAL_READ_HOLD_REASONS)("keeps %s pending history readable while withholding the expression and forbidding it as an attempt-write reason", async reason => { const d = await literalDetail(), expression = await literalRevision("gap_energy_source_value", "synthetic:source", false), request: LiteralCaseRequest = { version: LITERAL_CASE_REQUEST_VERSION, request_key: "synthetic:held-association", operation: "association", payload: { target_id: d.target.id, target_sha256: d.target.record_sha256, expression_revision_id: expression.id, expression_record_sha256: expression.record_sha256, source_identity: { paper_id: null, work_id: null }, action: "propose", predecessor: null } }, receipt = await literalCaseReceipt(request, false, "gap_energy_source_value", await literalContext(), expression); d.associations = [{ id: receipt.receipt_id, record_sha256: receipt.receipt_sha256, record_canonical_json: receipt.receipt_canonical_json, operation: "association", payload: request.payload, context_canonical_json: null, context_sha256: d.target.context_sha256, created_at: "2026-10-02T00:00:00Z", eligibility: { eligible: false, reason_codes: [reason] }, is_head: true, expression: null, source_identity_status: "proposed", ...literalFlags }]; d.association_total = 1; d.association_returned = 1; expect(await knownLiteralCaseDetail(d, literalCaseCap)).not.toBeNull(); expect(knownLiteralCaseRequest({ version: LITERAL_CASE_REQUEST_VERSION, request_key: "synthetic:attempt", operation: "attempt", payload: { target_id: d.target.id, target_sha256: d.target.record_sha256, outcome: "requires_interpretation", reason_codes: [reason], checked_scope: { source_ids: [], fulltext_checked: false, supplement_checked: false, scope_label: "Synthetic bounded scope" }, expression_pins: [], predecessor: null } })).toBe(false); d.associations[0].expression = expression; expect(await knownLiteralCaseDetail(d, literalCaseCap)).toBeNull(); });
});
describe("Actor-scoped minimal original-save identity", () => {
  it.each(["source", "case"] as const)("persists only %s pins and never source values, canonical requests or prepared packages", async kind => { const { identity } = await literalStorageFixture(kind); expect(storeLiteralRecovery(identity)).toBe(true); const raw = sessionStorage.getItem(literalRecoveryStorageKey(literalActor))!; expect(new TextEncoder().encode(raw).length).toBeLessThan(4096); expect(raw).not.toMatch(/0\.590|source_text|packageCanonical|requestCanonical|Synthetic fixture|payload|prepared/); expect(readLiteralRecovery(literalActor)).toEqual({ status: "pending", identity }); expect(readLiteralRecovery("00000000-0000-4000-8000-000000000909")).toEqual({ status: "empty" }); expect(storeLiteralRecovery(identity)).toBe(false); });
  it.each(["source", "case"] as const)("validates the exact original %s GET receipt without a retained draft or write grant", async kind => { const { identity, saved } = await literalStorageFixture(kind); const confirmed = await knownLiteralStoredOutcome(saved, literalActor, identity); expect(confirmed).toEqual({ kind, receiptId: identity.receiptId, receiptSha: identity.receiptSha, requestKey: identity.requestKey }); expect(Object.keys(confirmed!)).toHaveLength(4); expect(await knownLiteralStoredOutcome(saved, "00000000-0000-4000-8000-000000000909", identity)).toBeNull(); expect(await knownLiteralStoredOutcome({ ...saved, replayed: false }, literalActor, identity)).toBeNull(); });
  it.each(["source", "case"] as const)("refuses rehashed replacement %s receipts when the original receipt SHA is pinned", async kind => { const { identity, saved } = await literalStorageFixture(kind); const body = JSON.parse(saved.receipt_canonical_json); body.id = "00000000-0000-4000-8000-000000000909"; saved.receipt_id = body.id; saved.receipt_canonical_json = expressionCanonical(body); saved.receipt_sha256 = await expressionSha(saved.receipt_canonical_json); expect(await knownLiteralStoredOutcome(saved, literalActor, identity)).toBeNull(); });
  it.each(["source", "case"] as const)("accepts no extra keys, foreign actor, incomplete pins or unsupported versions in stored %s identities", async kind => { const { identity } = await literalStorageFixture(kind); for (const altered of [{ ...identity, payload: "private" }, { ...identity, actorId: "00000000-0000-4000-8000-000000000909" }, { ...identity, receiptSha: "a" }, { ...identity, version: "future" }, { ...identity, requestKey: " bad " }]) expect(knownLiteralStoredIdentity(altered, literalActor)).toBeNull(); });
  it("treats corrupt, duplicate-key, oversized and unavailable storage as blocked", async () => { const key = literalRecoveryStorageKey(literalActor); for (const raw of ["{broken", '{"version":"a","version":"b"}', "x".repeat(4097)]) { sessionStorage.setItem(key, raw); expect(readLiteralRecovery(literalActor)).toEqual({ status: "blocked" }); } vi.spyOn(window, "sessionStorage", "get").mockImplementation(() => { throw new Error("unavailable"); }); expect(readLiteralRecovery(literalActor)).toEqual({ status: "blocked" }); });
  it("requires successful storage and exact read-back before permitting a save identity", async () => { const { identity } = await literalStorageFixture("source"); mockSessionStorage({ setItem: () => { throw new Error("quota"); } }); expect(storeLiteralRecovery(identity)).toBe(false); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); });
  it("refuses a silent storage failure when exact read-back does not match the intended identity", async () => { const { identity } = await literalStorageFixture("source"); mockSessionStorage({ setItem: () => {} }); expect(storeLiteralRecovery(identity)).toBe(false); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); });
  it("clears only the exact same actor identity after independent verification and preserves a different pending identity", async () => { const { identity, saved } = await literalStorageFixture("case"); expect(storeLiteralRecovery(identity)).toBe(true); expect(clearLiteralRecovery({ ...identity, requestKey: "different" })).toBe(false); expect(readLiteralRecovery(literalActor).status).toBe("pending"); expect(await knownLiteralStoredOutcome(saved, literalActor, identity)).not.toBeNull(); expect(clearLiteralRecovery(identity)).toBe(true); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); });
});
