import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiError, materialFieldCaseCommit, materialFieldCaseContext, materialFieldCaseMaterial, materialFieldCaseOutcome } from "@/lib/api";
import { FIELD_CASE_REQUEST_VERSION, type FieldCaseRequest } from "@/lib/material-field-cases";
afterEach(() => vi.unstubAllGlobals());
describe("Private material field-case HTTP boundary", () => {
  it("uses credentialed no-store explicit reads with exact encoded material and selector", async () => { const fetcher = vi.fn().mockResolvedValue(new Response("{}", { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetcher); const controller = new AbortController(); await materialFieldCaseContext("material:/exact?1", "retained_result", 7, null, controller.signal); const [url, options] = fetcher.mock.calls[0]; const query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("material_id")).toBe("material:/exact?1"); expect(query.get("record_index")).toBe("7"); expect(query.has("entity_id")).toBe(false); expect(options).toMatchObject({ cache: "no-store", credentials: "include", signal: controller.signal }); expect(options.body).toBeUndefined(); });
  it("does not repeat an unknown POST and uses original GET identity for recovery", async () => { const fetcher = vi.fn().mockResolvedValueOnce(new Response("{}", { status: 503, headers: { "content-type": "application/json" } })).mockResolvedValueOnce(new Response("{}", { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetcher); const request: FieldCaseRequest = { version: FIELD_CASE_REQUEST_VERSION, request_key: "original:key/+1", operation: "target", payload: { field_id: "tc_kelvin", target: { kind: "retained_result", material_id: "exact", record_index: 0, entity_id: null, expected_context_sha256: "a".repeat(64) } } }; await expect(materialFieldCaseCommit(request, "b".repeat(64))).rejects.toBeInstanceOf(ApiError); expect(fetcher).toHaveBeenCalledOnce(); await materialFieldCaseOutcome(request.request_key, "c".repeat(64)); const [url, options] = fetcher.mock.calls[1]; expect(options.method).not.toBe("POST"); const query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("request_key")).toBe(request.request_key); expect(query.get("expected_request_sha256")).toBe("c".repeat(64)); expect(options.body).toBeUndefined(); });
  it("rejects an oversized adapter response before rendering or parsing private contents", async () => { const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ private_context: "x".repeat(2 * 1024 * 1024 + 1) }), { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", fetcher); await expect(materialFieldCaseMaterial("exact-material")).rejects.toBeInstanceOf(ApiError); expect(fetcher).toHaveBeenCalledOnce(); });
});
