import { webcrypto } from "node:crypto";
import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DashboardUserProvider } from "@/components/dashboard/user-context";
import { MaterialFieldCaseWorkbench } from "@/components/MaterialFieldCaseWorkbench";
import { ApiError, materialFieldCaseCapabilities, materialFieldCaseCommit, materialFieldCaseContext, materialFieldCaseDetail, materialFieldCaseMaterial, materialFieldCaseOutcome, materialFieldCasePreview, sourceExpressionDetail, sourceExpressionList, type User } from "@/lib/api";
import { notifyAuthChange } from "@/lib/auth-session";
import { expressionCanonical, expressionSha } from "@/lib/source-expressions";
import { FIELD_CASE_REQUEST_VERSION, type FieldCaseRequest } from "@/lib/material-field-cases";
import { caseActor, caseCap, caseFlags, caseMaterial, syntheticCaseContext, syntheticCaseDetail, syntheticCaseReceipt, syntheticMaterialPage } from "../helpers/material-field-case-test-data";
import { emptyExpressionPage, syntheticRevision } from "../helpers/source-expression-test-data";
vi.mock("@/lib/api", async original => ({ ...await original<typeof import("@/lib/api")>(), materialFieldCaseCapabilities: vi.fn(), materialFieldCaseCommit: vi.fn(), materialFieldCaseContext: vi.fn(), materialFieldCaseDetail: vi.fn(), materialFieldCaseMaterial: vi.fn(), materialFieldCaseOutcome: vi.fn(), materialFieldCasePreview: vi.fn(), sourceExpressionDetail: vi.fn(), sourceExpressionList: vi.fn() }));
const otherActor = "00000000-0000-4000-8000-000000000909";
const user = { id: caseActor, name: "Synthetic field operator", email: "operator@example.invalid", is_admin: false, is_reviewer: false } as User;
function view(material = caseMaterial, actor = caseActor) { return <DashboardUserProvider value={{ user: { ...user, id: actor }, setUser: vi.fn() }}><MaterialFieldCaseWorkbench initialMaterialId={material} /></DashboardUserProvider>; }
function deferred<T>() { let resolve!: (value: T) => void; return { promise: new Promise<T>(done => { resolve = done; }), resolve: (value: T) => resolve(value) }; }
async function mount() { const result = render(view()); await screen.findByText("Curator access"); return result; }
async function inspect() { fireEvent.click(screen.getByRole("button", { name: "Load material cases" })); await screen.findByRole("button", { name: "Inspect case" }); fireEvent.click(screen.getByRole("button", { name: "Inspect case" })); return screen.findByRole("region", { name: "Exact field case" }); }
async function previewTarget() { fireEvent.click(screen.getByRole("button", { name: "Load target context" })); await screen.findByRole("button", { name: "Preview field target" }); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); return screen.findByRole("button", { name: "Save pending operation" }); }
beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal("crypto", webcrypto); vi.mocked(materialFieldCaseCapabilities).mockResolvedValue(structuredClone(caseCap)); vi.mocked(materialFieldCaseMaterial).mockImplementation(async () => syntheticMaterialPage()); vi.mocked(materialFieldCaseContext).mockImplementation(async id => syntheticCaseContext(id)); vi.mocked(materialFieldCaseDetail).mockImplementation(async () => syntheticCaseDetail()); vi.mocked(materialFieldCasePreview).mockImplementation(async request => syntheticCaseReceipt(request)); vi.mocked(materialFieldCaseCommit).mockImplementation(async request => syntheticCaseReceipt(request, false)); vi.mocked(sourceExpressionList).mockResolvedValue(emptyExpressionPage()); });
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });
describe("Private exact material field cases", () => {
  it("waits for matching authenticated capability and explicit material load before private reads", async () => { const pending = deferred<unknown>(); vi.mocked(materialFieldCaseCapabilities).mockReturnValue(pending.promise); render(view()); expect(materialFieldCaseMaterial).not.toHaveBeenCalled(); expect(materialFieldCaseContext).not.toHaveBeenCalled(); await act(async () => pending.resolve(caseCap)); await screen.findByText("Curator access"); expect(materialFieldCaseMaterial).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Load material cases" })); await screen.findByRole("region", { name: "Bounded material cases" }); expect(vi.mocked(materialFieldCaseMaterial).mock.calls[0].slice(0, 2)).toEqual([caseMaterial, 0]); });
  it("rejects foreign capabilities and leaves default-disabled access unavailable", async () => { vi.mocked(materialFieldCaseCapabilities).mockResolvedValue({ ...caseCap, actor_user_id: otherActor }); render(view()); await screen.findByText(/response could not be verified/); expect(materialFieldCaseMaterial).not.toHaveBeenCalled(); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); vi.mocked(materialFieldCaseCapabilities).mockRejectedValueOnce(new ApiError(404, null, "disabled")); fireEvent.click(screen.getByRole("button", { name: "Refresh access" })); await screen.findByText(/interface, target or source is unavailable/); });
  it("permits a read-only actor to inspect returned cases while hiding all write surfaces", async () => { vi.mocked(materialFieldCaseCapabilities).mockResolvedValue({ ...caseCap, can_write: false, curator_grant_id: null }); render(view()); await screen.findByText("Read access"); await inspect(); expect(screen.queryByRole("region", { name: "Create exact field target" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Preview source check" })).not.toBeInTheDocument(); expect(materialFieldCasePreview).not.toHaveBeenCalled(); });
  it("requires explicit preview and exact save, with original unrounded target bytes", async () => { await mount(); await previewTarget(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); const request = vi.mocked(materialFieldCasePreview).mock.calls[0][0], expected = await syntheticCaseReceipt(request); expect(request.operation).toBe("target"); if (request.operation === "target") expect(request.payload.target.expected_context_sha256).toBe((await syntheticCaseContext()).context_sha256); expect(screen.getByText(/23\.000/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Saved pending operation" }); expect(vi.mocked(materialFieldCaseCommit).mock.calls[0].slice(0, 2)).toEqual([request, expected.preview_sha256]); expect(materialFieldCaseCommit).toHaveBeenCalledOnce(); });
  it("makes two exact retained record indices distinguishable before any write:23 onset versus21.5 zero resistance", async () => {
    vi.mocked(materialFieldCaseContext).mockImplementation(async (id, _kind, index) => {
      const context = await syntheticCaseContext(id), body = JSON.parse(context.context_canonical_json);
      body.record_index = index; body.result = { tc_kelvin: index === 0 ? 23 : 21.5, knowledge_origin: "Observed", tc_criterion: index === 0 ? "onset" : "zero_resistance" };
      context.context_canonical_json = JSON.stringify(body); context.context_sha256 = await expressionSha(context.context_canonical_json); context.target.record_index = index; context.target.expected_context_sha256 = context.context_sha256; context.closure.record_index = index; context.closure.paper_id = null;
      return context;
    });
    await mount(); fireEvent.click(screen.getByRole("button", { name: "Load target context" })); const first = await screen.findByRole("region", { name: "Retained target summary" }); expect(within(first).getByText("23")).toBeInTheDocument(); expect(within(first).getByText("onset")).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText("Retained record index"), { target: { value: "1" } }); expect(screen.queryByRole("region", { name: "Retained target summary" })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Load target context" })); const second = await screen.findByRole("region", { name: "Retained target summary" }); expect(within(second).getByText("21.5")).toBeInTheDocument(); expect(within(second).getByText("zero_resistance")).toBeInTheDocument(); expect(within(second).queryByText("23")).not.toBeInTheDocument(); expect(materialFieldCasePreview).not.toHaveBeenCalled();
  });
  it("invalidates preview when the scientific target field changes", async () => { await mount(); await previewTarget(); fireEvent.change(screen.getByLabelText("Scientific field"), { target: { value: "lambda_eph" } }); expect(screen.queryByRole("button", { name: "Save pending operation" })).not.toBeInTheDocument(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); });
  it("records unavailable scope without inventing a source expression or full-paper absence", async () => { await mount(); const region = await inspect(); fireEvent.change(within(region).getByLabelText("Checked scope"), { target: { value: "Abstract inspected; full text and supplement unavailable" } }); fireEvent.click(within(region).getByRole("button", { name: "Preview source check" })); await screen.findByRole("button", { name: "Save pending operation" }); const request = vi.mocked(materialFieldCasePreview).mock.calls[0][0]; expect(request.operation).toBe("attempt"); if (request.operation === "attempt") expect(request.payload.checked_scope).toEqual({ source_ids: [], fulltext_checked: false, supplement_checked: false, scope_label: "Abstract inspected; full text and supplement unavailable" }); expect(sourceExpressionList).not.toHaveBeenCalled(); });
  it("uses actual returned continuation after byte trimming without skipping omitted cases", async () => { const page = await syntheticMaterialPage(); vi.mocked(materialFieldCaseMaterial).mockResolvedValueOnce({ ...page, total: 8, next_offset: 1, entries_omitted: 7, response_truncated: true }).mockResolvedValueOnce({ ...page, total: 1, offset: 1, entries: [], entries_returned: 0 }); await mount(); fireEvent.click(screen.getByRole("button", { name: "Load material cases" })); await screen.findByRole("button", { name: "Next returned window" }); fireEvent.click(screen.getByRole("button", { name: "Next returned window" })); await waitFor(() => expect(vi.mocked(materialFieldCaseMaterial).mock.calls[1].slice(0, 2)).toEqual([caseMaterial, 1])); });
  it("keeps unsupported atomic-sites intake actionable as an attempt without fabricating expressions", async () => { vi.mocked(materialFieldCaseMaterial).mockResolvedValue(await syntheticMaterialPage(true, "atomic_sites")); vi.mocked(materialFieldCaseDetail).mockResolvedValue(await syntheticCaseDetail("atomic_sites")); await mount(); const region = await inspect(); expect(within(region).getByText(/does not support this field yet/)).toBeInTheDocument(); expect(within(region).getByRole("button", { name: "Preview source check" })).toBeInTheDocument(); expect(sourceExpressionList).not.toHaveBeenCalled(); });
  it("shows computed source value, uncertainty and ambient context without assigning it to target or 0 GPa", async () => { const revision = await syntheticRevision(), { version: _version, ...compact } = revision; compact.import_receipt = null; vi.mocked(sourceExpressionList).mockResolvedValue({ ...emptyExpressionPage(), total: 1, expressions: [compact] }); vi.mocked(sourceExpressionDetail).mockResolvedValue(revision); await mount(); const region = await inspect(); fireEvent.click(within(region).getByRole("button", { name: "Load compatible expressions" })); await screen.findByRole("button", { name: "Inspect source expression" }); fireEvent.click(screen.getByRole("button", { name: "Inspect source expression" })); await screen.findByRole("button", { name: "Preview source proposal" }); expect(screen.getByText(/Computed · ambient/)).toBeInTheDocument(); expect(screen.queryByText(/0 GPa/)).not.toBeInTheDocument(); expect(screen.getByLabelText("Proposed existing paper ID (optional)")).toHaveValue(""); expect(materialFieldCasePreview).not.toHaveBeenCalled(); });
  it("locks uncertain writes and recovers only original GET key/digests without retrying POST", async () => { await mount(); await previewTarget(); const request = vi.mocked(materialFieldCasePreview).mock.calls[0][0], saved = await syntheticCaseReceipt(request, false); saved.replayed = true; vi.mocked(materialFieldCaseCommit).mockRejectedValueOnce(new ApiError(503, null, "unknown")); vi.mocked(materialFieldCaseOutcome).mockRejectedValueOnce(new ApiError(404, null, "unavailable")).mockResolvedValueOnce(saved); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Original save recovery" }); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByText(/original outcome remains unverified/); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Saved pending operation" }); expect(materialFieldCaseCommit).toHaveBeenCalledOnce(); expect(vi.mocked(materialFieldCaseOutcome).mock.calls[0].slice(0, 2)).toEqual([request.request_key, await expressionSha(expressionCanonical(request))]); });
  it("bounds an unresponsive save even when a transport ignores cancellation, then uses GET recovery", async () => {
    await mount(); await previewTarget(); vi.useFakeTimers(); vi.mocked(materialFieldCaseCommit).mockReturnValue(new Promise(() => {}));
    try { fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await act(async () => { await vi.advanceTimersByTimeAsync(25001); }); expect(screen.getByRole("region", { name: "Original save recovery" })).toBeInTheDocument(); expect(materialFieldCaseCommit).toHaveBeenCalledOnce(); expect(materialFieldCaseOutcome).not.toHaveBeenCalled(); } finally { vi.useRealTimers(); }
  });
  it("does not resurrect an old material context after navigation to another exact ID", async () => { const late = deferred<unknown>(); vi.mocked(materialFieldCaseContext).mockReturnValue(late.promise); const rendered = await mount(); fireEvent.click(screen.getByRole("button", { name: "Load target context" })); rendered.rerender(view("synthetic-material:next")); await act(async () => late.resolve(await syntheticCaseContext())); expect(screen.getByLabelText("Material ID")).toHaveValue("synthetic-material:next"); expect(screen.queryByRole("button", { name: "Preview field target" })).not.toBeInTheDocument(); expect(screen.queryByText("synthetic-paper")).not.toBeInTheDocument(); });
  it("clears all private scope after auth notification and ignores late authenticated responses", async () => { const late = deferred<unknown>(); vi.mocked(materialFieldCaseMaterial).mockReturnValue(late.promise); await mount(); fireEvent.click(screen.getByRole("button", { name: "Load material cases" })); act(() => notifyAuthChange()); await act(async () => late.resolve(await syntheticMaterialPage())); expect(screen.queryByRole("region", { name: "Bounded material cases" })).not.toBeInTheDocument(); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); });
  it("offers withdrawal only for the actor's own current proposal, preserving held source history", async () => {
    const detail = await syntheticCaseDetail(), target = detail.target;
    const request: FieldCaseRequest = { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:held-proposal", operation: "association", payload: { target_id: target.id, target_sha256: target.record_sha256, expression_revision_id: "00000000-0000-4000-8000-000000000801", expression_record_sha256: "d".repeat(64), source_identity: { paper_id: "synthetic-paper", work_id: null }, action: "propose", predecessor: null } };
    const row = await syntheticCaseReceipt(request, false, target.context_canonical_json!, "00000000-0000-4000-8000-000000000802");
    detail.associations = [{ id: row.receipt_id, record_sha256: row.receipt_sha256, record_canonical_json: row.receipt_canonical_json, operation: "association", payload: request.payload, context_canonical_json: null, context_sha256: target.context_sha256, created_at: "2026-10-02T00:00:00Z", eligibility: { eligible: false, reason_codes: ["source_lifecycle_held"] }, is_head: true, expression: null, source_identity_status: "proposed", ...caseFlags }]; detail.association_total = 1; detail.association_returned = 1;
    vi.mocked(materialFieldCaseDetail).mockResolvedValue(detail); await mount(); const region = await inspect(); expect(within(region).getByText("Source lifecycle held", { selector: "p" })).toBeInTheDocument(); fireEvent.click(within(region).getByRole("button", { name: "Preview withdrawal of my proposal" })); await screen.findByRole("button", { name: "Save pending operation" }); const sent = vi.mocked(materialFieldCasePreview).mock.calls[0][0]; expect(sent.operation).toBe("association"); if (sent.operation === "association") expect(sent.payload).toMatchObject({ action: "withdraw", expression_revision_id: request.payload.expression_revision_id, predecessor: { id: row.receipt_id, record_sha256: row.receipt_sha256 } }); expect(materialFieldCaseCommit).not.toHaveBeenCalled();
  });
  it("never carries an unknown operation into another authenticated actor", async () => { const rendered = await mount(); await previewTarget(); vi.mocked(materialFieldCaseCommit).mockRejectedValueOnce(new ApiError(503, null, "unknown")); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Original save recovery" }); vi.mocked(materialFieldCaseCapabilities).mockResolvedValue({ ...caseCap, actor_user_id: otherActor }); rendered.rerender(view(caseMaterial, otherActor)); await screen.findByText("Curator access"); expect(screen.queryByRole("region", { name: "Original save recovery" })).not.toBeInTheDocument(); expect(materialFieldCaseOutcome).not.toHaveBeenCalled(); });
});
