import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiError, sourceTableExpressionCapabilities, sourceTableExpressionList, sourceTableExpressionDetail, materialTableFieldCaseCapabilities, materialTableFieldCaseMaterial, materialTableFieldCaseDetail, sourceExpressionCapabilities, materialFieldCaseCapabilities, sourceExpressionCommit, sourceExpressionOutcome } from "@/lib/api";
import { TABLE_PROFILE } from "@/lib/material-table-fields";
afterEach(() => vi.unstubAllGlobals());
function fetcher() { const mock = vi.fn().mockImplementation(async () => new Response("{}", { status: 200, headers: { "content-type": "application/json" } })); vi.stubGlobal("fetch", mock); return mock; }
describe("Explicit table-profile HTTP boundary", () => {
  it("uses explicit fixed table profile for all source and case reads while preserving default URLs", async () => { const f = fetcher(); await sourceTableExpressionCapabilities(); await sourceTableExpressionList(8, 8, "debye_temperature_source_value", "source:/exact?1"); await sourceTableExpressionDetail("uuid:/?1"); await materialTableFieldCaseCapabilities(); await materialTableFieldCaseMaterial("material:/exact?1", 8); await materialTableFieldCaseDetail("target:/?1"); for (const [url, options] of f.mock.calls) { expect(new URL(String(url), "https://example.invalid").searchParams.get("profile")).toBe(TABLE_PROFILE); expect(options).toMatchObject({ credentials: "include", cache: "no-store" }); expect(options.body).toBeUndefined(); } const list = new URL(String(f.mock.calls[1][0]), "https://example.invalid").searchParams; expect(list.get("offset")).toBe("8"); expect(list.get("field_id")).toBe("debye_temperature_source_value"); expect(list.get("source_id")).toBe("source:/exact?1"); await sourceExpressionCapabilities(); await materialFieldCaseCapabilities(); expect(String(f.mock.calls[6][0])).not.toContain("profile="); expect(String(f.mock.calls[7][0])).not.toContain("profile="); });
  it("does not retry an unknown source save and recovers by original GET key/hash only", async () => { const f = fetcher(); f.mockResolvedValueOnce(new Response("{}", { status: 503 })); const body = { request_key: "synthetic:original/+1", package: {} } as Parameters<typeof sourceExpressionCommit>[0]; await expect(sourceExpressionCommit(body, "a".repeat(64))).rejects.toBeInstanceOf(ApiError); expect(f).toHaveBeenCalledOnce(); await sourceExpressionOutcome(body.request_key, "b".repeat(64)); const [url, options] = f.mock.calls[1]; expect(options.method).not.toBe("POST"); expect(options.body).toBeUndefined(); const query = new URL(String(url), "https://example.invalid").searchParams; expect(query.get("request_key")).toBe(body.request_key); expect(query.get("expected_request_sha256")).toBe("b".repeat(64)); });
});
