import { webcrypto } from "node:crypto";
import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DashboardUserProvider } from "@/components/dashboard/user-context";
import { MaterialLiteralFieldWorkbench } from "@/components/MaterialLiteralFieldWorkbench";
import { ApiError, getMaterialEnrichment, materialLiteralFieldCapabilities, materialLiteralFieldPrepare, sourceLiteralExpressionCapabilities, materialFieldCaseContext, materialFieldCasePreview, materialFieldCaseCommit, materialFieldCaseOutcome, sourceExpressionPreview, sourceExpressionCommit, sourceExpressionOutcome, sourceLiteralExpressionList, sourceLiteralExpressionDetail, materialLiteralFieldCaseMaterial, materialLiteralFieldCaseDetail, type User } from "@/lib/api";
import { notifyAuthChange } from "@/lib/auth-session";
import { expressionCanonical, expressionSha } from "@/lib/source-expressions";
import { LITERAL_CASE_FIELDS, compileLiteralPackage, literalRecoveryStorageKey, readLiteralRecovery, storeLiteralRecovery, type LiteralPrepareRequest } from "@/lib/material-literal-fields";
import { literalActor, literalFlags, literalMaterial, literalCaseCap, literalSourceCap, literalPrepareCap, literalContext, literalReport, literalPreparedResponse, literalSourceReceipt, literalCaseReceipt, literalRevision, literalDetail, emptyLiteralSources, literalStorageFixture } from "../helpers/material-literal-field-test-data";
vi.mock("@/lib/api", async original => ({ ...await original<typeof import("@/lib/api")>(), getMaterialEnrichment: vi.fn(), materialLiteralFieldCapabilities: vi.fn(), materialLiteralFieldPrepare: vi.fn(), sourceLiteralExpressionCapabilities: vi.fn(), materialFieldCaseContext: vi.fn(), materialFieldCasePreview: vi.fn(), materialFieldCaseCommit: vi.fn(), materialFieldCaseOutcome: vi.fn(), sourceExpressionPreview: vi.fn(), sourceExpressionCommit: vi.fn(), sourceExpressionOutcome: vi.fn(), sourceLiteralExpressionList: vi.fn(), sourceLiteralExpressionDetail: vi.fn(), materialLiteralFieldCaseMaterial: vi.fn(), materialLiteralFieldCaseDetail: vi.fn() }));
const user = { id: literalActor, name: "Synthetic literal curator", email: "curator@example.invalid", is_admin: false, is_reviewer: false } as User;
let sourceKey = "synthetic:source";
function view(material = literalMaterial, field = "gap_energy_source_value", actor = literalActor) { return <DashboardUserProvider value={{ user: { ...user, id: actor }, setUser: vi.fn() }}><MaterialLiteralFieldWorkbench initialMaterialId={material} initialField={field} /></DashboardUserProvider>; }
function deferred<T>() { let resolve!: (value: T) => void; return { promise: new Promise<T>(done => { resolve = done; }), resolve: (value: T) => resolve(value) }; }
async function mount(field = "gap_energy_source_value") { const rendered = render(view(literalMaterial, field)); await screen.findByText("Curator access"); return rendered; }
async function load() { fireEvent.click(screen.getByRole("button", { name: "Load record and candidates" })); await screen.findByRole("button", { name: "Prepare original source" }); }
async function prepare() { await load(); fireEvent.click(screen.getByRole("button", { name: "Prepare original source" })); return screen.findByRole("region", { name: "Verified original source" }); }
async function previewSource() { await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview source import" })); return screen.findByRole("button", { name: "Save pending operation" }); }
async function saveSource() { await previewSource(); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Saved pending operation" }); }
async function inspectSource() { fireEvent.click(screen.getByRole("button", { name: "Load saved source expression" })); await screen.findByRole("button", { name: "Inspect source expression" }); fireEvent.click(screen.getByRole("button", { name: "Inspect source expression" })); await waitFor(() => expect(sourceLiteralExpressionDetail).toHaveBeenCalledOnce()); await within(screen.getByRole("region", { name: "Current literal source heads" })).findByText("Gap energy: 0.590(5) meV", { selector: "p" }); await waitFor(() => expect(screen.getByRole("button", { name: "Preview field target" })).toBeEnabled()); }
async function pendingSave(kind: "source" | "case", error = new ApiError(503, null, "unknown")) {
  if (kind === "source") { await previewSource(); const request = vi.mocked(sourceExpressionPreview).mock.calls.at(-1)![0], saved = await literalSourceReceipt(await compileLiteralPackage(request.package), request.request_key, false); saved.replayed = true; vi.mocked(sourceExpressionCommit).mockRejectedValueOnce(error); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); return { key: request.request_key, sha: saved.request_sha256, saved }; }
  await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); const request = vi.mocked(materialFieldCasePreview).mock.calls.at(-1)![0], saved = await literalCaseReceipt(request, false); saved.replayed = true; vi.mocked(materialFieldCaseCommit).mockRejectedValueOnce(error); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); return { key: request.request_key, sha: saved.request_sha256, saved };
}
function setActorAccess(actor: string, readOnly = false, session = 2) { vi.mocked(materialLiteralFieldCapabilities).mockResolvedValue({ ...literalPrepareCap, field_cases: { ...literalCaseCap, actor_user_id: actor, session_version: session, can_write: !readOnly, curator_grant_id: readOnly ? null : literalCaseCap.curator_grant_id } }); vi.mocked(sourceLiteralExpressionCapabilities).mockResolvedValue({ ...literalSourceCap, actor_user_id: actor, session_version: session, can_import: !readOnly, curator_grant_id: readOnly ? null : literalSourceCap.curator_grant_id }); }
function mockSessionStorage(overrides: Partial<Storage>) {
  const original = window.sessionStorage;
  vi.spyOn(window, "sessionStorage", "get").mockReturnValue({
    get length() { return original.length; },
    clear: () => original.clear(), getItem: key => original.getItem(key), key: index => original.key(index),
    removeItem: key => original.removeItem(key), setItem: (key, value) => original.setItem(key, value), ...overrides,
  });
}
beforeEach(() => {
  vi.resetAllMocks(); sessionStorage.clear(); vi.stubGlobal("crypto", webcrypto); sourceKey = "synthetic:source";
  vi.mocked(materialLiteralFieldCapabilities).mockResolvedValue(structuredClone(literalPrepareCap)); vi.mocked(sourceLiteralExpressionCapabilities).mockResolvedValue(structuredClone(literalSourceCap));
  vi.mocked(materialFieldCaseContext).mockImplementation(async (id, _kind, index) => literalContext(id, index ?? 0)); vi.mocked(getMaterialEnrichment).mockImplementation(async () => literalReport());
  vi.mocked(materialLiteralFieldPrepare).mockImplementation(async request => literalPreparedResponse(request as LiteralPrepareRequest));
  vi.mocked(sourceExpressionPreview).mockImplementation(async request => { sourceKey = request.request_key; return literalSourceReceipt(await compileLiteralPackage(request.package), sourceKey); });
  vi.mocked(sourceExpressionCommit).mockImplementation(async request => literalSourceReceipt(await compileLiteralPackage(request.package), request.request_key, false));
  vi.mocked(sourceLiteralExpressionList).mockImplementation(async () => ({ ...emptyLiteralSources(), total: 1, expressions: [await literalRevision("gap_energy_source_value", sourceKey, false)] })); vi.mocked(sourceLiteralExpressionDetail).mockImplementation(async () => literalRevision("gap_energy_source_value", sourceKey));
  vi.mocked(materialFieldCasePreview).mockImplementation(async request => literalCaseReceipt(request, true, "gap_energy_source_value", undefined, await literalRevision("gap_energy_source_value", sourceKey))); vi.mocked(materialFieldCaseCommit).mockImplementation(async request => literalCaseReceipt(request, false, "gap_energy_source_value", undefined, await literalRevision("gap_energy_source_value", sourceKey)));
  vi.mocked(materialLiteralFieldCaseDetail).mockImplementation(async () => literalDetail());
  vi.mocked(materialLiteralFieldCaseMaterial).mockResolvedValue({ version: literalCaseCap.version, actor_user_id: literalActor, session_version: 2, material_id: literalMaterial, total: 0, offset: 0, limit: 8, next_offset: null, entries: [], eligibility: { eligible: true, reason_codes: [] }, expressions_returned: 0, expressions_omitted: 0, entries_returned: 0, entries_omitted: 0, response_truncated: false, ...literalFlags });
});
describe("Persistent minimal original-save recovery", () => {
  it.each(["source", "case"] as const)("restores %s GET identity after same-actor unmount/remount without a payload or automatic POST", async kind => {
    const rendered = await mount(), original = await pendingSave(kind); await screen.findByRole("region", { name: "Original save recovery" }); const stored = sessionStorage.getItem(literalRecoveryStorageKey(literalActor))!; expect(stored).not.toMatch(/0\.590|Synthetic fixture|packageCanonical|requestCanonical|source_text|payload|prepared/); rendered.unmount(); render(view()); await screen.findByRole("region", { name: "Original save recovery" }); expect(sourceExpressionOutcome).not.toHaveBeenCalled(); expect(materialFieldCaseOutcome).not.toHaveBeenCalled(); expect(sourceExpressionCommit).toHaveBeenCalledTimes(kind === "source" ? 1 : 0); expect(materialFieldCaseCommit).toHaveBeenCalledTimes(kind === "case" ? 1 : 0);
    const outcome = kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome; vi.mocked(outcome).mockResolvedValueOnce(original.saved); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(vi.mocked(outcome).mock.calls.at(-1)!.slice(0, 2)).toEqual([original.key, original.sha]); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Load saved field target" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Load saved source expression" })).not.toBeInTheDocument();
  });
  it.each(["source", "case"] as const)("keeps %s pins scoped to A across A → B → A and permits only original GET recovery", async kind => {
    const rendered = await mount(), original = await pendingSave(kind); await screen.findByRole("region", { name: "Original save recovery" }); const b = "00000000-0000-4000-8000-000000000909"; setActorAccess(b); rendered.rerender(view(literalMaterial, "gap_energy_source_value", b)); await screen.findByText("Curator access"); expect(screen.queryByRole("region", { name: "Original save recovery" })).not.toBeInTheDocument(); expect(screen.queryByText(original.key)).not.toBeInTheDocument(); expect(readLiteralRecovery(literalActor).status).toBe("pending"); expect(readLiteralRecovery(b)).toEqual({ status: "empty" }); setActorAccess(literalActor); rendered.rerender(view()); await screen.findByRole("region", { name: "Original save recovery" }); const outcome = kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome; vi.mocked(outcome).mockResolvedValueOnce(original.saved); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(vi.mocked(outcome).mock.calls.at(-1)!.slice(0, 2)).toEqual([original.key, original.sha]); expect(sourceExpressionCommit).toHaveBeenCalledTimes(kind === "source" ? 1 : 0); expect(materialFieldCaseCommit).toHaveBeenCalledTimes(kind === "case" ? 1 : 0);
  });
  it.each(["source", "case"] as const)("retains %s identity through a 401 and recovers with read-only access and a new session", async kind => {
    await mount(); const original = await pendingSave(kind, new ApiError(401, null, "session changed")); await screen.findByText(/original save identity remains stored for GET recovery/); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); expect(readLiteralRecovery(literalActor).status).toBe("pending"); setActorAccess(literalActor, true, 3); fireEvent.click(screen.getByRole("button", { name: "Refresh access" })); await screen.findByRole("region", { name: "Original save recovery" }); expect(screen.getByText("Read access")).toBeInTheDocument(); const outcome = kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome; vi.mocked(outcome).mockResolvedValueOnce(original.saved); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); expect(sourceExpressionCommit).toHaveBeenCalledTimes(kind === "source" ? 1 : 0); expect(materialFieldCaseCommit).toHaveBeenCalledTimes(kind === "case" ? 1 : 0); expect(screen.queryByRole("button", { name: "Prepare original source" })).not.toBeInTheDocument();
  });
  it.each(["source", "case"] as const)("does not erase the original %s pins when a commit response arrives after an auth notification", async kind => {
    await mount(); if (kind === "source") await previewSource(); else { await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); }
    const late = deferred<unknown>(), request = kind === "source" ? vi.mocked(sourceExpressionPreview).mock.calls.at(-1)![0] : vi.mocked(materialFieldCasePreview).mock.calls.at(-1)![0], saved = kind === "source" ? await literalSourceReceipt(await compileLiteralPackage((request as Parameters<typeof sourceExpressionPreview>[0]).package), request.request_key, false) : await literalCaseReceipt(request as Parameters<typeof materialFieldCasePreview>[0], false); vi.mocked(kind === "source" ? sourceExpressionCommit : materialFieldCaseCommit).mockReturnValueOnce(late.promise); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await waitFor(() => expect(readLiteralRecovery(literalActor).status).toBe("pending")); act(() => notifyAuthChange()); await act(async () => late.resolve(saved)); expect(readLiteralRecovery(literalActor).status).toBe("pending"); expect(screen.queryByRole("region", { name: "Saved pending operation" })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Refresh access" })); await screen.findByRole("region", { name: "Original save recovery" }); saved.replayed = true; const outcome = kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome; vi.mocked(outcome).mockResolvedValueOnce(saved); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" });
  });
  it.each(["source", "case"] as const)("ignores a late %s GET from A after switching to B and leaves A's identity intact", async kind => {
    const { identity, saved } = await literalStorageFixture(kind); expect(storeLiteralRecovery(identity)).toBe(true); const rendered = render(view()); await screen.findByRole("region", { name: "Original save recovery" }); const late = deferred<unknown>(), outcome = kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome; vi.mocked(outcome).mockReturnValueOnce(late.promise); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); const b = "00000000-0000-4000-8000-000000000909"; setActorAccess(b); rendered.rerender(view(literalMaterial, "gap_energy_source_value", b)); await screen.findByText("Curator access"); await act(async () => late.resolve(saved)); expect(screen.queryByRole("region", { name: "Original receipt confirmed" })).not.toBeInTheDocument(); expect(screen.queryByText(identity.requestKey)).not.toBeInTheDocument(); expect(readLiteralRecovery(literalActor).status).toBe("pending"); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled();
  });
  it.each(["source", "case"] as const)("does not send a %s POST when its minimal identity cannot be stored", async kind => { await mount(); if (kind === "source") await previewSource(); else { await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); } mockSessionStorage({ setItem: () => { throw new Error("quota"); } }); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByText(/No save was sent; pending writes are blocked/); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); expect(screen.queryByRole("button", { name: "Save pending operation" })).not.toBeInTheDocument(); });
  it.each(["source", "case"] as const)("does not send a %s POST when storage silently drops its minimal identity", async kind => { await mount(); if (kind === "source") await previewSource(); else { await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); } mockSessionStorage({ setItem: () => {} }); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByText(/No save was sent; pending writes are blocked/); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); expect(readLiteralRecovery(literalActor)).toEqual({ status: "empty" }); });
  it("blocks writes when recovery storage is corrupt and never treats it as an empty ledger", async () => { sessionStorage.setItem(literalRecoveryStorageKey(literalActor), '{"unexpected":"private payload"}'); await mount(); await screen.findByText(/Recovery storage is unavailable or damaged/); fireEvent.click(screen.getByRole("button", { name: "Load record and candidates" })); await screen.findByText("0.590(5) meV", { selector: "p" }); expect(screen.queryByRole("button", { name: "Prepare original source" })).not.toBeInTheDocument(); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); expect(sessionStorage.getItem(literalRecoveryStorageKey(literalActor))).toBe('{"unexpected":"private payload"}'); });
  it("blocks writes when recovery storage is unavailable without exposing private fragments", async () => { vi.spyOn(window, "sessionStorage", "get").mockImplementation(() => { throw new Error("unavailable"); }); await mount(); await screen.findByText(/Recovery storage is unavailable or damaged/); expect(materialLiteralFieldPrepare).not.toHaveBeenCalled(); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); });
  it.each(["source", "case"] as const)("keeps %s recovery held if the verified original identity cannot be cleared", async kind => { const { identity, saved } = await literalStorageFixture(kind); expect(storeLiteralRecovery(identity)).toBe(true); render(view()); await screen.findByRole("region", { name: "Original save recovery" }); vi.mocked(kind === "source" ? sourceExpressionOutcome : materialFieldCaseOutcome).mockResolvedValueOnce(saved); mockSessionStorage({ removeItem: () => { throw new Error("unavailable"); } }); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(screen.getByRole("region", { name: "Original save recovery" })).toBeInTheDocument(); await screen.findByText(/stored identity could not be cleared/); expect(readLiteralRecovery(literalActor).status).toBe("pending"); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); });
});
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); });
describe("Private raw-literal field workbench", () => {
  it("waits for matching authenticated capabilities and explicit scope selection before candidate or source reads", async () => { const pending = deferred<unknown>(); vi.mocked(materialLiteralFieldCapabilities).mockReturnValue(pending.promise); render(view()); expect(getMaterialEnrichment).not.toHaveBeenCalled(); expect(materialFieldCaseContext).not.toHaveBeenCalled(); await act(async () => pending.resolve(literalPrepareCap)); await screen.findByText("Curator access"); expect(sourceLiteralExpressionList).not.toHaveBeenCalled(); expect(screen.getByLabelText("Scientific field")).toContainHTML("Spin density wave transition"); expect(screen.getAllByRole("option")).toHaveLength(14); });
  it("loads distinct exact retained records before considering a matching candidate", async () => { await mount(); await load(); expect(screen.getByText("onset")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Retained record index"), { target: { value: "1" } }); expect(screen.queryByRole("button", { name: "Prepare original source" })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Load record and candidates" })); await screen.findByText("zero_resistance"); expect(screen.getByText("21.5")).toBeInTheDocument(); await screen.findByText(/No matching candidate in the returned source scope/); expect(materialLiteralFieldPrepare).not.toHaveBeenCalled(); });
  it("performs read-only preparation and independently verifies original bytes before presenting any preview", async () => { await mount(); const prepared = await prepare(); expect(within(prepared).getByText("Gap energy: 0.590(5) meV")).toBeInTheDocument(); expect(within(prepared).getByText(/Original printed unit/)).toBeInTheDocument(); expect(materialLiteralFieldPrepare).toHaveBeenCalledOnce(); const request = vi.mocked(materialLiteralFieldPrepare).mock.calls[0][0] as LiteralPrepareRequest; expect(request.retained_result_id).toBe("synthetic-retained-0"); expect(request.retained_record_sha256).toBe("a".repeat(64)); expect(Object.keys(request)).not.toContain("source_text_base64"); expect(sourceExpressionPreview).not.toHaveBeenCalled(); expect(sourceExpressionCommit).not.toHaveBeenCalled(); expect(materialFieldCasePreview).not.toHaveBeenCalled(); });
  it("supports the full original source, exact target and matching pending association flow with separate preview/save steps", async () => {
    await mount(); await previewSource(); expect(sourceExpressionCommit).not.toHaveBeenCalled(); const sourceRequest = vi.mocked(sourceExpressionPreview).mock.calls[0][0], sourcePreview = await literalSourceReceipt(await compileLiteralPackage(sourceRequest.package), sourceRequest.request_key);
    fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Saved pending operation" }); expect(vi.mocked(sourceExpressionCommit).mock.calls[0].slice(0, 2)).toEqual([sourceRequest, sourcePreview.preview_sha256]); await inspectSource();
    fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); expect(materialFieldCaseCommit).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("button", { name: "Load saved field target" }); fireEvent.click(screen.getByRole("button", { name: "Load saved field target" })); await screen.findByRole("button", { name: "Preview matching source proposal" });
    fireEvent.click(screen.getByRole("checkbox", { name: "Propose the retained paper ID as a source link" })); fireEvent.click(screen.getByRole("button", { name: "Preview matching source proposal" })); await screen.findByRole("button", { name: "Save pending operation" }); const association = vi.mocked(materialFieldCasePreview).mock.calls[1][0]; expect(association.version).toBe("material-field-case-operation/1.1.0"); expect(association.operation).toBe("association"); if (association.operation === "association") expect(association.payload).toMatchObject({ source_identity: { paper_id: "synthetic-paper", work_id: null }, action: "propose", predecessor: null, expression_revision_id: "00000000-0000-4000-8000-000000000701" }); expect(materialFieldCaseCommit).toHaveBeenCalledOnce(); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByText(/pending association was saved/); expect(sourceExpressionCommit).toHaveBeenCalledOnce(); expect(materialFieldCaseCommit).toHaveBeenCalledTimes(2);
  });
  it("clears the exact source preview when the field changes without reusing the write key", async () => { await mount(); await previewSource(); fireEvent.change(screen.getByLabelText("Scientific field"), { target: { value: "minimum_temperature_k" } }); expect(screen.queryByRole("button", { name: "Save pending operation" })).not.toBeInTheDocument(); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(sourceExpressionCommit).not.toHaveBeenCalled(); });
  it("shows a study pressure limit without assigning it to Tc conditions", async () => { vi.mocked(getMaterialEnrichment).mockImplementation(async () => literalReport("maximum_applied_pressure_source_value")); vi.mocked(materialLiteralFieldPrepare).mockImplementation(async request => literalPreparedResponse(request as LiteralPrepareRequest, "maximum_applied_pressure_source_value")); await mount("maximum_applied_pressure_source_value"); const region = await prepare(); expect(within(region).getByText("Maximum applied pressure: 50.8 GPa")).toBeInTheDocument(); expect(within(region).getByText(/Study extent/)).toBeInTheDocument(); expect(screen.queryByText(/Reported result condition/)).not.toBeInTheDocument(); });
  it("hides write surfaces for read-only actors while allowing bounded source/case inspection", async () => { vi.mocked(materialLiteralFieldCapabilities).mockResolvedValue({ ...literalPrepareCap, field_cases: { ...literalCaseCap, can_write: false, curator_grant_id: null } }); vi.mocked(sourceLiteralExpressionCapabilities).mockResolvedValue({ ...literalSourceCap, can_import: false, curator_grant_id: null }); render(view()); await screen.findByText("Read access"); fireEvent.click(screen.getByRole("button", { name: "Load record and candidates" })); await screen.findByText("0.590(5) meV", { selector: "p" }); expect(screen.queryByRole("button", { name: "Prepare original source" })).not.toBeInTheDocument(); expect(screen.getByRole("button", { name: "Load current expressions" })).toBeInTheDocument(); expect(materialLiteralFieldPrepare).not.toHaveBeenCalled(); });
  it("withholds prepare after a changed original unit even when the package hash looks plausible", async () => { vi.mocked(materialLiteralFieldPrepare).mockImplementation(async request => { const response = await literalPreparedResponse(request as LiteralPrepareRequest); response.package.expressions[0].field_role = "measurement_limit"; return response; }); await mount(); await load(); fireEvent.click(screen.getByRole("button", { name: "Prepare original source" })); await screen.findByText(/original source proof could not be verified/); expect(screen.queryByRole("button", { name: "Preview source import" })).not.toBeInTheDocument(); expect(sourceExpressionPreview).not.toHaveBeenCalled(); });
  it("keeps an unknown source save locked and recovers only the original GET key/hash without repeating POST", async () => {
    await mount(); await previewSource(); const request = vi.mocked(sourceExpressionPreview).mock.calls[0][0], saved = await literalSourceReceipt(await compileLiteralPackage(request.package), request.request_key, false); saved.replayed = true;
    vi.mocked(sourceExpressionCommit).mockRejectedValueOnce(new ApiError(503, null, "unknown")); vi.mocked(sourceExpressionOutcome).mockRejectedValueOnce(new ApiError(404, null, "unavailable")).mockResolvedValueOnce(saved);
    fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Original save recovery" }); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByText(/original outcome remains unverified/); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(sourceExpressionCommit).toHaveBeenCalledOnce(); expect(vi.mocked(sourceExpressionOutcome).mock.calls[0].slice(0, 2)).toEqual([request.request_key, saved.request_sha256]);
  });
  it("bounds an unresponsive save, retains original recovery and never guesses rollback", async () => { await mount(); await previewSource(); vi.useFakeTimers(); vi.mocked(sourceExpressionCommit).mockReturnValue(new Promise(() => {})); try { fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await act(async () => { await vi.advanceTimersByTimeAsync(25001); }); expect(screen.getByRole("region", { name: "Original save recovery" })).toBeInTheDocument(); expect(sourceExpressionCommit).toHaveBeenCalledOnce(); expect(sourceExpressionOutcome).not.toHaveBeenCalled(); } finally { vi.useRealTimers(); } });
  it("recovers an unknown target save via field-case GET without repeating its POST", async () => { await mount(); await prepare(); fireEvent.click(screen.getByRole("button", { name: "Preview field target" })); await screen.findByRole("button", { name: "Save pending operation" }); const request = vi.mocked(materialFieldCasePreview).mock.calls[0][0], saved = await literalCaseReceipt(request, false); saved.replayed = true; vi.mocked(materialFieldCaseCommit).mockRejectedValueOnce(new ApiError(503, null, "unknown")); vi.mocked(materialFieldCaseOutcome).mockResolvedValueOnce(saved); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Original save recovery" }); fireEvent.click(screen.getByRole("button", { name: "Check original request" })); await screen.findByRole("region", { name: "Original receipt confirmed" }); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(materialFieldCaseCommit).toHaveBeenCalledOnce(); expect(vi.mocked(materialFieldCaseOutcome).mock.calls[0].slice(0, 2)).toEqual([request.request_key, await expressionSha(expressionCanonical(request))]); });
  it("withholds a saved source after a late capture supersession before any association preview", async () => { await mount(); await saveSource(); vi.mocked(sourceLiteralExpressionDetail).mockImplementation(async () => { const revision = await literalRevision("gap_energy_source_value", sourceKey); revision.capture.latest_retained_capture_for_source = false; return revision; }); fireEvent.click(screen.getByRole("button", { name: "Load saved source expression" })); await screen.findByRole("button", { name: "Inspect source expression" }); fireEvent.click(screen.getByRole("button", { name: "Inspect source expression" })); await screen.findByText(/original source proof could not be verified/); expect(screen.queryByRole("button", { name: "Preview matching source proposal" })).not.toBeInTheDocument(); expect(materialFieldCasePreview).not.toHaveBeenCalled(); });
  it("does not resurrect an original fragment after material navigation", async () => { const late = deferred<unknown>(); vi.mocked(materialLiteralFieldPrepare).mockReturnValue(late.promise); const rendered = await mount(); await load(); const c = await literalContext(), report = await literalReport(); fireEvent.click(screen.getByRole("button", { name: "Prepare original source" })); const request = vi.mocked(materialLiteralFieldPrepare).mock.calls[0][0] as LiteralPrepareRequest; rendered.rerender(view("synthetic:next")); await act(async () => late.resolve(await literalPreparedResponse(request))); expect(screen.getByLabelText("Material ID")).toHaveValue("synthetic:next"); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); void c; void report; });
  it("clears original fragments after auth notifications and ignores late authenticated reads", async () => { const late = deferred<unknown>(); vi.mocked(materialLiteralFieldPrepare).mockReturnValue(late.promise); await mount(); await load(); fireEvent.click(screen.getByRole("button", { name: "Prepare original source" })); const request = vi.mocked(materialLiteralFieldPrepare).mock.calls[0][0] as LiteralPrepareRequest; act(() => notifyAuthChange()); await act(async () => late.resolve(await literalPreparedResponse(request))); expect(screen.queryByRole("region", { name: "Verified original source" })).not.toBeInTheDocument(); expect(screen.queryByLabelText("Material ID")).not.toBeInTheDocument(); });
  it("does not carry an unknown save across actors", async () => { const rendered = await mount(); await previewSource(); vi.mocked(sourceExpressionCommit).mockRejectedValueOnce(new ApiError(503, null, "unknown")); fireEvent.click(screen.getByRole("button", { name: "Save pending operation" })); await screen.findByRole("region", { name: "Original save recovery" }); const actor = "00000000-0000-4000-8000-000000000909"; vi.mocked(materialLiteralFieldCapabilities).mockResolvedValue({ ...literalPrepareCap, field_cases: { ...literalCaseCap, actor_user_id: actor } }); vi.mocked(sourceLiteralExpressionCapabilities).mockResolvedValue({ ...literalSourceCap, actor_user_id: actor }); rendered.rerender(view(literalMaterial, "gap_energy_source_value", actor)); await screen.findByText("Curator access"); expect(screen.queryByRole("region", { name: "Original save recovery" })).not.toBeInTheDocument(); expect(sourceExpressionOutcome).not.toHaveBeenCalled(); });
  it("reads all 14 raw cases using the returned 8+6 continuation", async () => { const entries = await Promise.all(LITERAL_CASE_FIELDS.map((field, i) => literalDetail(field, `00000000-0000-4000-8000-${String(800+i).padStart(12, "0")}`))); vi.mocked(materialLiteralFieldCaseMaterial).mockImplementation(async (_id, offset = 0) => ({ version: literalCaseCap.version, actor_user_id: literalActor, session_version: 2, material_id: literalMaterial, total: 14, offset, limit: 8, next_offset: offset === 0 ? 8 : null, entries: entries.slice(offset, offset+8), eligibility: { eligible: true, reason_codes: [] }, expressions_returned: 0, expressions_omitted: 0, entries_returned: offset === 0 ? 8 : 6, entries_omitted: 0, response_truncated: false, ...literalFlags })); await mount(); fireEvent.click(screen.getByRole("button", { name: "Load material cases" })); await screen.findByRole("button", { name: "Next case window" }); const first = screen.getByRole("region", { name: "Current literal field cases" }); expect(within(first).getAllByRole("button", { name: "Inspect field case" })).toHaveLength(8); fireEvent.click(screen.getByRole("button", { name: "Next case window" })); await waitFor(() => expect(within(screen.getByRole("region", { name: "Current literal field cases" })).getAllByRole("button", { name: "Inspect field case" })).toHaveLength(6)); expect(vi.mocked(materialLiteralFieldCaseMaterial).mock.calls[1].slice(0, 2)).toEqual([literalMaterial, 8]); expect(within(screen.getByRole("region", { name: "Current literal field cases" })).getByText("Spin density wave transition")).toBeInTheDocument(); });
});
