/** Synthetic local contract data only; no human review or scientific source fixture. */
import { expressionCanonical, expressionSha } from "@/lib/source-expressions";
import { FIELD_CASE_FIELDS, FIELD_CASE_OUTCOMES, FIELD_CASE_REASONS, FIELD_CASE_REQUEST_VERSION, FIELD_CASE_VERSION, type FieldCaseCapabilities, type FieldCaseContext, type FieldCaseDetail, type FieldCaseEntry, type FieldCaseMaterialPage, type FieldCaseReceipt, type FieldCaseRequest } from "@/lib/material-field-cases";
import { expressionActor, expressionGrant } from "./source-expression-test-data";
export const caseActor = expressionActor, caseGrant = expressionGrant;
export const caseMaterial = "synthetic-material:exact-1", caseTargetId = "00000000-0000-4000-8000-000000000301";
export const caseFlags = { scientific_acceptance: false as const, canonical_promotions: 0 as const, selected_result_association: "unestablished" as const, sample_identity_established: false as const, phase_identity_established: false as const, public_content_release: false as const, ml_training_approved: false as const };
const aliases: Record<string, string | null> = { measurement_method: "method_statement", sample_form: "sample_form_statement", space_group: "structure_statement", crystal_structure: "structure_statement", pairing_symmetry: "classification_statement", gap_structure: "classification_statement", is_unconventional: "classification_statement", competing_order: "classification_statement", tc_criterion: "tc_kelvin:criterion_statement:reported_result_condition", atomic_sites: null, site_occupancies: null, composition_identity: null, xi_gl_nm: null };
export const caseCap: FieldCaseCapabilities = { version: FIELD_CASE_VERSION, request_version: FIELD_CASE_REQUEST_VERSION, actor_user_id: caseActor, session_version: 2, curator_grant_id: caseGrant, can_write: true, field_ids: [...FIELD_CASE_FIELDS], outcomes: [...FIELD_CASE_OUTCOMES], reason_codes: [...FIELD_CASE_REASONS], expression_field_map: Object.fromEntries(FIELD_CASE_FIELDS.map(f => [f, Object.hasOwn(aliases, f) ? aliases[f] : f])), max_page_size: 8, max_operation_bytes: 32768, ...caseFlags };
export async function syntheticCaseContext(materialId = caseMaterial): Promise<FieldCaseContext> {
  const body = { kind: "retained_result", material_id: materialId, record_index: 0, entity_id: null, material: { id: materialId, formula: "SyntheticFormula" }, result: { paper_id: "synthetic-paper", tc_max: 23 }, event: null, state: null, sample: null };
  const canonical = expressionCanonical(body).replace('"tc_max":23', '"tc_max":23.000'), sha = await expressionSha(canonical);
  return { version: FIELD_CASE_VERSION, actor_user_id: caseActor, session_version: 2, target: { kind: "retained_result", material_id: materialId, record_index: 0, entity_id: null, expected_context_sha256: sha }, context_canonical_json: canonical, context_sha256: sha, closure: { material_id: materialId, kind: "retained_result", record_index: 0, entity_id: null, paper_id: "synthetic-paper", work_id: null, event_id: null, state_id: null, sample_id: null, legacy_result_id: "synthetic-retained-id", retained_record_sha256: "a".repeat(64) }, eligibility: { eligible: true, reason_codes: [] }, ...caseFlags };
}
export async function syntheticCaseRequest(field = "tc_kelvin"): Promise<FieldCaseRequest> { const context = await syntheticCaseContext(); return { version: FIELD_CASE_REQUEST_VERSION, request_key: "synthetic:case:target", operation: "target", payload: { field_id: field, target: context.target } }; }
export async function syntheticCaseReceipt(request: FieldCaseRequest, dryRun = true, contextText?: string, id = caseTargetId): Promise<FieldCaseReceipt> {
  const context = contextText ?? (await syntheticCaseContext()).context_canonical_json, contextSha = await expressionSha(context), requestText = expressionCanonical(request), requestSha = await expressionSha(requestText);
  const previewText = expressionCanonical({ version: FIELD_CASE_VERSION, actor: { actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2 }, request_sha256: requestSha, receipt_id: id, context_sha256: contextSha }), previewSha = await expressionSha(previewText), p = request.payload;
  const body = { id, actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2, operation: request.operation, request_key: request.request_key, request_json: requestText, payload: p, request_sha256: requestSha, preview_json: previewText, preview_sha256: previewSha, context_json: context, context_sha256: contextSha, field_id: request.operation === "target" ? request.payload.field_id : "tc_kelvin", target_id: request.operation === "target" ? null : request.payload.target_id, chain_key: request.operation === "target" ? null : request.operation === "attempt" ? request.payload.target_id : "b".repeat(64), predecessor_id: request.operation === "target" ? null : request.payload.predecessor?.id ?? null, predecessor_sha256: request.operation === "target" ? null : request.payload.predecessor?.record_sha256 ?? null, expression_revision_id: request.operation === "association" ? request.payload.expression_revision_id : null, expression_record_sha256: request.operation === "association" ? request.payload.expression_record_sha256 : null };
  const text = expressionCanonical(body);
  return { version: FIELD_CASE_VERSION, receipt_id: id, receipt_sha256: await expressionSha(text), operation: request.operation, target_id: request.operation === "target" ? id : request.payload.target_id, actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2, request_key: request.request_key, request_sha256: requestSha, preview_sha256: previewSha, request_canonical_json: requestText, preview_canonical_json: previewText, receipt_canonical_json: text, replayed: false, dry_run: dryRun, pending_ledger_written: !dryRun, ...caseFlags };
}
export async function syntheticCaseEntry(field = "tc_kelvin"): Promise<FieldCaseEntry> { const receipt = await syntheticCaseReceipt(await syntheticCaseRequest(field)), body = JSON.parse(receipt.receipt_canonical_json); return { id: receipt.receipt_id, record_sha256: receipt.receipt_sha256, record_canonical_json: receipt.receipt_canonical_json, operation: "target", payload: body.payload, context_canonical_json: body.context_json, context_sha256: body.context_sha256, created_at: "2026-10-02T00:00:00Z", eligibility: { eligible: true, reason_codes: [] }, ...caseFlags }; }
export async function syntheticCaseDetail(field = "tc_kelvin"): Promise<FieldCaseDetail> { return { version: FIELD_CASE_VERSION, actor_user_id: caseActor, session_version: 2, target: await syntheticCaseEntry(field), associations: [], attempts: [], association_total: 0, attempt_total: 0, association_returned: 0, attempt_returned: 0, association_omitted: 0, attempt_omitted: 0, response_truncated: false, ...caseFlags }; }
export async function syntheticMaterialPage(withTarget = true, field = "tc_kelvin"): Promise<FieldCaseMaterialPage> { return { version: FIELD_CASE_VERSION, actor_user_id: caseActor, session_version: 2, material_id: caseMaterial, total: withTarget ? 1 : 0, offset: 0, limit: 8, next_offset: null, entries: withTarget ? [await syntheticCaseDetail(field)] : [], eligibility: { eligible: true, reason_codes: [] }, expressions_returned: 0, expressions_omitted: 0, entries_returned: withTarget ? 1 : 0, entries_omitted: 0, response_truncated: false, ...caseFlags }; }
