/** Synthetic byte-contract fixtures only; never evidence of a real source review. */
import { expressionSha } from "@/lib/source-expressions";
import { FIELD_REVIEW_CHECKS, FIELD_REVIEW_FIELDS, FIELD_REVIEW_PROFILE, FIELD_REVIEW_VERSION, type ReviewCapabilities, type ReviewContext, type ReviewEffective, type ReviewItem, type ReviewReceipt, type ReviewRequest } from "@/lib/material-field-review";
export const reviewActor = "00000000-0000-4000-8000-000000000901", reviewGrant = "00000000-0000-4000-8000-000000000902", reviewTarget = "00000000-0000-4000-8000-000000000903", reviewExpression = "00000000-0000-4000-8000-000000000904", reviewImporter = "00000000-0000-4000-8000-000000000905", reviewDecision = "00000000-0000-4000-8000-000000000906", reviewReceiptId = "00000000-0000-4000-8000-000000000907";
export const reviewFlags = { scientific_acceptance: false as const, canonical_promotions: 0 as const, ml_training_approved: false as const, public_release_authorized: false as const, sample_identity_established: false as const, phase_identity_established: false as const };
export const reviewCap: ReviewCapabilities = { version: FIELD_REVIEW_VERSION, profile_version: FIELD_REVIEW_PROFILE, actor_user_id: reviewActor, session_version: 2, reviewer_grant_id: reviewGrant, can_write: true, field_ids: [...FIELD_REVIEW_FIELDS], checks: [...FIELD_REVIEW_CHECKS], max_items: 8, max_operation_bytes: 32768, max_page_size: 8, supported_target_kinds: ["retained_result"], field_fidelity_acceptance_available: true, support_scope: "finite_flat_retained_records_with_current_source_expression_and_reviewed_tc_window", ...reviewFlags };
export function syntheticReviewCanonical(value: unknown): string { if (typeof value === "number") return value === 1.5 ? "1.500" : JSON.stringify(value); if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(syntheticReviewCanonical).join(",")}]`; return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${syntheticReviewCanonical((value as Record<string, unknown>)[k])}`).join(",")}}`; }
export async function syntheticReviewContext(field: ReviewItem["field_id"] = "tc_criterion"): Promise<ReviewContext> {
  const candidate = { field_id: field, value: field === "pressure_gpa" ? { raw_value: "about 1.500", raw_unit: "GPa", value: 1.5, unit: "GPa", status: "parsed" } : { raw_value: "resistive onset", status: "source_statement" }, value_spans: [{ start: 22, end: 36, sha256: "e".repeat(64) }], unit_spans: field === "pressure_gpa" ? [{ start: 37, end: 40, sha256: "f".repeat(64) }] : [], component: { kind: "condition", index: 0, field_id: field === "tc_criterion" ? "criterion_statement" : field === "measurement_method" ? "method_statement" : "pressure_gpa", role: "reported_result_condition" }, window: { id: "synthetic-source-window", raw_label: "Sample A, onset result" } };
  const missingness = { aliases: {}, missing: true, coarse_tc_type: null }, tuple = { subject: { formula: "SyntheticFormula", sample_label: "Sample A", formula_scope: "printed_source" }, window: candidate.window, source_role: "source_reported", model: null };
  const subject = { target_id: reviewTarget, field_id: field, context_sha256: "b".repeat(64), admission: { eligible: true, reason: null, visibility_version: "material-visibility/1.0.0", paper_id: "synthetic-paper", legacy_result_id: "synthetic-retained-result", retained_record_sha256: "c".repeat(64) }, retained_result_summary: { tc_kelvin: 23, paper_id: "synthetic-paper", year: 2009, knowledge_origin: "Observed", tc_type: null }, candidate, missingness, tuple, candidate_sha256: await expressionSha(syntheticReviewCanonical(candidate)), missingness_sha256: await expressionSha(syntheticReviewCanonical(missingness)), tuple_sha256: await expressionSha(syntheticReviewCanonical(tuple)), target_user_id: reviewImporter, association_user_id: null, importer_user_id: reviewImporter, capture_user_id: reviewImporter, tc_importer_user_id: null, eligible: true, reason_codes: [] as string[] };
  const text = syntheticReviewCanonical(subject), sha = await expressionSha(text);
  const item: ReviewItem = { target_id: reviewTarget, target_sha256: "a".repeat(64), field_id: field, association: null, expression: { id: reviewExpression, record_sha256: "d".repeat(64), projection_sha256: "e".repeat(64) }, tc_expression: null, source_identity: { paper_id: "synthetic-paper", work_id: null }, component: candidate.component as ReviewItem["component"], expected_subject_sha256: sha, expected_candidate_sha256: subject.candidate_sha256, expected_missingness_sha256: subject.missingness_sha256, expected_tuple_sha256: subject.tuple_sha256, decision: "request_clarification", checks: Object.fromEntries(FIELD_REVIEW_CHECKS.map(c => [c, "unresolved"])) as ReviewItem["checks"], source_inspection_attested: false, rationale: "Source inspection and exact scope review are required.", predecessor: null, resolves_decision_id: null };
  return { version: FIELD_REVIEW_VERSION, profile_version: FIELD_REVIEW_PROFILE, actor_user_id: reviewActor, session_version: 2, subject, subject_canonical_json: text, subject_sha256: sha, item_template: item, ...reviewFlags };
}
export async function syntheticReviewRequest(accept = false): Promise<ReviewRequest> { const context = await syntheticReviewContext(); return { version: FIELD_REVIEW_VERSION, profile_version: FIELD_REVIEW_PROFILE, request_key: "synthetic:field-review:1", items: [{ ...context.item_template, ...(accept ? { decision: "accept" as const, source_inspection_attested: true, checks: Object.fromEntries(FIELD_REVIEW_CHECKS.map(c => [c, "satisfied"])) as ReviewItem["checks"] } : {}) }] }; }
export async function syntheticReviewReceipt(request: ReviewRequest, dryRun = true): Promise<ReviewReceipt> {
  const text = syntheticReviewCanonical(request), sha = await expressionSha(text), preview = { version: FIELD_REVIEW_VERSION, receipt_id: reviewReceiptId, actor_user_id: reviewActor, actor_grant_id: reviewGrant, actor_session_version: 2, request_sha256: sha }, previewText = syntheticReviewCanonical(preview), previewSha = await expressionSha(previewText);
  const body = { id: reviewReceiptId, actor_user_id: reviewActor, actor_grant_id: reviewGrant, actor_session_version: 2, request_key: request.request_key, request_json: text, request_sha256: sha, preview_json: previewText, preview_sha256: previewSha }, bodyText = syntheticReviewCanonical(body);
  return { version: FIELD_REVIEW_VERSION, receipt_id: reviewReceiptId, receipt_sha256: await expressionSha(bodyText), actor_user_id: reviewActor, actor_grant_id: reviewGrant, actor_session_version: 2, request_key: request.request_key, request_sha256: sha, preview_sha256: previewSha, request_canonical_json: text, preview_canonical_json: previewText, receipt_canonical_json: bodyText, dry_run: dryRun, replayed: false, review_ledger_written: !dryRun, decision_ids: [reviewDecision], ...reviewFlags };
}
export async function syntheticReviewEffective(accepted = false, held = false): Promise<ReviewEffective> {
  const context = await syntheticReviewContext(), request = await syntheticReviewRequest(true), item = request.items[0], body = { id: reviewDecision, actor_user_id: reviewActor, actor_grant_id: reviewGrant, actor_session_version: 2, request_id: reviewReceiptId, request_sha256: "f".repeat(64), item_index: 0, target_id: reviewTarget, field_id: item.field_id, decision: item.decision, payload: item, chain_key: `${reviewTarget}:${item.field_id}`, predecessor_id: null, predecessor_sha256: null }, text = syntheticReviewCanonical(body);
  const usable = accepted && !held, value = usable ? context.subject.candidate : null, canonical = usable ? syntheticReviewCanonical(value) : null;
  return { version: FIELD_REVIEW_VERSION, actor_user_id: reviewActor, session_version: 2, target_id: reviewTarget, field_id: item.field_id, field_fidelity_accepted: usable, effective_value: value, effective_value_canonical_json: canonical, decision: accepted || held ? { id: reviewDecision, record_sha256: await expressionSha(text), record_canonical_json: text, target_id: reviewTarget, field_id: item.field_id, decision: "accept", is_head: true, field_fidelity_accepted: usable, effective_value: value, effective_value_canonical_json: canonical, reason_codes: held ? ["source_expression_held", "subject_changed"] : [], source_identity_status: usable ? "reviewed_field_fidelity_only" : "unestablished", created_at: "2026-10-02T00:00:00Z", ...reviewFlags } : null, ...reviewFlags };
}
