/** Original table facts plus synthetic actor/target receipts for UI tests only. */
import oracle from "./material-table-oracle.json";
/** Actor, target and receipt identities below are synthetic; source cells retain the cited original text. */
import { expressionCanonical, expressionSha, type ExpressionCapabilities, type ExpressionReceipt } from "@/lib/source-expressions";
import { FIELD_CASE_VERSION } from "@/lib/material-field-cases";
import { TABLE_READ_HOLD_REASONS, TABLE_CASE_FIELDS, TABLE_CASE_VERSION, TABLE_CASE_REQUEST_VERSION, TABLE_PROFILE, TABLE_PACKAGE_VERSION, TABLE_INTAKE_VERSION, TABLE_REGISTRY_SHA, TABLE_ROLES, compileTablePackage, tableExpressionRecovery, tableCaseRecovery, tableStoredSourceIdentity, tableStoredCaseIdentity, type TablePackage, type TablePrepared, type TableCaseCapabilities, type TableCaseContext, type TableCaseRequest, type TableCaseReceipt, type TableCaseDetail, type TableSourceRevision, type TableExpressionPage } from "@/lib/material-table-fields";
import { caseActor, caseGrant, caseCap, caseFlags, caseMaterial, caseTargetId, syntheticCaseContext } from "./material-field-case-test-data";
export { caseActor as tableActor, caseGrant as tableGrant, caseFlags as tableFlags, caseMaterial as tableMaterial };
export const tableSourceId = "00000000-0000-4000-8000-000000000701", tableReceiptId = "00000000-0000-4000-8000-000000000702", tableCaptureId = "00000000-0000-4000-8000-000000000703";
export const tableCaseCap: TableCaseCapabilities & { profile: string; field_request_versions: Record<string, string> } = { ...caseCap, version: TABLE_CASE_VERSION, request_version: TABLE_CASE_REQUEST_VERSION, profile: TABLE_PROFILE, read_hold_reason_codes: [...TABLE_READ_HOLD_REASONS], field_ids: [...TABLE_CASE_FIELDS], expression_field_map: Object.fromEntries(TABLE_CASE_FIELDS.map(f => [f, f])), field_request_versions: Object.fromEntries(TABLE_CASE_FIELDS.map(f => [f, TABLE_CASE_REQUEST_VERSION])) };
export const tableSourceCap: ExpressionCapabilities = { version: TABLE_INTAKE_VERSION, package_version: TABLE_PACKAGE_VERSION, actor_user_id: caseActor, session_version: 2, can_import: true, curator_grant_id: caseGrant, registry_sha256: TABLE_REGISTRY_SHA, field_profiles: TABLE_ROLES, max_source_bytes: 131072, max_expressions: 20, max_package_bytes: 131072, max_projection_bytes: 32768, max_expression_page_size: 8, scope: "private_pending_source_expressions", scientific_acceptance: false, canonical_promotions: 0, public_content_release: false };
export async function tableContext(material = caseMaterial, index = 0): Promise<TableCaseContext> {
  const c = await syntheticCaseContext(material), body = JSON.parse(c.context_canonical_json); body.record_index = index; body.material.formula = "Mo5P1.1B1.9"; delete body.result.tc_max; body.result.tc_kelvin = index === 0 ? 23 : 21.5; body.result.tc_criterion = index === 0 ? "onset" : "zero_resistance";
  c.context_canonical_json = JSON.stringify(body); c.context_sha256 = await expressionSha(c.context_canonical_json); c.target.record_index = index; c.target.expected_context_sha256 = c.context_sha256; c.closure.record_index = index; c.closure.legacy_result_id = `synthetic-retained-${index}`; c.closure.retained_record_sha256 = index === 0 ? "a".repeat(64) : "b".repeat(64); return c;
}
export async function tableSourceReceipt(p: TablePrepared, key = "synthetic:source", dryRun = true): Promise<ExpressionReceipt> {
  const { source_text_base64: _source, ...retained } = p.package, packageText = expressionCanonical(retained), manifest = await Promise.all(p.projections.map(async (projection, i) => ({ entry_index: i, expression_key: projection.expression_key, entry_sha256: await expressionSha(expressionCanonical(p.package.expressions[i])), projection_sha256: await expressionSha(expressionCanonical(projection)), predecessor_id: null, predecessor_sha256: null, revision_number: 1 })));
  const actor = { actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2 }, requestText = expressionCanonical({ version: TABLE_INTAKE_VERSION, package_sha256: p.packageSha }), requestSha = await expressionSha(requestText), previewText = expressionCanonical({ version: TABLE_INTAKE_VERSION, request_key: key, request_sha256: requestSha, actor, manifest }), previewSha = await expressionSha(previewText);
  const body = { id: tableReceiptId, ...actor, request_key: key, request_sha256: requestSha, preview_sha256: previewSha, capture_id: tableCaptureId, package_json: packageText, package_sha256: p.packageSha, expression_count: manifest.length, expression_manifest: manifest }, receiptText = expressionCanonical(body);
  return { version: TABLE_INTAKE_VERSION, receipt_id: tableReceiptId, receipt_sha256: await expressionSha(receiptText), ...actor, request_key: key, request_sha256: requestSha, preview_sha256: previewSha, capture_id: tableCaptureId, package_sha256: p.packageSha, package_canonical_json: packageText, request_canonical_json: requestText, preview_canonical_json: previewText, receipt_canonical_json: receiptText, expression_count: manifest.length, expression_manifest: manifest, count_scope: "source_expression_revisions_not_independent_experiments", replayed: false, dry_run: dryRun, pending_ledger_written: !dryRun, status: "pending", scientific_acceptance: false, canonical_promotions: 0, selected_result_association: "unestablished", public_content_release: false };
}
export async function tableRevision(field = "electronic_specific_heat_coefficient_source_value", key = "synthetic:source", detail = true, pkg?: TablePackage): Promise<TableSourceRevision & { version?: string }> {
  const p = await compileTablePackage(pkg ?? await tablePackage(field)), projection = p.projections[0], receipt = await tableSourceReceipt(p, key, false), entrySha = receipt.expression_manifest[0].entry_sha256, projectionText = expressionCanonical(projection), metadataText = expressionCanonical(p.package.source);
  const body = { id: tableSourceId, actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2, import_receipt_id: receipt.receipt_id, import_receipt_sha256: receipt.receipt_sha256, capture_id: tableCaptureId, entry_index: 0, entry_sha256: entrySha, expression_key: projection.expression_key, field_id: field, revision_number: 1, predecessor_id: null, predecessor_sha256: null, projection_json: projectionText, projection_sha256: await expressionSha(projectionText) }, text = expressionCanonical(body);
  return { ...(detail ? { version: TABLE_INTAKE_VERSION } : {}), id: tableSourceId, record_sha256: await expressionSha(text), expression_key: projection.expression_key, revision_canonical_json: text, entry_index: 0, source_entry_sha256: entrySha, import_receipt_id: receipt.receipt_id, import_receipt_sha256: receipt.receipt_sha256, import_receipt: detail ? receipt : null, revision_number: 1, predecessor_id: null, predecessor_sha256: null, projection_sha256: body.projection_sha256, projection_canonical_json: projectionText, projection, source_entry: p.package.expressions[0], is_expression_head: true, capture: { id: tableCaptureId, record_sha256: "d".repeat(64), source: p.package.source, source_metadata_canonical_json: metadataText, source_content_sha256: p.package.source_content_sha256, metadata_sha256: await expressionSha(metadataText), retained_utf8_bytes: p.retainedBytes, fragment_integrity: "server_verified_retained_bytes", parent_integrity: "declared_not_verified", publication_revision_verified: false, rights_verified: false, publication_currentness_verified: false, latest_retained_capture_for_source: true, public_content_release: false } };
}
export async function tableCaseReceipt(request: TableCaseRequest, dryRun = true, field = "electronic_specific_heat_coefficient_source_value", context: TableCaseContext | undefined = undefined, expression?: TableSourceRevision, targetId = caseTargetId): Promise<TableCaseReceipt> {
  context = context ?? await tableContext(); const id = request.operation === "target" ? targetId : "00000000-0000-4000-8000-000000000706", requestText = expressionCanonical(request), requestSha = await expressionSha(requestText), actor = { actor_user_id: caseActor, actor_grant_id: caseGrant, actor_session_version: 2 }, previewText = expressionCanonical({ version: TABLE_CASE_VERSION, actor, request_sha256: requestSha, receipt_id: id, context_sha256: context.context_sha256 }), previewSha = await expressionSha(previewText), p = request.payload;
  const body = { id, ...actor, operation: request.operation, request_key: request.request_key, request_json: requestText, payload: p, request_sha256: requestSha, preview_json: previewText, preview_sha256: previewSha, context_json: context.context_canonical_json, context_sha256: context.context_sha256, field_id: request.operation === "target" ? request.payload.field_id : field, target_id: request.operation === "target" ? null : request.payload.target_id, chain_key: request.operation === "target" ? null : request.operation === "attempt" ? request.payload.target_id : await expressionSha(expressionCanonical([request.payload.target_id, expression?.expression_key ?? "synthetic-source"])), predecessor_id: request.operation === "target" ? null : request.payload.predecessor?.id ?? null, predecessor_sha256: request.operation === "target" ? null : request.payload.predecessor?.record_sha256 ?? null, expression_revision_id: request.operation === "association" ? request.payload.expression_revision_id : null, expression_record_sha256: request.operation === "association" ? request.payload.expression_record_sha256 : null }, receiptText = expressionCanonical(body);
  return { version: TABLE_CASE_VERSION, receipt_id: id, receipt_sha256: await expressionSha(receiptText), operation: request.operation, target_id: request.operation === "target" ? id : request.payload.target_id, ...actor, request_key: request.request_key, request_sha256: requestSha, preview_sha256: previewSha, request_canonical_json: requestText, preview_canonical_json: previewText, receipt_canonical_json: receiptText, replayed: false, dry_run: dryRun, pending_ledger_written: !dryRun, ...caseFlags };
}
export async function tableDetail(field = "electronic_specific_heat_coefficient_source_value", targetId = caseTargetId): Promise<TableCaseDetail> { const c = await tableContext(), request: TableCaseRequest = { version: TABLE_CASE_REQUEST_VERSION, request_key: "synthetic:table-target", operation: "target", payload: { field_id: field, target: c.target } }, receipt = await tableCaseReceipt(request, false, field, c, undefined, targetId), body = JSON.parse(receipt.receipt_canonical_json); return { version: TABLE_CASE_VERSION, actor_user_id: caseActor, session_version: 2, target: { id: receipt.receipt_id, record_sha256: receipt.receipt_sha256, record_canonical_json: receipt.receipt_canonical_json, operation: "target", payload: body.payload, context_canonical_json: body.context_json, context_sha256: body.context_sha256, created_at: "2026-10-02T00:00:00Z", eligibility: { eligible: true, reason_codes: [] }, ...caseFlags }, associations: [], attempts: [], association_total: 0, attempt_total: 0, association_returned: 0, attempt_returned: 0, association_omitted: 0, attempt_omitted: 0, response_truncated: false, ...caseFlags }; }
export function emptyTableSources(): TableExpressionPage { return { version: TABLE_INTAKE_VERSION, total: 0, offset: 0, limit: 8, count_scope: "current_pending_expression_heads_not_experiments_or_verified_properties", expressions: [], scientific_acceptance: false, canonical_promotions: 0 }; }
export async function tableStorageFixture(kind: "source" | "case") {
  if (kind === "source") { const p = await compileTablePackage(await tablePackage()), preview = await tableSourceReceipt(p, "synthetic:persistent-source"), ref = { ...tableExpressionRecovery(p, tableSourceCap, preview.request_key), previewSha: preview.preview_sha256, manifestCanonical: expressionCanonical(preview.expression_manifest), receiptId: preview.receipt_id, receiptSha: preview.receipt_sha256, captureId: preview.capture_id }, saved = await tableSourceReceipt(p, preview.request_key, false); saved.replayed = true; return { identity: await tableStoredSourceIdentity(ref), saved }; }
  const c = await tableContext(), request: TableCaseRequest = { version: TABLE_CASE_REQUEST_VERSION, request_key: "synthetic:persistent-case", operation: "target", payload: { field_id: "electronic_specific_heat_coefficient_source_value", target: c.target } }, preview = await tableCaseReceipt(request), ref = { ...tableCaseRecovery(request, tableCaseCap, await expressionSha(expressionCanonical(request))), previewSha: preview.preview_sha256, receiptId: preview.receipt_id, receiptSha: preview.receipt_sha256 }, saved = await tableCaseReceipt(request, false); saved.replayed = true; return { identity: tableStoredCaseIdentity(ref), saved };
}

/** Frozen independently compiled Python oracle for source cells, with synthetic protocol identities. */
// Public deterministic identity digests are kept separate from reconstructed projection fields.
// Expected projection hashes still cover every field of the complete Python projection.

export async function tablePackage(field?: string): Promise<TablePackage> {
  const p = structuredClone(oracle.package) as unknown as TablePackage;
  if (field) p.expressions = p.expressions.filter(e => e.field_id === field).slice(0, 1);
  return p;
}
export const tableOracle = {
  ...oracle,
  projections: oracle.projections.map(({ expression_identity_digest, ...projection }) => ({
    ...projection, expression_key: expression_identity_digest,
  })),
};
